SELECT * FROM SYSIBM.TABLES;
SELECT * FROM SYSIBM.TABLES_S;
SELECT * FROM SYSIBM.SQLTABLES;

SELECT TABLE_NAME, TABLE_PARTITION,PARTITION_NUMBER, NUMBER_ROWS,NUMBER_PAGES,DATA_SIZE,NUMBER_DISTINCT_INDEXES,
SYSTEM_TABLE_SCHEMA,SYSTEM_TABLE_NAME, SYSTEM_TABLE_MEMBER
                  FROM SYSIBM.SYSPARTITIONSTAT 
WHERE TABLE_SCHEMA LIKE ('%HOSVITAL%')
ORDER BY TABLE_NAME;

SELECT * FROM SYSIBM.SQLTABLEPRIVILEGES WHERE GRANTEE LIKE ('%ABERNAL%');
SELECT * FROM SYSIBM.SQLSCHEMAS;

SET SCHEMA SYSPROC;
SELECT * FROM SYSPROC.SYSAUDIT_END;

SELECT * FROM SYSIBMADM.USER_INFO;

SELECT * FROM QGPL.QSRVSRC;
SELECT * FROM SYSIBMADM.ENV_SYS_INFO;  --