create table maestre.actual2 (campo1 char(10));

SELECT * FROM SYSIBM.SQLTABLES where  TABLE_SCHEM='HOSVIPRU' and table_type='TABLE'; 
SELECT * FROM SYSIBM.SQLTABLES where  TABLE_SCHEM='HOSVITAL' and table_type='TABLE'; 
select count(*) from hosvipru.hccom1;

create table hosvipru.pqueue_2021030  as (select  * from hosvipru.pqueue) with data;

select aspgrp,sum(storage_used) from SYSIBMADM.USER_STORAGE group by aspgrp;

SELECT * FROM SYSIBMADM.USER_STORAGE order by aspgrp, storage_used;

SELECT * FROM SYSIBM.SQLTABLES 
where  TABLE_CAT='IASP' AND TABLE_SCHEM='HOSVIPRU' and table_type='TABLE'; 


SELECT TABLE_NAME, TABLE_PARTITION,PARTITION_NUMBER, NUMBER_ROWS,NUMBER_PAGES,DATA_SIZE,NUMBER_DISTINCT_INDEXES,
SYSTEM_TABLE_SCHEMA,SYSTEM_TABLE_NAME, SYSTEM_TABLE_MEMBER
FROM SYSIBM.SYSPARTITIONSTAT 
WHERE TABLE_SCHEMA LIKE ('%HOSVIPRU%')
ORDER BY TABLE_NAME;

SELECT * FROM HOSVIPRU.INGRESOS WHERE INGFECADM >= '2020-08-01 00:00:00';  -- COPIA DE AGOSTO 21
