SELECT AVERAGE_EXECUTION_TIME_S as TIME_SECONDS, NUM_EXECUTIONS as EXECUTIONS, STMT_TEXT as TEXT 
FROM SYSIBMADM.TOP_DYNAMIC_SQL 
WHERE upper(STMT_TEXT) like 'SELECT%' ORDER BY AVERAGE_EXECUTION_TIME_S DESC FETCH FIRST 10 ROWS ONLY;

SELECT NUM_EXECUTIONS as EXECUTIONS, AVERAGE_EXECUTION_TIME_S as TIME_SECONDS, STMT_TEXT as TEXT
 FROM SYSIBMADM.TOP_DYNAMIC_SQL 
WHERE upper(STMT_TEXT) like 'SELECT%' ORDER BY NUM_EXECUTIONS DESC FETCH FIRST 10 ROWS ONLY;
SELECT T1.* FROM (SELECT TABSCHEMA, TABNAME, DATA_OBJECT_P_SIZE + INDEX_OBJECT_P_SIZE + LONG_OBJECT_P_SIZE + LOB_OBJECT_P_SIZE + XML_OBJECT_P_SIZE AS TOTAL_SIZE, INDEX_OBJECT_P_SIZE, DICTIONARY_SIZE FROM SYSIBMADM.ADMINTABINFO ) AS T1 ORDER BY T1.TOTAL_SIZE DESC FETCH FIRST 1000 ROWS ONLY WITH UR;

SELECT SUBSTR(TABSCHEMA,1,18) TABSCHEMA,
SUBSTR(TABNAME,1,30) TABNAME,
SUM(DATA_OBJECT_P_SIZE) DATA_OBJECT_P_SIZE,
SUM(INDEX_OBJECT_P_SIZE) INDEX_OBJECT_P_SIZE,
SUM(LONG_OBJECT_P_SIZE) LONG_OBJECT_P_SIZE,
SUM(LOB_OBJECT_P_SIZE) LOB_OBJECT_P_SIZE,
SUM(XML_OBJECT_P_SIZE) XML_OBJECT_P_SIZE
FROM SYSIBMADM.ADMINTABINFO
WHERE TABSCHEMA NOT LIKE 'SYS%'
GROUP BY TABSCHEMA, TABNAME;


-- Conteo de indexes


select table_schema,count(*)  from  qsys2.sysindexes
group by table_schema
order by table_schema;



select * from qsys2.SYSCST;
select * from qsys2.SYSPARMS;

select * from qsys2.TABLE_CONSTRAINTS;

select * from qsys2.sysindexes;

select * from qsys2.SYSPACKAGE;
select * from qsys2.SYSVIEWS;
