/*

Cordial saludo,

De manera atenta nos permitimos solicitar la generación de reportes de ingreso de pacientes del mes de agosto con el código de diagnóstico B342. 
Adicionalmente, es necesario contar con el número de pacientes que se dieron egreso antes de 6 horas, antes de 12 horas, antes de 24 horas y antes de 48 horas.

Lo anterior debido a una solicitud de la Dirección Científica y Dirección General a la Coordinación de Urgencias.

Muchas gracias por su colaboración.

*/

SELECT * FROM HOSVITAL.INGRESOS;
SELECT * FROM HOSVITAL.MAEDIA;


--Primer Query

SELECT I.MPTDOC TIPO_DOC,I.MPCEDU DOCUMENTO ,C.MPNOMC PACIENTE , I.INGFECADM INGRESO ,I.INGFECEGR EGRESO,I.INGENTDX, I.INGSALDX, I.INGDXSAL1, I.INGDXSAL2, I.INGDXSAL3
FROM HOSVITAL.INGRESOS I
INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC=I.MPTDOC AND C.MPCEDU=I.MPCEDU)
-- INNER JOIN HOSVITAL.MAEDIA M ON (M.DMCOD =
WHERE I.INGFECADM >= '2020-08-01 00:00:00' AND I.INGFECADM <= '2020-08-31 23:59:59' AND (I.INGENTDX='B342' OR I.INGSALDX='B342' OR I.INGDXSAL1 ='B342' OR I.INGDXSAL2='B342'  OR I.INGDXSAL3='B342')
ORDER BY I.INGFECADM;


-- Segundo Query


-- HASTA 6 HORAS

SELECT I.MPTDOC TIPO_DOC,I.MPCEDU DOCUMENTO ,C.MPNOMC PACIENTE , I.INGFECADM INGRESO ,I.INGFECEGR EGRESO,I.INGENTDX, I.INGSALDX, I.INGDXSAL1, I.INGDXSAL2, I.INGDXSAL3
FROM HOSVITAL.INGRESOS I
INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC=I.MPTDOC AND C.MPCEDU=I.MPCEDU)
-- INNER JOIN HOSVITAL.MAEDIA M ON (M.DMCOD =
WHERE I.INGFECADM >= '2020-08-01 00:00:00' AND I.INGFECADM <= '2020-08-31 23:59:59' AND (I.INGENTDX='B342' OR I.INGSALDX='B342' OR I.INGDXSAL1 ='B342' OR I.INGDXSAL2='B342'  OR I.INGDXSAL3='B342') AND  
 I.INGFECEGR < (  I.INGFECADM + 6 HOURS)
ORDER BY I.INGFECADM;

-- ENTRE 6 Y 12 HORAS

SELECT I.MPTDOC TIPO_DOC,I.MPCEDU DOCUMENTO ,C.MPNOMC PACIENTE , I.INGFECADM INGRESO ,I.INGFECEGR EGRESO,I.INGENTDX, I.INGSALDX, I.INGDXSAL1, I.INGDXSAL2, I.INGDXSAL3
FROM HOSVITAL.INGRESOS I
INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC=I.MPTDOC AND C.MPCEDU=I.MPCEDU)
-- INNER JOIN HOSVITAL.MAEDIA M ON (M.DMCOD =
WHERE I.INGFECADM >= '2020-08-01 00:00:00' AND I.INGFECADM <= '2020-08-31 23:59:59' AND (I.INGENTDX='B342' OR I.INGSALDX='B342' OR I.INGDXSAL1 ='B342' OR I.INGDXSAL2='B342'  OR I.INGDXSAL3='B342') AND  
 I.INGFECEGR  BETWEEN  (  I.INGFECADM + 6 HOURS) AND   (  I.INGFECADM + 12 HOURS)
ORDER BY I.INGFECADM;

-- ENTRE 12 Y 24 HORAS


SELECT I.MPTDOC TIPO_DOC,I.MPCEDU DOCUMENTO ,C.MPNOMC PACIENTE , I.INGFECADM INGRESO ,I.INGFECEGR EGRESO,I.INGENTDX, I.INGSALDX, I.INGDXSAL1, I.INGDXSAL2, I.INGDXSAL3
FROM HOSVITAL.INGRESOS I
INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC=I.MPTDOC AND C.MPCEDU=I.MPCEDU)
-- INNER JOIN HOSVITAL.MAEDIA M ON (M.DMCOD =
WHERE I.INGFECADM >= '2020-08-01 00:00:00' AND I.INGFECADM <= '2020-08-31 23:59:59' AND (I.INGENTDX='B342' OR I.INGSALDX='B342' OR I.INGDXSAL1 ='B342' OR I.INGDXSAL2='B342'  OR I.INGDXSAL3='B342') AND 
 I.INGFECEGR  BETWEEN  (  I.INGFECADM + 12 HOURS) AND   (  I.INGFECADM + 24 HOURS)
ORDER BY I.INGFECADM;

-- ENTRE 24  Y 48 HORAS


SELECT I.MPTDOC TIPO_DOC,I.MPCEDU DOCUMENTO ,C.MPNOMC PACIENTE , I.INGFECADM INGRESO ,I.INGFECEGR EGRESO,I.INGENTDX, I.INGSALDX, I.INGDXSAL1, I.INGDXSAL2, I.INGDXSAL3
FROM HOSVITAL.INGRESOS I
INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC=I.MPTDOC AND C.MPCEDU=I.MPCEDU)
-- INNER JOIN HOSVITAL.MAEDIA M ON (M.DMCOD =
WHERE I.INGFECADM >= '2020-08-01 00:00:00' AND I.INGFECADM <= '2020-08-31 23:59:59' AND (I.INGENTDX='B342' OR I.INGSALDX='B342' OR I.INGDXSAL1 ='B342' OR I.INGDXSAL2='B342'  OR I.INGDXSAL3='B342') AND --  I.MPCEDU='1075245098' AND 
 I.INGFECEGR  BETWEEN  (  I.INGFECADM + 24 HOURS) AND   (  I.INGFECADM +48 HOURS)
ORDER BY I.INGFECADM;


select count(*) total FROM HOSVITAL.INGRESOS I INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC=I.MPTDOC AND C.MPCEDU=I.MPCEDU) WHERE I.INGFECADM >='2020-08-01 00:00:00' AND I.INGFECADM <='2020-08-31 23:59:59' AND (I.INGENTDX='B342' OR I.INGSALDX='B342' OR I.INGDXSAL1 ='B342' OR I.INGDXSAL2='B342' OR I.INGDXSAL3='B342') AND I.INGFECEGR BETWEEN (I.INGFECADM + 12 HOURS) AND (I.INGFECADM + 24 HOURS)

