-- Excel

SELECT HOSVITAL.MAEPAB11.MPCODP AS COD_PABELLON, HOSVITAL.MAEPAB.MPNOMP AS PABELLON, HOSVITAL.MAEPAB11.MPNUMC AS CAMA, HOSVITAL.MAEPAB11.HISCAMEDO AS ESTADO_CAMA, HOSVITAL.MAEPAB11.HISCAMFEC AS FECHA, HOSVITAL.MAEPAB11.HISCAMHOR AS HORA, HOSVITAL.MAEPAB11.MPCEDU AS IDENTIFICACION, HOSVITAL.MAEPAB11.MPTDOC AS TIPO_IDEN, HOSVITAL.CAPBAS.MPNOMC AS NOMBRE, HOSVITAL.CAPBAS.MPSEXO AS SEXO, HOSVITAL.CAPBAS.MPFCHN  AS FECHA_NAC, HOSVITAL.MAEPAB11.HISCNSING AS CONSEC_INGRE, HOSVITAL.INGRESOS.INGSALDX AS DIAGNOSTICO_SALIDA 
FROM (HOSVITAL.MAEPAB11
 INNER JOIN HOSVITAL.MAEPAB ON HOSVITAL.MAEPAB11.MPCODP = HOSVITAL.MAEPAB.MPCODP) 
INNER JOIN HOSVITAL.CAPBAS ON (HOSVITAL.MAEPAB11.MPTDOC = HOSVITAL.CAPBAS.MPTDOC) AND (HOSVITAL.MAEPAB11.MPCEDU = HOSVITAL.CAPBAS.MPCEDU)
 INNER JOIN HOSVITAL.INGRESOS ON(HOSVITAL.MAEPAB11.MPCEDU=HOSVITAL.INGRESOS.MPCEDU) AND (HOSVITAL.MAEPAB11.MPTDOC=HOSVITAL.INGRESOS.MPTDOC) 
WHERE (((HOSVITAL.MAEPAB11.HISCAMFEC)>='2021-01-01' And (HOSVITAL.MAEPAB11.HISCAMFEC)<='2021-01-31'));

-- Report

SELECT MAEPAB.MPCODP AS COD_PABELLON,MAEPAB.MPNOMP,I.MPNUMC,I.MPTDOC,I.MPCEDU AS TIPO_IDEN, C.MPNOMC AS NOMBRE, C.MPSEXO AS GENERO,C.MPFCHN AS FECHA_NAC,I.INGCSC AS CONSEC_INGRE,I.INGSALDX AS DIAGNOSTICO_SALIDA,M.MENOMB, I.INGFECADM AS FECHA_INGRESO, C.MDCODD COD_DEPARTAMENTO,MAEDMB.MDNOMD DEPARTAMENTO, C.MDCODM COD_LOCALIDAD,MAEDMB1.MDNOMM LOCALIDAD, C.MDCODB COD_BARRIO, MAEDMB2.MDNOMB BARRIO
 FROM HOSVITAL.INGRESOS I 
INNER JOIN HOSVITAL.MAEPAB MAEPAB ON (MAEPAB.MPCODP=I.MPCODP) 
INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC=I.MPTDOC AND C.MPCEDU=I.MPCEDU)
INNER JOIN HOSVITAL.MAEEMP M ON (M.MENNIT=I.INGNIT)
INNER JOIN HOSVITAL.MAEDMB MAEDMB ON (MAEDMB.MDCODD=C.MDCODD) 
INNER JOIN HOSVITAL.MAEDMB1 MAEDMB1 ON (MAEDMB1.MDCODM =C.MDCODM AND MAEDMB1.MDCODD=C.MDCODD)
INNER JOIN HOSVITAL.MAEDMB2 MAEDMB2 ON (MAEDMB2.MDCODM=C.MDCODM AND MAEDMB2.MDCODD=C.MDCODD AND MAEDMB2.MDCODB =C.MDCODB)
 WHERE I.INGFECADM>='2021-01-01 00:00:00' AND I.INGFECADM<='2021-01-31 23:59:59'
ORDER BY I.MPCEDU