
select * FROM HOSVITAL.MOVBAN WHERE DOCCOD='RNA' AND MVBFCH >= '2020-06-01 00:00:00';  -- 7885

SELECT * FROM HOSVITAL.MOVBAN WHERE DOCCOD='RNA'  AND MVBNROCMP=6823;

SELECT * FROM HOSVITAL.MOVBAN1 WHERE DOCCOD='RNA'  AND MVBNROCMP=6823;


SELECT * FROM HOSVITAL.DOCUCON where docdsc like ('%RECI%');
SELECT * FROM HOSVITAL.DOCUCON WHERE DOCCOD='DRC'; -- DETALLE RECIBOS CAJA CARTERA                                	

SELECT * FROM HOSVITAL.MOVCXC  WHERE MCCCNC LIKE ('%RNA%7885%');
SELECT * FROM HOSVITAL.MOVCONT2 WHERE MVCANIO=2020 AND MVCMES= 6 AND DOCCOD='DRC' AND MVCNRO= 24113 ; -- MVCDET LIKE ('%RNA%7885%');
-- DRC 24113
-- RNA 7386
-- FAC 612425         	
-- FAC 612565         	



-- Query para saber que documento DRC tiejne un RNA


SELECT M2.DOCCOD,M2.MVBNROCMP, M.MVBFCH AS FECHA_RC,M2.MVB2CD,M2.MVB2CN, CXC.MCCFCH AS FEC_DETALLE,M1.MVB1TRC AS TERCERO, TER.TRCRAZSOC AS NOMBRE,M1.MVB1VL1 AS VALOR_RECIBO  ,CXC.MCCNUMOBL AS FACTURA,CXC.MCCVLR AS VALOR_FACTURA,
 CASE WHEN M.MVBDET='S' THEN 'Detallado'  WHEN M.MVBDET='N' THEN 'No Detallado' END AS ESTADO_DETALLE    , CASE WHEN M.MVBACT='S' THEN 'Registrado'  WHEN M.MVBACT='N' THEN 'No Registrado' END AS ESTADO
FROM  HOSVITAL.MOVBAN M
LEFT  JOIN HOSVITAL.MOVBAN1 M1 ON (M1.DOCCOD=M.DOCCOD AND M1.MVBNROCMP = M.MVBNROCMP)
LEFT  JOIN HOSVITAL.MOVBAN2 M2 ON (M2.DOCCOD=M1.DOCCOD AND M2.MVBNROCMP = M1.MVBNROCMP)
LEFT  JOIN HOSVITAL.MOVCXC CXC ON (CXC.DOCCOD=M2.MVB2CD AND CXC.MVCXCNRO=M2.MVB2CN)
LEFT JOIN HOSVITAL.TERCEROS TER ON (TER.TRCCOD=M1.MVB1TRC )
WHERE M2.DOCCOD='RNA' AND M.MVBFCH>= '2020-06-01 00:00:00'  and cxc.mccnumobl = '537400'-- AND M.MVBNROCMP=7882
ORDER  BY M2.MVBNROCMP ;

SELECT * FROM HOSVITAL.MOVBAN WHERE DOCCOD='RNA'  AND MVBNROCMP=5999;

SELECT * FROM HOSVITAL.MOVBAN1 WHERE DOCCOD='RNA'  AND MVBNROCMP=5999;

SELECT * FROM HOSVITAL.MOVBAN2 WHERE DOCCOD='RNA'  AND MVBNROCMP=5999;
SELECT * FROM HOSVITAL.MOVCXC WHERE MCCNUMOBL = '537400';

SELECT * FROM HOSVITAL.MOVCONT2 WHERE  DOCCOD='DRC' AND MVCNRO= 22461 ; -- AND MVCDOCRF1='537400' ;

-- Query para saber que documentos RNA y DRC tiene asociada una factura


SELECT M.DOCCOD,M.MVBNROCMP, M.MVBFCH AS FECHA_RC,  CXC.DOCCOD  ,CXC.MVCXCNRO, CXC.MCCFCH AS FEC_DETALLE,CXC.CLICOD AS TERCERO, TER.TRCRAZSOC AS NOMBRE,M1.MVB1VL1 AS VALOR_RECIBO  ,CXC.MCCNUMOBL AS FACTURA,CXC.MCCVLR AS VALOR_FACTURA, CASE WHEN M.MVBDET='S' THEN 'Detallado'  WHEN M.MVBDET='N' THEN 'No Detallado' END AS ESTADO_DETALLE    , CASE WHEN M.MVBACT='S' THEN 'Registrado'  WHEN M.MVBACT='N' THEN 'No Registrado' END AS ESTADO
FROM  HOSVITAL.MOVBAN2 M2
LEFT  JOIN HOSVITAL.MOVBAN1 M1 ON (M2.DOCCOD=M1.DOCCOD AND M2.MVBNROCMP=M1.MVBNROCMP)
LEFT   JOIN HOSVITAL.MOVBAN M ON (M2.DOCCOD=M.DOCCOD AND M2.MVBNROCMP=M.MVBNROCMP)
RIGHT  JOIN HOSVITAL.MOVCXC CXC ON (M2.MVB2CD=CXC.DOCCOD  AND M2.MVB2CN=CXC.MVCXCNRO      )
LEFT JOIN HOSVITAL.TERCEROS TER ON (CXC.CLICOD = TER.TRCCOD )
WHERE  cxc.doccod='DRC' AND cxc.mccnumobl = '580377' 
ORDER  BY M2.MVBNROCMP ;

-- Ojo verificar esta final
-- TRABAJAR ELDIA LUNES 6-JULIO

SELECT M2.DOCCOD,M2.MVBNROCMP, M.MVBFCH AS FECHA_RC,CXC.DOCCOD  ,CXC.MVCXCNRO, CXC.MCCFCH AS FEC_DETALLE,CXC.CLICOD AS TERCERO, TER.TRCRAZSOC AS NOMBRE,M1.MVB1VL1 AS VALOR_RECIBO  ,CXC.MCCNUMOBL AS FACTURA,CXC.MCCVLR AS VALOR_FACTURA,
 CASE WHEN M.MVBDET='S' THEN 'Detallado'  WHEN M.MVBDET='N' THEN 'No Detallado' END AS ESTADO_DETALLE    , CASE WHEN M.MVBACT='S' THEN 'Registrado'  WHEN M.MVBACT='N' THEN 'No Registrado' END AS ESTADO
FROM  HOSVITAL.MOVBAN M
LEFT  JOIN HOSVITAL.MOVBAN1 M1 ON (M1.DOCCOD=M.DOCCOD AND M1.MVBNROCMP = M.MVBNROCMP)
LEFT  JOIN HOSVITAL.MOVBAN2 M2 ON (M2.DOCCOD=M1.DOCCOD AND M2.MVBNROCMP = M1.MVBNROCMP)
RIGHT  JOIN HOSVITAL.MOVCXC CXC ON (M2.MVB2CD = CXC.DOCCOD  AND M2.MVB2CN = CXC.MVCXCNRO)
LEFT JOIN HOSVITAL.TERCEROS TER ON (CXC.CLICOD = TER.TRCCOD )
WHERE  M.MVBFCH>= '2017-06-01 00:00:00'  and cxc.doccod='DRC'   and cxc.mccnumobl = '537400'  -- AND M.MVBNROCMP=7882
 -- WHERE  cxc.doccod='DRC'  AND cxc.mccnumobl = '537400'  -- AND M.MVBFCH >= '2001-06-01 00:00:00'
ORDER  BY M2.MVBNROCMP ;