select * from hosvital.hojoblprv where hopnoobl ='07100008300';

select * from hosvital.hojoblprv where hopnoobl ='1260083328';

insert into hosvital.hojoblprv
(EMPCOD,PRVCOD,HOPNOOBL,MCDPTO,CNTVIG,CNTCOD,CNUCOD,CNUSUB,CNCCOD,CNTSUB,HOPFCHOBL,HOPFCHRAD,HOPTPPZ,HOPVLRCUO,HOPCUOINI,HOPVLROBL,HOPVLRMEX,HOPTOTCRE,HOPTOTDEB,
HOPMVTER,HOJFCHCAN,HOPESTAFPT,HOJNROOC,HOJBASDES,HOJDOCOC,HOPSEDCAU,HOPDOCCAU,HOPNROCAU,HOPHOM,HOJSEDOC,HOPCODCON,HOPCODCOR)


select EMPCOD,PRVCOD,'260083328',MCDPTO,CNTVIG,CNTCOD,CNUCOD,CNUSUB,CNCCOD,CNTSUB,'2019-11-27 00:00:00','2019-11-27 00:00:00',HOPTPPZ,HOPVLRCUO,HOPCUOINI,HOPVLROBL,HOPVLRMEX,HOPTOTCRE,HOPTOTDEB,
HOPMVTER,HOJFCHCAN,HOPESTAFPT,HOJNROOC,HOJBASDES,HOJDOCOC,HOPSEDCAU,HOPDOCCAU,HOPNROCAU,HOPHOM,HOJSEDOC,HOPCODCON,HOPCODCOR
from hosvital.hojoblprv where hopnoobl ='1260083328';

--

select * from hosvital.movcxp where doccod='ACP'AND MVCXPNRO= 2007;


INSERT INTO HOSVITAL.MOVCXP
(EMPCOD,DOCCOD,MCDPTO,MVCXPNRO,MVCXPCSC,CNTVIG,MVCXPFCH,MVCXPMB,MVCXPTC , '260083328' , CNTCOD,PRVCOD,MVCXPNAT,MVCXPVAL,MVCXPVEX,CNUCOD,CNUSUB,
CNCCOD,CNTSUB,MVCXPCNC,MVCXPACT,MVCXPTER,FLJCAJCOD,FLJCAJCON)

SELECT EMPCOD,'NBN',MCDPTO,3370,MVCXPCSC,CNTVIG,'2019-11-27 00:00:00',MVCXPMB,MVCXPTC,MVCXPNUOB,CNTCOD,PRVCOD,MVCXPNAT,MVCXPVAL,MVCXPVEX,CNUCOD,CNUSUB,
CNCCOD,CNTSUB,MVCXPCNC,MVCXPACT,MVCXPTER,FLJCAJCOD,FLJCAJCON
FROM hosvital.movcxp where doccod='ACP'AND MVCXPNRO= 2007;

SELECT EMPCOD,DOCCOD,MCDPTO,MVCXPNRO,MVCXPCSC,CNTVIG,MVCXPFCH,MVCXPMB,MVCXPTC,MVCXPNUOB,CNTCOD,PRVCOD,MVCXPNAT,
MVCXPVAL,MVCXPVEX,CNUCOD,CNUSUB,CNCCOD,CNTSUB,MVCXPCNC,MVCXPACT,MVCXPTER,FLJCAJCOD,FLJCAJCON
FROM hosvital.movcxp where doccod='ACP'AND MVCXPNRO= 2007;



SELECT EMPCOD,DOCCOD,MCDPTO,MVCXPNRO,MVCXPCSC,CNTVIG,MVCXPFCH,MVCXPMB,MVCXPTC,MVCXPNUOB,CNTCOD,PRVCOD,MVCXPNAT,
MVCXPVAL,MVCXPVEX,CNUCOD,CNUSUB,CNCCOD,CNTSUB,MVCXPCNC,MVCXPACT,MVCXPTER,FLJCAJCOD,FLJCAJCON
FROM hosvital.movcxp where doccod='NBN'AND MVCXPNRO= 3370;


select * from hosvital.hojoblprv where hopnoobl ='260083328';


SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='NGR' AND MVCNRO= 32006;

update  hosvital.movcont3
set  mvcest ='N'
WHERE  EMPCOD='01' AND  doccod='NGR ' AND MVCNRO IN (  32006  )  and mvcest='N';



UPDATE HOSVITAL.MOVCONT2 
SET MVCVLRLC = 0.0 , MVCVLR= 0.0
WHERE DOCCOD='NGR' AND MVCNRO= 32006;


select * from hosvital.NIMOVCON1   where  DOCCOD = 'NGR ' AND NIMCNRO IN(  32006  ); 
select * from hosvital.NIMOVCON2   where  DOCCOD = 'NGR ' AND NIMCNRO IN(  32006  ); 

UPDATE  hosvital.NIMOVCON1
set  NIMC1EST ='C'
where EMPCOD='01' AND doccod='NGR ' and NIMCNRO  in  (  32006  ) and NIMC1EST='S';

UPDATE  hosvital.NIMOVCON2
set  
where EMPCOD='01' AND doccod='NGR ' and NIMCNRO  in  (  32006  ) and NIMC1EST='S';



SELECT * FROM HOSVITAL.HOJOBL WHERE HOJNUMOBL = '571731';

UPDATE  HOSVITAL.HOJOBL 
SET HOJTOTCRE=0, HOJTOTDEB =395753
WHERE HOJNUMOBL = '571731' AND CNTCOD= '13032001';

SELECT* FROM HOSVITAL.MOVCXC WHERE MCCNUMOBL= '571731';
 
UPDATE  HOSVITAL.MOVCXC 
SET  MCCVLR= 0.00
WHERE MCCNUMOBL= '571731' AND DOCCOD = 'NGR' AND MVCXCNRO= 32006;

---

--------
--------

insert into  hosvital.nimovcon1
select empcod,doccod,mvcnro,mcdpto,mvccpt,agccdg,tranapl,mvcfch,'PES',mvctascmb,mvcest,mvcusucre,mvcusuact,mvcfchact,mvcultcsc,mvcmpajs,mvfchsys,' ',mvcfchanu,' ',' ',0,' ',mvcfchemi,mvcfchaut,' ',' ','S','S',' ',' ',0,'  ',' ', ' ',' '
from hosvital.movcont3 
where doccod='LAN' and mvcnro=1722;

insert into  hosvital.nimovcon2
select EMPCOD,DOCCOD,MVCNRO,MCDPTO,MVCCSC,CNTVIG,CNTCOD,CNUCOD,CNUSUB,CNCCOD,CNTSUB,TRCCOD,MVCDOCRF1,MVCDOCRF2,
MVCDOCRF3,MVCNAT,MVCVLRLC,MVCVLREX,MVCDET,MVCBSE,MVCVLR,MVCIMPCOD,MVCCFCH   ,MVCANIO,        MVCMES,          MVCSEDORG,MVCCMPAJ,
MVCDOCRF4,' ', MOVCNTPRF
from  hosvital.movcont2 
where doccod='LAN' and mvcnro in  (1722) ;--  AND MVCCSC= 74 ;  --   and mvccsc IN (72) ;

SELECT * FROM HOSVITAL.NIMOVCON1 where doccod='LAN' and NIMCNRO=1722; ;

UPDATE HOSVITAL.NIMOVCON1 
SET  NIMC1MA='N', NIMC1MG='N'
where doccod='LAN' and NIMCNRO=1722; 




