 select * from HOSVINEW.maepab where mpcodp IN ('43','24','12'); 
select * from HOSVINEW.maepab1 where mpnumc IN ('UI218','UI217');
 SELECT * FROM HOSVINEW.MAEPAB11 where mpnumc IN ('UI218','UI217') AND HISCAMFEC BETWEEN '2020-06-01' AND '2020-06-30' order by MPNUMC; 
SELECT * FROM HOSVINEW.HISCAM WHERE mpnumc IN ('UI218','UI217');
 delete from HOSVINEW.HISCAM where mpnumc in ('UI218') AND ESTCAM='S';
 SELECT * FROM HOSVINEW.HISCAM WHERE mpnumc IN ('309U');
 DELETE FROM HOSVINEW.HISCAM WHERE mpnumc IN ('309U') AND ESTCAM='S' AND MPCODP='12';
 SELECT * FROM HOSVINEW.HISCAM WHERE mpnumc IN ('310U');
DELETE FROM HOSVINEW.HISCAM WHERE mpnumc IN ('310U') AND ESTCAM='S' AND MPCODP='12';



-----------

SELECT * FROM HOSVItal.HISCAM WHERE mpnumc IN ('UI218','UI217'); 
 SELECT * FROM HOSVItal.HISCAM WHERE mpnumc IN ('309U');
 SELECT * FROM HOSVItal.HISCAM WHERE mpnumc IN ('310U');

 delete from HOSVITAL.HISCAM where mpnumc in ('UI218') AND ESTCAM='S';
 DELETE FROM HOSVITAL.HISCAM WHERE mpnumc IN ('309U') AND ESTCAM='S' AND MPCODP='12';
DELETE FROM HOSVITAL.HISCAM WHERE mpnumc IN ('310U') AND ESTCAM='S' AND MPCODP='12';
