SELECT * FROM HOSVITAL.PRVPROD WHERE MSRESO= '0040MQ03' ;
SELECT * FROM HOSVITAL.PRVPROD;

CREATE TABLE HOSVITAL.PRVPROD_20200304 AS (SELECT * FROM HOSVITAL.PRVPROD) WITH DATA;
SELECT COUNT(*) FROM HOSVITAL.PRVPROD_20200304;


UPDATE HOSVITAL.PRVPROD
SET  PRVPRC=PRVULPRCE;

UPDATE  HOSVITAL.PRVPROD B
SET B.PRVPRC = (SELECT A.PRVPRC FROM HOSVITAL.PRVPROD_20200304 A WHERE A.EMPCOD= B.EMPCOD AND A.PRVCOD=B.PRVCOD AND A.MSRESO =B.MSRESO);


