select * from hosvital.movcont2 where doccod='CA' AND MVCNRO = 8381;

SELECT * FROM HOSVITAL.MOVCXP WHERE MVCXPNUOB ='40196' ;

SELECT * FROM HOSVITAL.HOJOBLPRV WHERE HOPNOOBL= '40196';

UPDATE  HOSVITAL.HOJOBLPRV 
SET HOJFCHCAN='0001-01-01'
WHERE EMPCOD='01' AND HOPNOOBL= '40196';


SELECT * FROM HOSVITAL.HOJOBLPRV WHERE HOPNOOBL= 'EU-5';
SELECT * FROM HOSVITAL.HOJOBLPRV WHERE PRVCOD='900704639';

SELECT * FROM HOSVITAL.MOVCXP WHERE MVCXPNUOB ='EU-5';
delete  FROM HOSVITAL.MOVCXP WHERE MVCXPNUOB ='EU-5'  and cntvig = 2021;




insert into hosvital.hojoblprv
(EMPCOD,PRVCOD,HOPNOOBL,MCDPTO,CNTVIG,CNTCOD,CNUCOD,CNUSUB,CNCCOD,CNTSUB,HOPFCHOBL,HOPFCHRAD,HOPTPPZ,HOPVLRCUO,HOPCUOINI,HOPVLROBL,HOPVLRMEX,HOPTOTCRE,
HOPTOTDEB,HOPMVTER,HOJFCHCAN,HOPESTAFPT,HOJNROOC,HOJBASDES,HOJDOCOC,HOPSEDCAU,HOPDOCCAU,HOPNROCAU,HOPHOM,HOJSEDOC,HOPCODCON,HOPCODCOR)
select
EMPCOD,PRVCOD,HOPNOOBL,MCDPTO,2021,CNTCOD,CNUCOD,CNUSUB,CNCCOD,CNTSUB,HOPFCHOBL,HOPFCHRAD,HOPTPPZ,HOPVLRCUO,HOPCUOINI,HOPVLROBL,HOPVLRMEX,HOPTOTCRE,
HOPTOTDEB,HOPMVTER,HOJFCHCAN,HOPESTAFPT,HOJNROOC,HOJBASDES,HOJDOCOC,HOPSEDCAU,HOPDOCCAU,HOPNROCAU,HOPHOM,HOJSEDOC,HOPCODCON,HOPCODCOR
FROM HOSVITAL.HOJOBLPRV WHERE HOPNOOBL= 'EU-5';