SELECT  * FROM HOSVITAL.HOJOBLPRV  WHERE  PRVCOD='860007373' AND CNTVIG = 2019  AND HOPNOOBL LIKE ('%RETE%') ORDER BY HOPFCHOBL;
SELECT  * FROM HOSVITAL.MOVCXP   WHERE  PRVCOD='860007373' AND CNTVIG = 2018  AND MVCXPNUOB LIKE ('%RETE%') ;
SELECT  * FROM HOSVITAL.MOVCXP   WHERE   CNTVIG = 2018  AND MVCXPNUOB LIKE ('%RETE%') ;


SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='CI' AND MVCNRO=8;