select * from hosvital.movcxp where doccod='CA' AND MVCXPNRO=11851;
SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='CA' AND MVCNRO=11851;

SELECT * FROM HOSVITAL.HOJOBLPRV WHERE HOPNOOBL='3138';

SELECT * FROM HOSVITAL.HOJOBLPRV WHERE PRVCOD='52094553' and cntvig=2020 order by HOPNOOBL;
SELECT * FROM HOSVITAL.HOJOBLPRV WHERE PRVCOD='52094553' and cntvig=2020  and hopnoobl='3137';

INSERT INTO HOSVITAL.HOJOBLPRV (EMPCOD,PRVCOD,HOPNOOBL,MCDPTO,CNTVIG,CNTCOD,CNUCOD,CNUSUB,CNCCOD,CNTSUB,HOPFCHOBL,HOPFCHRAD,HOPTPPZ,HOPVLRCUO,HOPCUOINI,HOPVLROBL,HOPVLRMEX,HOPTOTCRE,
HOPTOTDEB,HOPMVTER,HOJFCHCAN,HOPESTAFPT,HOJNROOC,HOJBASDES,HOJDOCOC,HOPSEDCAU,HOPDOCCAU,HOPNROCAU,HOPHOM,HOJSEDOC,HOPCODCON,HOPCODCOR)
SELECT EMPCOD,PRVCOD,MVCXPNUOB,MCDPTO,2020,CNTCOD,CNUCOD,CNUSUB,CNCCOD,CNTSUB,MVCXPFCH,MVCXPFCH,1,MVCXPVAL,0.00,MVCXPVAL,0.00,MVCXPVAL,0,'N','2020-04-24','N',0,0,'','002','CI',0,'N','','',''
 FROM HOSVITAL.MOVCXP 
WHERE DOCCOD='CA' AND MVCXPNRO=11851 AND MVCXPCSC=4;