SELECT HOSVITAL.INGRESOS.MPCEDU AS ID, HOSVITAL.MAEPAB.MPNOMP AS PABELLON, HOSVITAL.CAPBAS.MPNOMC AS NOMBRE_PACIENTE, HOSVITAL.INGRESOS.INGCSC AS CONSE_ING, HOSVITAL.INGRESOS.INGFECADM AS FECHA_ADM, HOSVITAL.INGRESOS.INGFECEGR AS FECHA_EGRESO, HOSVITAL.INGRESOS.CLAPRO AS TIPO_ATENCION, MONTH(HOSVITAL.INGRESOS.INGFECEGR) AS MES_EGRESO , HOSVITAL.MAEEMP.MENOMB , DAY(  HOSVITAL.INGRESOS.INGFECEGR - HOSVITAL.INGRESOS.INGFECADM ) AS DIFERENCIA 
 FROM HOSVITAL.INGRESOS
 INNER JOIN HOSVITAL.CAPBAS ON (HOSVITAL.INGRESOS.MPCEDU=HOSVITAL.CAPBAS.MPCEDU)
 INNER JOIN HOSVITAL.MAEPAB ON(HOSVITAL.INGRESOS.MPCODP=HOSVITAL.MAEPAB.MPCODP)
 INNER JOIN HOSVITAL.MAEEMP ON HOSVITAL.INGRESOS.INGNIT = HOSVITAL.MAEEMP.MENNIT 
WHERE DATE(HOSVITAL.INGRESOS.INGFECEGR) >= '2019-08-31'  AND DATE(HOSVITAL.INGRESOS.INGFECEGR) <= '2019-09-01' AND  HOSVITAL.INGRESOS.MPCEDU ='1106779677';

SELECT * FROM HOSVITAL.CAPBAS WHERE MPCEDU='1106779677';


SELECT * FROM HOSVITAL.INGRESOS WHERE MPCEDU='1106779677';

-- Sdo reporte 

SELECT m.mpnfac as factura, i.MPCEDU AS ID, maepab.MPNOMP AS PABELLON, cap.MPNOMC AS NOMBRE_PACIENTE, i.INGCSC AS CONSE_ING, i.INGFECADM AS FECHA_ADM, i.INGFECEGR AS FECHA_EGRESO, i.CLAPRO AS TIPO_ATENCION, MONTH(i.INGFECEGR) AS MES_EGRESO , emp.MENOMB , DAY(  i.INGFECEGR - i.INGFECADM ) AS DIFERENCIA 
FROM HOSVITAL.INGRESOS i
INNER JOIN HOSVITAL.CAPBAS cap ON (cap.MPCEDU=i.MPCEDU)
INNER JOIN HOSVITAL.MAEPAB maepab ON(maepab.MPCODP=i.MPCODP)
INNER JOIN HOSVITAL.MAEEMP emp ON (emp.mennit = i.INGNIT)
INNER JOIN HOSVITAL.MAEATE m on (m.mptdoc=i.mptdoc and m.mpcedu=i.mpcedu and m.mactving=i.ingcsc and m.maestf not in ('1','10'))
WHERE DATE(i.INGFECEGR) >= '2019-10-06'  AND DATE(i.INGFECEGR) <= '2019-10-07' AND  i.inginslc<> 'S' ;


select mactving,facfch from hosvital.maeate where mpcedu='20040914';
select ingcsc,inginslc from hosvital.ingresos where mpcedu='20040914';