SELECT K.BODEGA,B.BODDESC BODEGA_SALIDA,K.MSRESO COD_PRODUCTO,M.MSNOMG AS PRODUCTO,K. DOCTIP,D.DOCDSC DOCUMENTO, K.DOCNRO NUMERO_DOC,K.MOVFCH FECHA,K.MOVCNT CANTIDAD,k.movvlt,K.MOVBOD,B1.BODDESC BODEGA_DESTINO 
FROM HOSVITAL.KARDEX1 K
 INNER JOIN HOSVITAL.DOCUCON D ON (D.DOCCOD=K.DOCTIP) 
INNER JOIN HOSVITAL.BODEGAS B ON (B.BODEGA=K.BODEGA) 
INNER JOIN HOSVITAL.BODEGAS B1 ON (B1.BODEGA= K.MOVBOD)
 INNER JOIN HOSVITAL.MAESUM1 M ON (M.MSRESO=K.MSRESO) 
WHERE K.MOVFCH>='2020-08-01 00:00:00' AND K.MOVFCH<='2020-08-31 23:59:59' AND K.DOCTIP ='ASA' AND K.DOCNRO=12324319 -- AND K.BODEGA='00' AND MOVBOD='01' --  AND K.MOVES='S'
 ORDER BY K.MOVFCH,K. DOCTIP, K.DOCNRO;

select count(* ) from hosvital.kardex1 WHERE MOVFCH>='2020-01-01 00:00:00' AND MOVFCH<='2020-07-31 23:59:59' ;  --949981	


-- Con lotes

SELECT K.BODEGA,B.BODDESC BODEGA_SALIDA,K.MSRESO COD_PRODUCTO,M.MSNOMG AS PRODUCTO,K. DOCTIP,D.DOCDSC DOCUMENTO, K.DOCNRO NUMERO_DOC,K.MOVFCH FECHA,M1.MVTOLOT, M1.MVTOVCTO,K.MOVCNT CANTIDAD,k.movvlt,K.MOVBOD,B1.BODDESC BODEGA_DESTINO 
FROM HOSVITAL.KARDEX1 K
 INNER JOIN HOSVITAL.DOCUCON D ON (D.DOCCOD=K.DOCTIP) 
INNER JOIN HOSVITAL.BODEGAS B ON (B.BODEGA=K.BODEGA) 
INNER JOIN HOSVITAL.BODEGAS B1 ON (B1.BODEGA= K.MOVBOD)
 INNER JOIN HOSVITAL.MAESUM1 M ON (M.MSRESO=K.MSRESO) 
inner  JOIN HOSVITAL.MOVINV4 M4 ON (M4.DOCCOD=K.DOCTIP AND M4.DOCNRO=K.DOCNRO AND M4.MSRESO=M.MSRESO)
left  JOIN HOSVITAL.MOVINV1 M1 ON (M1.DOCCOD=K.DOCTIP AND M1.DOCNRO=K.DOCNRO and m1.mvtocsc = m4.mvtocsc)
WHERE K.MOVFCH>='2020-01-01 00:00:00' AND K.MOVFCH<='2020-07-31 23:59:59' 
 ORDER BY K.MOVFCH,K. DOCTIP, K.DOCNRO;

-- 12324319
select * from hosvital.movinv4 WHERE DOCCOD='ASA' AND DOCNRO = 12325957		;
select * from hosvital.movinv3 WHERE DOCCOD='ASA' AND DOCNRO = 12325957		;
select * from hosvital.movinv2 WHERE DOCCOD='ASA' AND DOCNRO = 12325957		;
select * from hosvital.movinv1 WHERE DOCCOD='ASA' AND DOCNRO = 12135179	 order by docnro,mvtocsc	;
select * from hosvital.movinv1;

select * from hosvital.lotesum;
select * from hosvital.lotesum1 where lotecod in('FGFA044212','005-20');

select * from hosvital.lotesum where lotecod in('FGFA044212','005-20');