SELECT  ACFCOD,ActFijEst FROM HOSVITAL.ACTFIJ WHERE ACFCOD in ('TERRE002','M001349','EDIF003');

SELECT * FROM HOSVITAL.ACTFIJ WHERE ACFCOD in ('TERRE002','M001349','EDIF003');

UPDATE  HOSVITAL.ACTFIJ 
SET ACFPLA='TERRE002', ACFEST=1
WHERE ACFCOD='TERRE002';

select * from hosvital.ActFijCla;

SELECT  ACFCOD,ActFijEst FROM HOSVITAL.ACTFIJ;