SELECT MPNFAC,MAESTF,FACFCH FROM MAEATE WHERE MPNFAC = 1944109 

BEGIN TRANSACTION;
UPDATE MAEATE
SET MAESTF=0
 WHERE MPNFAC = 1944109 

 SELECT MPNFAC,MAESTF,FACFCH FROM MAEATE WHERE MPNFAC = 1944109 
 -- COMMIT;
 -- ROLLBACK