
SELECT * FROM MOVCONT2 WHERE DOCCOD='CFA' AND MVCNRO = 31691

SELECT MVCNAT, SUM(MVCVLR)
FROM MOVCONT2
WHERE DOCCOD='CFA' AND MVCNRO = 31691
GROUP BY MVCNAT


SELECT * FROM  MOVCONT2 WHERE MvCAnio=0 AND MvCMes=0  -- 89
SELECT * FROM  MOVCONT2 WHERE MvCAnio=0 AND MvCMes=0  AND CntVig=2016-- 89/ 88

BEGIN TRANSACTION;
UPDATE MOVCONT2
SET MvCAnio =2016, MvCMes=12, MvCCmpAj='N'
WHERE MvCAnio=0 AND MvCMes=0 AND MvCCFch>= '2016-12-01'
-- COMMIT;
-- ROLLBACK