SELECT  * FROM MOVCXP WHERE DOCCOD='CXP' AND MvCxPNro =14667;  -- 050-528124     
SELECT * FROM HOJOBLPRV WHERE PrvCod='860005114' AND HOPNoObl= '050-528124' ORDER BY HOPFCHOBL  -- 050-528124     $$581070
-- DUPLICO EN LA MOVCXP 
-- LOS REGISTROS



SELECT  * FROM MOVCONT2 WHERE DOCCOD='CXP' AND MVCNRO =14667;
SELECT  * FROM MOVCONT3 WHERE DOCCOD='CXP' AND MVCNRO =14667;



SELECT  * FROM MOVCONT2 WHERE DOCCOD='CEC' AND MVCNRO =46668
SELECT  * FROM MOVCONT3 WHERE DOCCOD='CEC' AND MVCNRO =46668;
SELECT  * FROM MOVCXP WHERE DOCCOD='CEC' AND MvCxPNro =46668; 




SELECT  * FROM MOVCONT2 WHERE DOCCOD='CFA' AND MVCNRO =31518
SELECT  * FROM MOVCONT3 WHERE DOCCOD='CFA' AND MVCNRO =31518;
SELECT  * FROM MOVCXP WHERE DOCCOD='CFA' AND MvCxPNro =31518; 

-- QUEDA DOBLE LA OBLIGACION EN LA MOVCXP

SELECT * FROM HOJOBLPRV WHERE PrvCod='800149695' AND HOPNoObl= '-CV1-861946' ORDER BY HOPFCHOBL

----------



SELECT  * FROM MOVCONT2 WHERE DOCCOD='CFA' AND MVCNRO =31517
SELECT  * FROM MOVCONT3 WHERE DOCCOD='CFA' AND MVCNRO =31517;
SELECT  * FROM MOVCXP WHERE DOCCOD='CFA' AND MvCxPNro =31517; 
SELECT  * FROM MOVCXP WHERE  MvCxPNuOb =  '-CV1-861946'

-- QUEDA DOBLE LA OBLIGACION EN LA MOVCXP

SELECT * FROM HOJOBLPRV WHERE PrvCod='800149695' AND  HOPNoObl= '-CV1-861946' ORDER BY HOPFCHOBL



-- segunda parte de pruebas

SELECT  * FROM MOVCONT2 WHERE DOCCOD='CFA' AND MVCNRO =31370
SELECT  * FROM MOVCONT3 WHERE DOCCOD='CFA' AND MVCNRO =31370;
SELECT  * FROM MOVCXP WHERE DOCCOD='CFA' AND MvCxPNro =31370; 
SELECT  * FROM MOVCXP WHERE  MvCxPNuOb =  'FV-37250' -- Esta una sola vez

-- QUEDA DOBLE LA OBLIGACION EN LA MOVCXP

SELECT * FROM HOJOBLPRV WHERE PrvCod='830123305' AND  HOPNoObl= 'FV-37250' ORDER BY HOPFCHOBL -- 2320500.00	0.00	2320500.00	0.00


-- otro aso

SELECT  * FROM MOVCONT2 WHERE DOCCOD='CXP' AND MVCNRO =14642
SELECT  * FROM MOVCONT3 WHERE DOCCOD='CXP' AND MVCNRO =14642;
SELECT  * FROM MOVCXP WHERE DOCCOD='CXP' AND MvCxPNro =14642; 
SELECT  * FROM MOVCXP WHERE  MvCxPNuOb =  '67-179793' -- Esta DUPLICADO EL VALOR
--AL INGRESAR POR CXP BOTON MODIFICAR

-- QUEDA DOBLE LA OBLIGACION EN LA MOVCXP

SELECT * FROM HOJOBLPRV WHERE PrvCod='805011262' AND  HOPNoObl= '67-179793' ORDER BY HOPFCHOBL -- EL TOTAL ESTA CORRECTO


-- otro aso

SELECT  * FROM MOVCONT2 WHERE DOCCOD='CXP' AND MVCNRO =14543
SELECT  * FROM MOVCONT3 WHERE DOCCOD='CXP' AND MVCNRO =14543;
SELECT  * FROM MOVCXP WHERE DOCCOD='CXP' AND MvCxPNro =14543; 
SELECT  * FROM MOVCXP WHERE  MvCxPNuOb =  'GRLA 771' -- Esta DUPLICADO EL VALOR
--AL INGRESAR POR CXP BOTON MODIFICAR

-- QUEDA DOBLE LA OBLIGACION EN LA MOVCXP

SELECT * FROM HOJOBLPRV WHERE PrvCod='19423748' AND  HOPNoObl= 'GRLA 771' ORDER BY HOPFCHOBL -- EL TOTAL ESTA CORRECTO 739018.00

-- OTRO ASSO CFA



-- Los consecutivos




SELECT  * FROM MOVCONT2 WHERE DOCCOD='CFA' AND MVCNRO =31491
SELECT  * FROM MOVCONT3 WHERE DOCCOD='CFA' AND MVCNRO =31491;
SELECT  * FROM MOVCXP WHERE DOCCOD='CFA' AND MvCxPNro =31491; 
SELECT  * FROM MOVCXP WHERE  MvCxPNuOb =  'AC-10998' -- Esta DUPLICADO EL VALOR
--AL INGRESAR POR CXP BOTON MODIFICAR

-- QUEDA DOBLE LA OBLIGACION EN LA MOVCXP

SELECT * FROM HOJOBLPRV WHERE PrvCod='830068653'  AND  HOPNoObl= 'AC-10998' 
ORDER BY HOPFCHOBL -- EL TOTAL ESTA CORRECTO 739018.00

SELECT * FROM CUENTAS WHERE CNTCOD= '23352501'
SELECT * FROM CUENTAS WHERE CNTCOD= '23353001'

----------------

SELECT  * FROM MOVCONT2 WHERE DOCCOD='CFA' AND MVCNRO =31491
SELECT  * FROM MOVCONT3 WHERE DOCCOD='CFA' AND MVCNRO =31491;
SELECT  * FROM MOVCXP WHERE DOCCOD='CFA' AND MvCxPNro =31491; 
SELECT  * FROM MOVCXP WHERE  MvCxPNuOb =  'GRLA 771' -- Esta DUPLICADO EL VALOR
--AL INGRESAR POR CXP BOTON MODIFICAR

-- QUEDA DOBLE LA OBLIGACION EN LA MOVCXP

SELECT * FROM HOJOBLPRV WHERE PrvCod='830068653' AND  HOPNoObl= 'GRLA 771' ORDER BY HOPFCHOBL -- EL TOTAL ESTA CORRECTO 739018.00

SELECT * FROM CUENTAS WHERE CNTCOD= '23352501'


--------------

SELECT  * FROM MOVCONT2 WHERE DOCCOD='CFA' AND MVCNRO =31522
SELECT  * FROM MOVCONT3 WHERE DOCCOD='CFA' AND MVCNRO =31522;
SELECT  * FROM MOVCXP WHERE DOCCOD='CFA' AND MvCxPNro =31522; 
SELECT  * FROM MOVCXP WHERE  MvCxPNuOb =  'FAC26122016' -- Esta DUPLICADO EL VALOR
--AL INGRESAR POR CXP BOTON MODIFICAR

-- QUEDA DOBLE LA OBLIGACION EN LA MOVCXP

SELECT * FROM HOJOBLPRV WHERE PrvCod='900545739' AND  HOPNoObl= 'FAC26122016' ORDER BY HOPFCHOBL -- EL TOTAL ESTA CORRECTO 739018.00

SELECT * FROM CUENTAS WHERE CNTCOD= '23352501'




-- Buscar Ordenes d trabajo que no esten causadas


SELECT  B.MvCCFch,A.DOCCOD,A.MvCxPNro,A.MvCxPNro,A.MvCXPCSC,
B.MvCCsc,
MvCxPNuOb,B.MvCDocRf1 ,A.MvCxPVal,B.MVCVLR,(A.MvCxPVal-B.MVCVLR)
FROM
MOVCXP A, MOVCONT2 B
WHERE A.DOCCOD IN ('CXP','CFA') AND 
 A.EMPCOD=B.EMPCOD AND A.MCDpto=B.MCDpto AND
A.DOCCOD=B.DOCCOD AND B.MVCANIo= 2016 AND
    A.MvCxPNro=B.MvCNro AND
 B.MvCMes>=11 AND
   A.CNTCOD=B.CNTCOD AND A.PRVCOD=B.TRCCOD AND
	  B.MvCNat='C'
	  ORDER BY A.MvCxPNro  -- HAY 174/ 176

	  SELECT * FROM MOVCXP WHERE MvCxPNro= 31518
	  SELECT * FROM MOVCONT2 WHERE DOCCOD='CFA' AND MvCNRO= 31518
	  SELECT * FROM HOJOBLPRV  WHERE HOPNoObl = '919' AND PrvCod='830001458'

-- SACO UNA COPIA : TABLA REPORT.MOVCXP_MODIFICA20161226


 SELECT B.MvCCFch,A.DOCCOD,A.MvCxPNro,B.MVCNRO,A.MvCXPCSC,
B.MvCCsc,
A.MvCxPNuOb,B.MvCDocRf1 
FROM
MOVCXP A, MOVCONT2 B
WHERE  A.DOCCOD IN ('CXP','CFA') AND 
A.DOCCOD=B.DOCCOD AND B.MVCANIo= 2016 AND B.MvCMes>=11 AND
      A.EMPCOD=B.EMPCOD AND A.MCDpto=B.MCDpto AND A.MvCxPNro=B.MvCNro AND A.CNTCOD=B.CNTCOD AND A.PRVCOD=B.TRCCOD AND
	  B.MvCNat='C' AND  A.MvCXPCSC<>B.MvCCsc
	  ORDER BY A.MvCxPNro  -- HAY 144



-- Veamos la actualizacion :

BEGIN TRANSACTION;
UPDATE MOVCXP
SET  MvCXPCSC = B.MvCCsc
FROM MOVCXP A, MOVCONT2 B
WHERE  A.DOCCOD IN ('CXP','CFA') AND  A.DOCCOD=B.DOCCOD AND B.MVCANIo= 2016 AND B.MvCMes>=11 AND
      A.EMPCOD=B.EMPCOD AND A.MCDpto=B.MCDpto AND A.MvCxPNro=B.MvCNro AND A.CNTCOD=B.CNTCOD AND A.PRVCOD=B.TRCCOD AND
	  B.MvCNat='C' AND  A.MvCXPCSC<>B.MvCCsc
--COMMIT;
-- ROLLBACk;



-- CRUZAR VALORES
SELECT * FROM MOVCXP WHERE DOCCOD='CFA' AND MvCxPNro= 14667

select * from MOVCONT2 where DOCCOD='CFA' AND MvCNro = 14667 AND MvCNat='C'




BEGIN transaction;
delete from movcxp
where doccod='CFA' AND MvCxPNro=31518  AND MvCxPCsc=4
-- COMMIT


	  SELECT * FROM MOVCXP WHERE MvCxPNro= 31146
	  SELECT * FROM MOVCONT2 WHERE DOCCOD='CFA' AND MvCNRO= 31146
	    SELECT * FROM MOVCONT3 WHERE DOCCOD='CFA' AND MvCNRO= 31146
	  SELECT * FROM HOJOBLPRV  WHERE HOPNoObl = 'HBS 9884' AND PrvCod='830126596'

	  

---

SELECT DISTINCT DOCCOD FROM MOVCXP




