BEGIN TRANSACTION;
UPDATE ADGLOSAS1
SET GloedoItNt = ' '
WHERE MPNFac = 2283914 
-- COMMIT
-- ROLLBACK

SELECT GloedoItNt,* FROM ADGLOSAS1 WHERE MPNFac = 2283914 

BEGIN TRANSACTION;
UPDATE ADGLOSAS
SET GloedoItNt = ' '
WHERE MPNFac = 2283914 
-- COMMIT
-- ROLLBACK

SELECT * FROM ADGLOSAS  WHERE MPNFac = 2283914 
SELECT * FROM ADGLOSAS1 WHERE MPNFac = 2283914 

BEGIN TRANSACTION;
UPDATE ADGLOSAS1
SET GLOEDOITM = 'P' -- ESTABA EN M
WHERE MPNFac = 2283914 
-- COMMIT
-- ROLLBACK

