SELECT * FROM MOVCONT3
 WHERE MvCFch >= '2016-11-01' and MvCEst='A'
 

 SELECT * FROM MOVCONT2 WHERE DOCCOD='CFA' AND MvCNro = 31514
 SELECT * FROM MOVCONT2 WHERE MvCAnio=0 AND MvCMes=0
 SELECT * FROM MOVCONT3 WHERE DOCCOD='CFA' AND MvCNro = 31414
