SELECT * FROM ENTRALM  WHERE DOCCOD='CEC' AND EntANro IN ( 46777 , 46778)
SELECT * FROM ENTRALM1 WHERE DOCCOD='CEC' AND EntANro = 46777 

SELECT * FROM DOCUCON WHERE DOCCOD='CEC'
SELECT * FROM DOCUCON WHERE DOCCOD='ENT'

SELECT * FROM COMPCAB WHERE DOCCOD='COC' AND OrdeNro= 46777

SELECT * FROM ENTRALM  WHERE DOCCOD='ENT' AND EntANro = 46777 
SELECT * FROM COMPCAB2 WHERE DOCCOD='COC'

SELECT * FROM ENTRALM  WHERE DOCCOD='CEC' AND ORDENUM = 46777 

select * from MOVCONT3 WHERE DOCCOD='ENT' AND MVCNRO= 46777
select * from MOVCONT3 WHERE DOCCOD='CEC' AND MVCNRO= 46777

SELECT * FROM ENTRALM  WHERE DOCCOD='CEC' AND EntAFch>= '2016-12-01' ORDER BY 

-- Es una entrada por remision : 5590         / ENTREMIS

SELECT * FROM KARDEX1
WHERE MovFch >= '2016-12-01' AND TranCod= 'ENTREMIS' AND DOCTIP= 'CEC'AND DocNro = 46777 -- REQUISICION Nro 40212

SELECT * FROM REQUISICI WHERE ReqNro = 40212
SELECT * FROM REQUISI1 WHERE ReqNro = 40212

SELECT * FROM ENTRALM  WHERE DOCCOD='CEC' AND EntANro IN ( 46777 , 46778) -- Esta es una entrada por remision


SELECT * FROM TMPFAC WHERE TFCEDU = '11333381'

SELECT * FROM TMPFAC1 WHERE TFCEDU = '11333381'


SELECT * FROM TMPFAC2 WHERE TFCEDU = '11333381' AND TFReso IN (SELECT MSRESO  FROM MAESUM1 WHERE   MSMATOST='S') -- Estos son los productos :


SELECT * FROM ENTRALM1 WHERE DOCCOD='CEC' AND EntANro= 46777 AND MSRESO IN
(
SELECT TFRESO FROM TMPFAC2 WHERE TFCEDU = '11333381' AND TFReso IN (SELECT MSRESO  FROM MAESUM1 WHERE   MSMATOST='S')
) -- HAY (2) RODUCTOS  : CUT02286236    - CUT02287358    


-- veamos la requission en elkadex



SELECT * FROM KARDEX1
WHERE MovFch >= '2016-12-01' AND TranCod= 'ENTREMIS' AND MOVREQN  = 40212 -- REQUISICION Nro 40212

-- No le veo orden de compra ...
-- ESta es la entrada a almacen

SELECT * FROM ENTRALM  WHERE DOCCOD='CEC' AND EntANro IN ( 46777 , 46778)

-- Esta es la remison

SELECT * FROM KARDEX1
WHERE MovFch >= '2016-12-01' AND TranCod= 'ENTREMIS' AND DOCTIP='CEC' AND  DocNro= 46777

SELECT * FROM KARDEX1
WHERE MovFch >= '2016-12-01' AND MovCodPac= '11333381' AND MSRESO = 'CUT02286236'



-- Este es el inventaruo (Movinv4)

SELECT * FROM MOVINV4
WHERE DOCCOD='CEC' AND DocNro= 46777

SELECT * FROM MOVINV3
WHERE DOCCOD='CEC' AND DocNro= 46777

-- Esta es la requisicion

SELECT * FROM REQUISICI WHERE ReqNro = 40212
SELECT * FROM REQUISI1 WHERE ReqNro = 40212


-- Veamos un caso posterior :

SELECT * FROM KARDEX1
WHERE MovFch >= '2016-01-01' AND TranCod= 'ENTREMIS' AND DOCTIP='CEC' 

-- Veamos esta : CEC	47055 / REQ- PACIENTE -- 40410	41353237       

SELECT * FROM ENTRALM  WHERE DOCCOD='CEC' AND EntANro IN ( 41826)

SELECT * FROM ENTRALM WHERE  DOCCOD='CEC' AND EntAFch >= '2016-01-01' AND OrdeNum<>0 AND
            EntANro IN (SELECT DOCNRO FROM KARDEX1 WHERE DOCTIP='CEC'  AND TranCod= 'ENTREMIS')

			SELECT * FROM ENTRALM WHERE  DOCCOD='CEC' AND EntAFch >= '2016-01-01' AND OrdeNum =0 AND TranCod='ENTREMIS' AND
            EntANro IN (SELECT DOCNRO FROM KARDEX1 WHERE DOCTIP='CEC'  AND TranCod= 'ENTREMIS')  -- 1190


			select * from docucon where docdsc like ('%REM%')
			select * from TRANINV where TranCod  like ('%REM%')

			-- Transaciones :

SALREMIS
ENTREMIS
AISREM  
REVENTRM
AISREM  
REVENTRM
AISREM  
REVENTRM

-- La facturacion

SELECT * FROM TMPFAC2 WHERE TFCEDU = '11333381' AND TFRESO IN ('CUT02286236','CUT02286980','CUT02287358')

SELECT requltest,* FROM REQUISI1 WHERE ReqNro = 40212  --requltest   

BEGIN TRANSACTION;
UPDATE REQUISI1
SET requltest='P'
WHERE ReqNro = 40212
-- COMMIT
