Select CAST('UED URGENCIAS' AS NVARCHAR),sum(VALOR)as VALOR from(SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,
T1.TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,
T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,
I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND
 T.TFTDOC=T1.TFTDOC) INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD 
 INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
 INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) 
 WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFESTS = '1' AND T.TFCCODCAM =''UNION ALL SELECT T2.TFCEDU AS IDENTIFICACION, T2.TFTDOC AS TIPO_DOCUMENTO,
 C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,
 T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,
 T2.TFNITS AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
 FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)
 INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD 
 INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD 
 INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' and T.TFESTS = '1' AND T.TFCCODCAM =''
 union all
  SELECT T1.TFCEDU AS IDENTIFICACION, T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE, T1.TMCTVING AS INGRESO,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,
  T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,
  P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,
  I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) 
  INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD 
  INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON
   (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T1.TFPTPOTRN<>'H' AND
    T1.TFESTAANU1<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16') UNION ALL SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,
	C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,
	T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,
	ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2
	 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)
	 INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON 
	 ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND
	  I.INGCSC=T.TMCTVING)WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16')) L
	   WHERE CCOSTO IN ('20101','20102','20104')
	   UNION ALL
	    Select CAST('UED HOSPITALIZACION' AS NVARCHAR),sum(VALOR)as VALOR from(SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,
	   C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1.TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,
	   T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,
	   T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
	   FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 
	   INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD 
	   INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
	   INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFESTS = '1' AND
	    T.TFCCODCAM =''UNION ALL SELECT T2.TFCEDU AS IDENTIFICACION, T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU 
		AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,
		P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,
		I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)
		INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB 
		INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
		INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T2.TFSTPOTRN<>'H' AND 
		T2.TFESTAANU2<>'S' and T.TFESTS = '1' AND T.TFCCODCAM =''union all SELECT T1.TFCEDU AS IDENTIFICACION, T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,
		 T1.TMCTVING AS INGRESO,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,
		 T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,
		 T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA
		  FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 
		  INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD 
		  INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
		  INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFCCODCAM =''
		   AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16') UNION ALL SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,
		   T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,
		   G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB AS 
		   NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2 INNER JOIN TMPFAC T 
		   ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)
		   INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON
		    ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND
			 I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16'))
			 L WHERE CCOSTO IN ('20301','20306','20307')
			 UNION ALL
			  Select CAST('UED UCI GENERAL' AS NVARCHAR),sum(VALOR)as VALOR
			  from (SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1.TFCSCP AS CONSECUTIVO,T1.TFFCHP AS 
			  FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,
			  CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,
			  I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND 
			  T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON
			   M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
			   INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) 
			   WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFESTS = '1' AND T.TFCCODCAM =''UNION ALL SELECT T2.TFCEDU AS IDENTIFICACION, T2.TFTDOC AS TIPO_DOCUMENTO,
			   C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS
			    CANTIDAD,T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS 
				AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2
				 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)
				 INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD 
				 INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD 
				 INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' and T.TFESTS = '1' 
				 AND T.TFCCODCAM =''union all SELECT T1.TFCEDU AS IDENTIFICACION, T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE, T1.TMCTVING AS INGRESO,T1. TFCSCP AS
				  CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,
				  T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,
				  E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1
				   INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P
				    ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD
					 INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
					 INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFCCODCAM =
					 '' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16') 
					 UNION ALL 
					 SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,
					 T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,
					 T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS 
					 AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
					 FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND
					  C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD
					   INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD
					    INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' AND T.TFCCODCAM =''
						 AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16'))L WHERE CCOSTO IN ('20302','20308')
						 UNION ALL
						  Select CAST('UED UCI INTENSIVO' AS NVARCHAR),sum(VALOR)as VALOR 
						 from(SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1.TFCSCP AS CONSECUTIVO,
						 T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,
						 T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,
						 E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 
						 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1
						  INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD 
						  INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
						  INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFESTS = '1'
						   AND T.TFCCODCAM =''UNION ALL SELECT T2.TFCEDU AS IDENTIFICACION, T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,
						   T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,G.GRPDSC AS
						    GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB AS 
							NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2 
							INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND 
							C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON 
							T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD 
							INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' and
							 T.TFESTS = '1' AND T.TFCCODCAM =''union all SELECT T1.TFCEDU AS IDENTIFICACION, T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE, 
							 T1.TMCTVING AS INGRESO,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,
							 T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,
							 T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,
							 T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)
							  INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD 
							  INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR
							   INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND
							    I.INGCSC=T.TMCTVING) WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16')
								 UNION ALL
								  SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,
								  T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,
								  T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB 
								  AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
								  FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON 
								  (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER 
								  JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
								  INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)
								  WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16'))L WHERE CCOSTO = '20302'
								   UNION ALL 
								   SElect CAST('UED UCI INTERMEDIO' AS NVARCHAR),sum(VALOR)as VALOR from(SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,
								   T1.TMCTVING AS INGRESO,T1.TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,
								   T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS
								    CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS
									 ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) INNER JOIN MAEPRO M ON
									  M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON 
									  T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON 
									  (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) 
									  WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFESTS = '1' AND T.TFCCODCAM =''UNION ALL SELECT T2.TFCEDU AS IDENTIFICACION, T2.TFTDOC AS
									   TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,
									   MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,
									   P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS 
									   FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND 
									   T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON 
									   MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD 
									   INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD 
									   INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S'
									    and T.TFESTS = '1' AND T.TFCCODCAM =''union all SELECT T1.TFCEDU AS IDENTIFICACION, T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,
										 T1.TMCTVING AS INGRESO,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,
										 T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,
										 P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM 
										 AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND 
										 T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB 
										 INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP
										  INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON
										   (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFCCODCAM ='' AND
										    T.TFESTS = '0' AND P.MPCODP not in ('2','17','16') UNION ALL SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,
											C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS
											 PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS 
											 PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS
											  FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND 
											  T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS 
											  ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD 
											  INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD 
											  INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)WHERE T2.TFSTPOTRN<>'H' AND
											   T2.TFESTAANU2<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16'))L WHERE CCOSTO = '20308'
											    UNION ALL 
												Select CAST('UED IMAGENOLOGIA' AS NVARCHAR),sum(VALOR)as VALOR from(SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,
												C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,
												M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,
												CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,
												E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 
												INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 
												INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON
												 T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
												 INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND
												  I.INGCSC=T.TMCTVING) WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFESTS = '1' AND T.TFCCODCAM ='' AND CT.CPTCOD IN ('20','21')
												  UNION ALL
												   SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1. TFCSCP AS
												    CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,
													CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,
													T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,
													I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND 
													T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB
													 INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON
													  ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
													  INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)WHERE T1.TFPTPOTRN<>'H' AND 												  
													 T1.TFESTAANU1<>'S' AND T.TFESTS = '1' AND T.TFCCODCAM ='' AND T1.TFPRC1 = '881401-01' 
													 UNION ALL
													  SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS 
													  AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS 
													  VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS
													   CAMA,T2.TFNITS AS CONTRATO, ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR
													    AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND
														 T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)
														 INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON 
														 T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
														 INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND 
														 I.INGCSC=T.TMCTVING)WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' and T.TFESTS = '1' AND T.TFCCODCAM ='' AND
														  MS.MSRESO IN ('V08AI0211022','37730-19','37730-20','37730-4','37730-18','000022543-01')
														  UNION ALL
														   SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,
														   T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,
														   T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,
														   T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM
														    AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2 INNER JOIN TMPFAC T 
															ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU
															 AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB 
															 INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS 
															 INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD 
															 INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) 
																 WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' and   T.TFESTS = '1' AND
																  T.TFCCODCAM ='' AND T2.TFCENCOS = ('20503') AND MS.MSRESO NOT IN ('V08AI0211022','37730-19','37730-20','37730-4','37730-18','000022543-01')
																  UNION ALL 
																  SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP
																   AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,
																   T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS
																    NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
																	FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)INNER JOIN MAEPRO M ON
																	 M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD 
																	 INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
																	 INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND 
																	 I.INGCSC=T.TMCTVING)WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFCCODCAM='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16')
																	 AND CT.CPTCOD IN ('20','21')UNION ALL SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS
																	  INGRESO,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP
																	   AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM 
																	   AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,
																	   T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)
																	   INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD 
																	   INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
																	   INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC
																	    AND I.INGCSC=T.TMCTVING)WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFCCODCAM='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16') 
																		AND T1.TFPRC1 = '881401-01' UNION ALL SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS
																		 INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,
																		 G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS 
																		 CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA
																		  FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)
																		  INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P 
																		  ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS 
																		  INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU 
																		  AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0'
																		   AND P.MPCODP not in ('2','17','16')AND MS.MSRESO IN ('V08AI0211022','37730-19','37730-20','37730-4','37730-18','000022543-01')
																		   UNION ALL
																		    SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,
																			T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,
																			T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB AS
																			 NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA
																			  FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)
																			  INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON
																			   P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON
																			    E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND 
																				I.INGCSC=T.TMCTVING) WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in 
																				('2','17','16') AND T2.TFCENCOS = ('20503')AND MS.MSRESO NOT IN ('V08AI0211022','37730-19','37730-20','37730-4','37730-18','000022543-01')) L
																				 UNION ALL 
																				 Select CAST('UED CIRUGIA' AS NVARCHAR),sum(VALOR)as VALOR from(SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS 
																				 NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1.TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS 
																				 PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS
																				  DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS
																				   NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 
																				   INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)INNER JOIN MAEPRO M ON 
																				   M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN
																				    CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
																					INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC 
																					AND I.INGCSC=T.TMCTVING)WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFESTS = '1' AND T.TFCCODCAM =''AND CT.CPTCOD = '04'
																					UNION ALL 
																					SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1. 
																					TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP
																					 AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS 
																					 PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM
																					  AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T 
																					  ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 
																					  INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD 
																					  INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E
																					   ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON 
																					   (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND
																					    T.TFESTS = '1' AND T.TFCCODCAM =''AND T1.TFPCODSCC = '20401' AND CT.CPTCOD <> '04'UNION ALL SELECT T2.TFCEDU AS 
																						IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS 
																						CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS
																						 VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS
																						  CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS
																						   FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING 
																						   AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON
																						    MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD 
																							INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON
																							 MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)
																							 WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' and T.TFESTS = '1' AND T.TFCCODCAM =''AND T2.TFCENCOS = '20401'
																							 union all
																							  SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,
																							  T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS
																							   CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,
																							   P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS 
																							   NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1
																							    INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)INNER JOIN MAEPRO M
																								 ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD
																								  INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E
																								   ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I 
																								   ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' 
																								   AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16')AND CT.CPTCOD = '04'
																								   UNION ALL
																								    SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO
																									,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR 
																									AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,
																									P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS
																									 NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
																									 FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)
																									 INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON 
																									 M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON 
																									 ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU
																									  AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)
																									  WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP 
																									  not in ('2','17','16')AND T1.TFPCODSCC = '20401' AND CT.CPTCOD <> '04'UNION ALL SELECT T2.TFCEDU AS 
																									  IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS
																									   CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS
																									    AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS
																										 PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS
																										  NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
																										  FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)
																										  INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO 
																										  INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD 
																										  INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
																										  INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC 
																										  AND I.INGCSC=T.TMCTVING) WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0'  
																										  AND P.MPCODP not in ('2','17','16')AND T2.TFCENCOS = '20401') L 
																										  UNION ALL
																										   Select cast('UED CONSULTA EXTERNA'as nvarchar),
																										  sum(VALOR)as VALOR from(SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,
																										  T1.TMCTVING AS INGRESO,T1.TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS
																										   PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS 
																										   CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS 
																										   CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS
																										    FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND
																											 T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P 
																											 ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC 
																											 ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON 
																											 E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
																											 INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)WHERE T1.TFPTPOTRN<>'H'
																											  AND T1.TFESTAANU1<>'S' AND T.TFESTS = '1' AND T.TFCCODCAM =''AND P.MPCODP = '1' UNION ALL SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS
																											   TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1.TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS 
																											   CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC 
																											   AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS 
																											   NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON
																											    (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON 
																												P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME 
																												ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
																												INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' 
																												AND T.TFESTS = '1' AND T.TFCCODCAM =''AND M.PRNOMB LIKE '%INTERCONSULTA%' AND P.MPCODP <> '1'
																												UNION ALL 
																												SELECT T2.TFCEDU AS
																												 IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS
																												  FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS
																												   CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,
																 ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
																 FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)
																 INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB 
																 INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
																 INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)
																 WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' AND T.TFESTS = '1' AND T.TFCCODCAM =''AND P.MPCODP = '1' 
																 UNION ALL 
																 SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,
																 C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,
																 M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,
																 CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,
																 E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 
																 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 
															 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD 
															 INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
															 INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) 
															 WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16')AND P.MPCODP = '1' 
															 UNION ALL 
															 SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,
															 T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP 
															 AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,
															 T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
															 FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)
															 INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD 
															 INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP 
															 INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
															 INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) WHERE T1.TFPTPOTRN<>'H' AND 
															 T1.TFESTAANU1<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16')AND M.PRNOMB LIKE '%INTERCONSULTA%' AND P.MPCODP <> '1'
															 UNION ALL 
															 SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,
															 T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,
															 T2.TFNITS AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
															 FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)
															 INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB 
															 INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
															  INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)
															  WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16') AND P.MPCODP = '1') L 
															  UNION ALL 
															  Select CAST('UED REHABILITACION'AS NVARCHAR),sum(VALOR)as VALOR from(SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,
															  C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,
															  T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,
															  CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS
															   FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,
															  T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC)
															  INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD 
															  INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR 
															  INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND 
															  I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFESTS = '1' AND T.TFCCODCAM =''AND 
															  T1.TFPRC1 IN ('937000','938300','931000','931000-23','890208','931000-55','940700-1','931000-4','931000-34','931000-7','931000-21','931000-6','931000-5','931000-22','890308','931000-42','890409','931000-15','931000-8','931000-18','931000-19')
															  UNION ALL 
															  SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,
															  T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,
															  T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,
															  T.TFCCODCAM AS CAMA,T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
															  FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND 
															  T.TFTDOC=T1.TFTDOC)INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD 
															  INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON 
															  (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)
															  WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16')AND T1.TFPRC1 
															  IN ('937000','938300','931000','931000-23','890208','931000-55','940700-1','931000-4','931000-34','931000-7','931000-21','931000-6','931000-5','931000-22','890308','931000-42','890409','931000-15','931000-8','931000-18','931000-19')) L 
															  UNION ALL 
															  Select CAST('TOTAL PENDIENTES' AS NVARCHAR),sum(VALOR)as VALOR
															   from (SELECT T1.TFCEDU AS IDENTIFICACION,T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T1.TMCTVING AS INGRESO,T1.TFCSCP AS CONSECUTIVO,
															  T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,
															  T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,
															  T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
															  FROM TMPFAC1 T1 INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) 
															  INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD 
															  INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP 
															  INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
															  INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) 
															  WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFESTS = '1' AND T.TFCCODCAM =''UNION ALL SELECT T2.TFCEDU AS IDENTIFICACION, 
															  T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,
															  T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,
															  CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,T2.TFNITS AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,
															  E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC2 T2 
															  INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)
															  INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO 
															  INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS 
															  INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC 
															  AND I.INGCSC=T.TMCTVING) WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' and T.TFESTS = '1' AND T.TFCCODCAM =''
															  union all 
															  SELECT T1.TFCEDU AS IDENTIFICACION, T1.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE, 
															  T1.TMCTVING AS INGRESO,T1. TFCSCP AS CONSECUTIVO,T1.TFFCHP AS FECHA_PORCEDIMIENTO,T1.TFPRC1 AS CUPS,M.PRNOMB AS PROCEDIMIENTO,T1.TFCANPR AS CANTIDAD,
															  T1.TFVATP AS VALOR,CT.CPTDESC AS CONCEPTO_SERVICIO,T1.TFPCODSCC AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,
															  T1.TFNITP AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA FROM TMPFAC1 T1 
															  INNER JOIN TMPFAC T ON (T.TFCEDU=T1.TFCEDU AND T.TMCTVING=T1.TMCTVING AND T.TFTDOC=T1.TFTDOC) INNER JOIN MAEPRO M ON M.PRCODI=T1.TFPRC1 INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB 
															  INNER JOIN CPTSERV CT ON M.PRCPTO = CT.CPTCOD INNER JOIN CENCOST CC ON T1.TFPCODSCC=CC.CNCCOD 
															  INNER JOIN MAEEMP ME ON ME.MENNIT=T1.TFNITP INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN CAPBAS C ON (C.MPCEDU=T1.TFCEDU AND C.MPTDOC=T1.TFTDOC)
															  INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING) 
															  WHERE T1.TFPTPOTRN<>'H' AND T1.TFESTAANU1<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16') 
															  UNION ALL 
															  SELECT T2.TFCEDU AS IDENTIFICACION,T2.TFTDOC AS TIPO_DOCUMENTO,C.MPNOMC AS NOMBRE_PACIENTE,
															  T2.TMCTVING AS INGRESO,T2.TFCSCS AS CONSECUTIVO,T2.TFFCSU AS FECHA_SUMINISTRO,T2.TFRESO AS CODIGO,MS.MSNOMG AS PRODUCTO,T2.TFCANS AS CANTIDAD,
															  T2.TFVATS AS VALOR,G.GRPDSC AS GRUPO,T2.TFCENCOS AS CCOSTO,CC.CNCDSC AS DESCRIPCION_CENCOSTO,P.MPNOMP AS PABELLON_ACOSTADO,T.TFCCODCAM AS CAMA,
															  T2.TFNITS AS CONTRATO,ME.MENOMB AS NOMBRE_CONTRATO,E.EMPDSC AS NOMBRE_EMPRESA,I.INGFECADM AS FECHA_INGRESO,I.INGFECEGR AS FECHA_EGRESO,T.TFESTS AS ESTADO_SALIDA 
															  FROM TMPFAC2 T2 INNER JOIN TMPFAC T ON (T.TFCEDU=T2.TFCEDU AND T.TMCTVING=T2.TMCTVING AND T.TFTDOC=T2.TFTDOC)
															  INNER JOIN CAPBAS C ON (C.MPCEDU=T2.TFCEDU AND C.MPTDOC=T2.TFTDOC)INNER JOIN MAESUM1 MS ON MS.MSRESO=T2.TFRESO INNER JOIN MAEPAB P ON P.MPCODP=T.TFCCODPAB 
															  INNER JOIN CENCOST CC ON T2.TFCENCOS=CC.CNCCOD 
															  INNER JOIN MAEEMP ME ON ME.MENNIT=T2.TFNITS INNER JOIN EMPRESS E ON E.MECNTR=ME.MECNTR INNER JOIN GRUPOS G ON MS.MSGRPCOD=G.GRPCOD 
															  INNER JOIN INGRESOS I ON (I.MPCEDU=T.TFCEDU AND I.MPTDOC=T.TFTDOC AND I.INGCSC=T.TMCTVING)
															  WHERE T2.TFSTPOTRN<>'H' AND T2.TFESTAANU2<>'S' AND T.TFCCODCAM ='' AND T.TFESTS = '0' AND P.MPCODP not in ('2','17','16')) L

