SELECT * FROM MAEESP  WHERE MENomE LIKE ('%TERA%RESP%')
select * from CITMED2
-- RESERVADOS
-- ATENDIDOS

SELECT * FROM CTRLCITAS
SELECT * FROM CITMED1


SELECT A.CitNum,A.CitFchHra,D.MPTDOC,D.MPCEDU , D.MPNOMC,A.CitCmbDto
FROM
CTRLCITAS A, CITMED2 B, CITMED1 C ,CAPBAS D
WHERE A.CitFchHra >= '2016-01-01' AND  A.CitCmbDto IN ('RESERVADA','ATENDIDA') AND A.CITNUM=B.CITNUM AND
    B.MECodE IN (730) AND  A.CITNUM= C.CITNUM AND C.CITTIPDOC=D.MPTDOC AND C.CITCED=D.MPCEDU
	ORDER BY C.CitCed ,A.CitFchHra