--  Generar SQL 
--  Versión:                   	V7R1M0 100423 
--  Generado en:              	01/06/20 09:10:43 
--  Base de datos relacional:       	S10B409T 
--  Opción de estándares:          	DB2 for i 
CREATE TABLE HOSVINEW.TERCEROS ( 
	TRCCOD CHAR(15) CCSID 284 NOT NULL , 
	TRCTPOIDE DECIMAL(2, 0) DEFAULT NULL , 
	TRCRAZSOC CHAR(60) CCSID 284 DEFAULT NULL , 
	TRCDIR CHAR(60) CCSID 284 DEFAULT NULL , 
	TRCTLF CHAR(30) CCSID 284 DEFAULT NULL , 
	TRCFAX CHAR(20) CCSID 284 DEFAULT NULL , 
	TRCAAE CHAR(10) CCSID 284 DEFAULT NULL , 
	TRCEMAIL VARCHAR(400) CCSID 284 DEFAULT NULL , 
	TRCMDCODD CHAR(2) CCSID 284 DEFAULT NULL , 
	TRCMDCODM DECIMAL(9, 0) DEFAULT NULL , 
	TRCMDCODB DECIMAL(9, 0) DEFAULT NULL , 
	TCOCOD DECIMAL(2, 0) DEFAULT NULL , 
	TRCFCHCRE TIMESTAMP DEFAULT NULL , 
	TRCTIPENT DECIMAL(2, 0) DEFAULT NULL , 
	TRCNIT CHAR(15) CCSID 284 DEFAULT NULL , 
	TRCDIGVER CHAR(1) CCSID 284 DEFAULT NULL , 
	TRCSGL CHAR(20) CCSID 284 DEFAULT NULL , 
	TRCTIPTRC DECIMAL(2, 0) DEFAULT NULL , 
	TRCRSL CHAR(20) CCSID 284 DEFAULT NULL , 
	TRCREICRP DECIMAL(15, 0) DEFAULT NULL , 
	TRCREINRP CHAR(73) CCSID 284 DEFAULT NULL , 
	TRCREPLEG CHAR(60) CCSID 284 DEFAULT NULL , 
	TRCPRMNOM CHAR(12) CCSID 284 DEFAULT NULL , 
	TRCSEGNOM CHAR(12) CCSID 284 DEFAULT NULL , 
	TRCPRMAPE CHAR(18) CCSID 284 DEFAULT NULL , 
	TRCSEGAPE CHAR(18) CCSID 284 DEFAULT NULL , 
	TRCEXCMM CHAR(1) CCSID 284 DEFAULT NULL , 
	TRCACT CHAR(1) CCSID 284 DEFAULT NULL , 
	TRCMNJRUT CHAR(1) CCSID 284 DEFAULT NULL , 
	PAISCOD CHAR(4) CCSID 284 DEFAULT NULL , 
	TRCUSUINA CHAR(10) CCSID 284 DEFAULT NULL , 
	TRCFCHINA TIMESTAMP DEFAULT NULL , 
	TRCNODOM CHAR(1) CCSID 284 DEFAULT NULL , 
	TRCAPLIE CHAR(1) CCSID 284 DEFAULT NULL , 
	TRCIDEERP CHAR(2) CCSID 284 DEFAULT NULL , 
	TRCFECNAC TIMESTAMP DEFAULT NULL , 
	TRCSEX CHAR(1) CCSID 284 DEFAULT NULL , 
	TRCANLCOD DECIMAL(4, 0) DEFAULT NULL , 
	TRCINDARE CHAR(1) CCSID 284 DEFAULT NULL , 
	TRCCLC1 VARCHAR(20) CCSID 284 DEFAULT NULL , 
	TRCREGFIS VARCHAR(2) CCSID 284 DEFAULT NULL , 
	TRCRESFIS VARCHAR(10) CCSID 284 DEFAULT NULL , 
	CONSTRAINT HOSVINEW.Q_CLI_V7_TERCEROS_TRCCOD_00001 PRIMARY KEY( TRCCOD ) )   
	; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON HOSVINEW.TERCEROS TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HOSVINEW.TERCEROS TO RMAESTRE WITH GRANT OPTION ; 
  
CREATE INDEX HOSVINEW.ITERCEROS1 
	ON HOSVINEW.TERCEROS ( TRCTIPTRC ASC )   
	; 
  
CREATE INDEX HOSVINEW.ITERCEROS2 
	ON HOSVINEW.TERCEROS ( TRCTIPENT ASC )   
	; 
  
CREATE INDEX HOSVINEW.ITERCEROS3 
	ON HOSVINEW.TERCEROS ( TRCMDCODD ASC , TRCMDCODM ASC , TRCMDCODB ASC )   
	; 
  
CREATE INDEX HOSVINEW.ITERCEROS4 
	ON HOSVINEW.TERCEROS ( PAISCOD ASC )   
	; 
  
CREATE INDEX HOSVINEW.ITERCEROS6 
	ON HOSVINEW.TERCEROS ( TRCTPOIDE ASC )   
	; 
  
CREATE INDEX HOSVINEW.ITERCEROS7 
	ON HOSVINEW.TERCEROS ( TCOCOD ASC )   
	; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00001 
	ON HOSVINEW.TERCEROS ( TRCRAZSOC ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00001 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00002 
	ON HOSVINEW.TERCEROS ( TRCCOD ASC , TRCRAZSOC ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00002 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00003 
	ON HOSVINEW.TERCEROS ( TRCACT ASC , TRCRAZSOC ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00003 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00004 
	ON HOSVINEW.TERCEROS ( TRCACT ASC , TRCCOD ASC , TRCRAZSOC ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00004 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00005 
	ON HOSVINEW.TERCEROS ( TRCACT ASC , TRCCOD ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00005 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00006 
	ON HOSVINEW.TERCEROS ( TRCCOD ASC , TRCRAZSOC ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00006 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00007 
	ON HOSVINEW.TERCEROS ( TRCNIT ASC , TRCCOD ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00007 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00008 
	ON HOSVINEW.TERCEROS ( TRCACT ASC , TRCCOD ASC , TRCRAZSOC ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00008 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00009 
	ON HOSVINEW.TERCEROS ( TRCNIT ASC , TRCRAZSOC ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00009 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00010 
	ON HOSVINEW.TERCEROS ( TRCRAZSOC ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00010 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00011 
	ON HOSVINEW.TERCEROS ( TRCEXCMM ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00011 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00012 
	ON HOSVINEW.TERCEROS ( TRCNIT ASC , TRCCOD ASC , TRCRAZSOC ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00012 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.TERCEROS_INDEX_00013 
	ON HOSVINEW.TERCEROS ( TRCACT ASC , PAISCOD ASC , TRCEXCMM ASC , TRCTIPENT ASC , TRCTPOIDE ASC , TRCTIPTRC ASC , TRCDIR ASC , TRCTLF ASC , TRCFAX ASC , TRCAAE ASC , TRCEMAIL ASC , TRCFCHCRE ASC , TRCDIGVER ASC , TRCSGL ASC , TRCRSL ASC , TRCREICRP ASC , TRCREINRP ASC , TRCREPLEG ASC , TRCPRMNOM ASC , TRCSEGNOM ASC )   
	; 
  
LABEL ON INDEX HOSVINEW.TERCEROS_INDEX_00013 
	IS 'Índice generado desde el Asesor de índices' ; 
  
CREATE INDEX HOSVINEW.UTERCER1 
	ON HOSVINEW.TERCEROS ( TRCCOD DESC )   
	; 
  
CREATE INDEX HOSVINEW.UTERCER2 
	ON HOSVINEW.TERCEROS ( TRCNIT ASC )   
	; 
  
CREATE VIEW HOSVINEW."RES 256" ( 
	DOC , 
	NUMERO , 
	FECHA_MOV , 
	MES_MOV , 
	AÑO , 
	NIT , 
	RAZON_SOCIAL FOR COLUMN RAZON00001 , 
	OBLIGACION , 
	SUBGRUPO , 
	GRUPO , 
	VALOR , 
	NAT , 
	ESTADO_DOC , 
	OBSERVACIONES FOR COLUMN OBSER00001 ) 
	AS 
	SELECT MOVCONT2.DOCCOD AS DOC, MOVCONT2.MVCNRO AS NUMERO, MOVCONT2.MVCCFCH AS FECHA_MOV, MOVCONT2.MVCMES AS MES_MOV, MOVCONT2.MVCANIO AS AÑO, MOVCONT2.TRCCOD AS NIT, TERCEROS.TRCRAZSOC AS RAZON_SOCIAL, MOVCONT2.MVCDOCRF1 AS OBLIGACION, PROVEEDOR1.PRVCON AS SUBGRUPO, PROVEEDOR1.PRVCRGCON AS GRUPO, MOVCONT2.MVCVLRLC AS VALOR, MOVCONT2.MVCNAT AS NAT, MOVCONT3.MVCEST AS ESTADO_DOC, MOVCONT3.MVCCPT AS OBSERVACIONES 
	FROM ((HOSVINEW.MOVCONT2 MOVCONT2 INNER JOIN HOSVINEW.MOVCONT3 MOVCONT3 ON (MOVCONT2.MCDPTO = MOVCONT3.MCDPTO) AND (MOVCONT2.MVCNRO = MOVCONT3.MVCNRO) AND (MOVCONT2.DOCCOD = MOVCONT3.DOCCOD) AND (MOVCONT2.EMPCOD = MOVCONT3.EMPCOD)) INNER JOIN HOSVINEW.TERCEROS TERCEROS ON MOVCONT2.TRCCOD = TERCEROS.TRCCOD) INNER JOIN HOSVINEW.PROVEEDOR1 PROVEEDOR1 ON TERCEROS.TRCCOD = PROVEEDOR1.PRVCOD 
	WHERE MOVCONT2.DOCCOD IN ('CEG', 'ACH') AND MOVCONT2.MVCANIO=2018 ; 
  
LABEL ON TABLE HOSVINEW."RES 256" 
	IS 'RESOLUCION 256' ; 
  
GRANT ALTER , REFERENCES , SELECT   
ON HOSVINEW."RES 256" TO HOSVITAL WITH GRANT OPTION ;
