-- Para facturacion Procedimientos

UPDATE HOSVINEW.MAEATE2 SET MAPVLRSIV = MPINTE WHERE MAPPORIVA =0;
UPDATE HOSVINEW.MAEATE2 SET MACODIMPP = NULL WHERE MAPPORIVA = 0 AND MAPVLRSIV = MPINTE;
UPDATE HOSVINEW.TMPFAC1 SET TFPVLRSIV = TFINTE WHERE TFPPORIVA = 0;
UPDATE HOSVINEW.TMPFAC1 SET TFPCODIMPP = NULL WHERE TFPPORIVA = 0 AND TFPVLRSIV = TFINTE;


-- Para facturacion Suministros
select * from hosvital.maeate3;

UPDATE HOSVINEW.MAEATE3 SET MASVLRSIV = MAVALU WHERE MASPORIVA =0;
UPDATE HOSVINEW.MAEATE3 SET MACODIMPS = NULL WHERE MASPORIVA = 0 AND MASVLRSIV = MAVALU; -- MAVALU EN VEZ DE MPINTE

SELECT TFINTE, A.* FROM HOSVITAL.TMPFAC2 A;

UPDATE HOSVINEW.TMPFAC2 SET TFSVLRSIV = TFVALU WHERE TFSPORIVA = 0;
UPDATE HOSVINEW.TMPFAC2 SET TFCODIMPS = NULL WHERE TFSPORIVA = 0 AND TFSVLRSIV = TFVALU;  --  TFVALU  , EN VEZ DE TFINTE