select * FROM HOSVIPRU.RESSEV  WHERE RESFEC >= '2020-07-01 00:00:00';

SELECT  FACFCH , COUNT(*) 
FROM HOSVIPRU.MAEATE 
WHERE FACFCH >= '2020-07-01' 
GROUP BY FACFCH
ORDER BY FACFCH;

SELECT * FROM HOSVIPRU.TERCEROS;

SELECT * FROM HOSVIPRU.MAEATE WHERE FACFCH ='2020-07-07';

SELECT M.MPNFAC,M.MATIPDOC,M.MPMENI, M.FACFCH,MAE.MENOMB
FROM HOSVIPRU.MAEATE M
INNER JOIN HOSVIPRU.MAEEMP MAE ON (MAE.MENNIT=M.MPMENI)
WHERE M.FACFCH ='2020-07-07';



SELECT M.MATIPDOC AS TIPO_FAC,M.MPNFAC AS FACTURA,M.MPMENI AS COD_CONTRATO, M.FACFCH,MAE.MENOMB , T.TRCRAZSOC, T.TRCCOD,T.TRCEMAIL, T.TRCDIR,T.TRCREGFIS, T.TRCRESFIS
FROM HOSVIPRU.MAEATE M
INNER JOIN HOSVIPRU.MAEEMP MAE ON (MAE.MENNIT=M.MPMENI)
LEFT  JOIN HOSVIPRU.TERCEROS T ON (MAE.MECNTR = T.TRCNIT)
WHERE M.FACFCH ='2020-07-07' ; -- AND M.MPNFAC IN (632644, 632645);


SELECT * FROM HOSVIPRU.MAEEMP WHERE MENOMB LIKE('%CONVIDA%'); -- MECNTR
SELECT * FROM HOSVIPRU.TERCEROS WHERE TRCRAZSOC LIKE('%CONVIDA%')
