-- consumo promedio mes

SELECT HOSVITAL.KARDEX.BODEGA, HOSVITAL.KARDEX.MSRESO, HOSVITAL.MAESUM1.MSNOMG, HOSVITAL.KARDEX.MOVSUNI, HOSVITAL.KARDEX.MOVSVLR, HOSVITAL.MAESUM1.MSGRPCOD -- con promedio dia y mes
FROM HOSVITAL.MAESUM1 INNER JOIN HOSVITAL.KARDEX ON  HOSVITAL.KARDEX.MSRESO = HOSVITAL.MAESUM1.MSRESO
 WHERE HOSVITAL.KARDEX.BODEGA='01';


select * from hosvital.dspfrmc;

select COUNT(*) from hosvital.movinv4  WHERE FCHMVT >= '2020-08-01 00:00:00' AND DOCCOD='ASA';


select * from hosvital.docucon where docdsc like ('%SAL%');
select  * from hosvital.movinv4  ;  WHERE FCHMVT >= '2020-08-01 00:00:00' AND DOCCOD='ASA';

SELECT * FROM HOSVITAL.KARDEX ORDER BY BODEGA,MSRESO;
SELECT * FROM HOSVITAL.BODEGAS;

SELECT K.BODEGA, B.BODDESC,K.MSRESO, M.MSNOMG, K.MOVSUNI UNIDADES, K.MOVSVLR VALOR, M.MSGRPCOD  GRUPO ,                            -- con promedio dia y mes
(SELECT SUM(MVTOCNT)
 FROM HOSVITAL.MOVINV4 M4
  WHERE M4.FCHMVT>= '2020-08-01 00:00:00' AND  M4.FCHMVT<= '2020-08-31 23:59:59'  AND M4.DOCCOD='ASA'  AND M4.MVTOES='S' AND M4.MVTOBDS=K.BODEGA AND M4.MSRESO=K.MSRESO
) CONSUMO_PERIODO,
(SELECT SUM(MVTOCNT)/30
 FROM HOSVITAL.MOVINV4 M4
  WHERE M4.FCHMVT>= '2020-08-01 00:00:00' AND  M4.FCHMVT<= '2020-08-31 23:59:59'  AND M4.DOCCOD='ASA'  AND M4.MVTOES='S' AND M4.MVTOBDS=K.BODEGA AND M4.MSRESO=K.MSRESO
) CONSUMO_PROMEDIO
FROM HOSVITAL.MAESUM1 M
 INNER JOIN HOSVITAL.KARDEX  K ON  (K.MSRESO = M.MSRESO)
INNER JOIN HOSVITAL.BODEGAS B ON (B.EMPCOD='01' AND B.BODEGA=K.BODEGA)
 WHERE K.BODEGA='01'
ORDER BY K.BODEGA,K.MSRESO;