SELECT K.DOCTIP TIPO,K.DOCNRO NUMERO ,F.HISTIPDOC TIPODOC, F.HISCKEY DOCUMENTO, K.MOVFOLPAC FOLIO, C.MPNOMC PACIENTE,F.FSMDSCMDC,K.MOVFCH FECHA 
FROM HOSVITAL.KARDEX1 K 
INNER JOIN HOSVITAL.FRMSMNS F ON (F.HISTIPDOC=K.MOVTIPDOC AND F.HISCKEY=K.MOVCODPAC AND F.HISCSEC=K.MOVFOLPAC AND F.FSMMSRESO=K.MSRESO) 
INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC=F.HISTIPDOC AND C.MPCEDU=F.HISCKEY)
 WHERE K.DOCTIP='ASA' AND K.DOCNRO>=12415232;

SELECT * FROM HOSVITAL.KARDEX1  WHERE DOCTIP='ASA' AND  DOCNRO=12415232;
SELECT * FROM HOSVITAL.KARDEX1  WHERE DOCTIP='ASA' AND  DOCNRO=12415232   ;

SELECT  * FROM HOSVITAL.FRMSMNS WHERE HISTIPDOC='CC' AND HISCKEY='1140830482' AND HISCSEC>=93  ORDER BY HISCSEC;
SELECT * FROM HOSVITAL.HCCOM1 WHERE HISCKEY='1140830482' AND HISCSEC=93;

SELECT * FROM HOSVITAL.DOCUCON WHERE DOCCOD='ASA';

SELECT * FROM HOSVITAL.DSPFRMC  WHERE HISCKEY='1140830482' AND HISCSEC=93;
SELECT * FROM HOSVITAL.DSPFRMC1  WHERE HISCKEY='1140830482' AND HISCSEC=93;  -- DESPACHO NRO 3855097

-- CON DESPACHOS DIRECTOS

SELECT K.DOCTIP TIPO,K.DOCNRO NUMERO ,F.HISTIPDOC TIPODOC, F.HISCKEY DOCUMENTO, K.MOVFOLPAC FOLIO, C.MPNOMC PACIENTE,F.FSMDSCMDC,K.MOVFCH FECHA 
FROM HOSVITAL.KARDEX1 K 
LEFT JOIN HOSVITAL.FRMSMNS F ON (F.HISTIPDOC=K.MOVTIPDOC AND F.HISCKEY=K.MOVCODPAC AND F.HISCSEC=K.MOVFOLPAC AND F.FSMMSRESO=K.MSRESO) 
INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC=F.HISTIPDOC AND C.MPCEDU=F.HISCKEY)
LEFT JOIN HOSVITAL.DSPFRMC  DSP ON (DSP.HISTIPDOC= F.HISTIPDOC AND DSP.HISCKEY=F.HISCKEY  AND DSP.HISCSEC=K.MOVFOLPAC AND DSP.MSRESO=K.MSRESO)
 WHERE K.DOCTIP='ASA' AND K.DOCNRO=12415232;	


SELECT K.DOCTIP TIPO,K.DOCNRO NUMERO ,K.MOVTIPDOC TIPODOC, K.MOVCODPAC DOCUMENTO, K.MOVFOLPAC FOLIO, C.MPNOMC PACIENTE,
(
SELECT   F.FSMDSCMDC FROM HOSVITAL.FRMSMNS F WHERE F.HISTIPDOC=K.MOVTIPDOC AND F.HISCKEY=K.MOVCODPAC AND F.HISCSEC=K.MOVFOLPAC AND F.FSMMSRESO=K.MSRESO  GROUP BY F.FSMDSCMDC) 
  FORMULADO,
(
SELECT  MAESUM1.MSNOMG 
 FROM  HOSVITAL.DSPFRMC  DSP 
INNER JOIN HOSVITAL.MAESUM1 MAESUM1 ON (MAESUM1.MSRESO= DSP.MSRESO )
WHERE  DSP.HISTIPDOC=K.MOVTIPDOC  AND DSP.HISCKEY=K.MOVCODPAC  AND DSP.HISCSEC=K.MOVFOLPAC AND DSP.MSRESO=K.MSRESO GROUP BY MAESUM1.MSNOMG)
 DIRECTO,K.MOVFCH FECHA 
FROM HOSVITAL.KARDEX1 K 
INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC=K.MOVTIPDOC AND C.MPCEDU=K.MOVCODPAC)
 WHERE K.DOCTIP='ASA' AND K.DOCNRO>=12415262
ORDER BY K.DOCNRO;


SELECT * FROM HOSVITAL.KARDEX1 WHERE  DOCTIP='ASA' AND DOCNRO= 12415268;
SELECT * FROM HOSVITAL.FRMSMNS WHERE HISCKEY='80162061' AND HISCSEC IN (6);
SELECT * FROM HOSVITAL.DSPFRMC  WHERE HISCKEY='80162061' AND HISCSEC IN (6);


SELECT * FROM HOSVITAL.MAESUM1 WHERE MSRESO IN ('0010A02B','0026A03D', '0023A03A' , '0128B05B'   ,'0023A03A'       	);
