SELECT * FROM HOSVITAL.KARDEX1 WHERE MOVFCH>= '2020-05-01 00:00:00' ;
SELECT * FROM  HOSVITAL.DOCUCON;

SELECT * FROM HOSVITAL.BODEGAS;

SELECT K.BODEGA,B.BODDESC,K.MSRESO,K. DOCTIP,D.DOCDSC,  K.DOCNRO,K.MOVFCH,K.MOVCNT,K.MOVBOD,B1.BODDESC, K.MOVCODPAC

FROM HOSVITAL.KARDEX1 K
INNER JOIN HOSVITAL.DOCUCON D ON (D.DOCCOD=K.DOCTIP)
INNER JOIN HOSVITAL.BODEGAS B ON (B.BODEGA= K.BODEGA)
INNER JOIN HOSVITAL.BODEGAS B1 ON (B1.BODEGA= K.MOVBOD)
WHERE K.MOVFCH>= '2020-05-01 00:00:00' AND K.MOVFCH<= '2020-05-11 23:59:59' AND K.BODEGA='00' AND MOVBOD='01' AND K.MOVES='S'
ORDER BY K.MOVFCH;