select * from hosvital.movcont2 where doccod='PCP' AND MVCNRO = 2172  ORDER BY EMPCOD,MVCCSC;

UPDATE hosvital.movcont2
SET MVCCSC=366
WHERE doccod='PCP' AND MVCNRO = 2172  AND  MVCCSC=500 AND TRCCOD='1098636393';

UPDATE hosvital.movcont2
SET  EMPCOD='01'
WHERE doccod='PCP' AND MVCNRO = 2172  AND  MVCCSC=2 AND TRCCOD='12621429';


UPDATE hosvital.movcont2
SET  MVCCSC=372,EMPCOD='01'
WHERE doccod='PCP' AND MVCNRO = 2172  AND  MVCCSC=7	 AND TRCCOD='16638808' AND EMPCOD='';

select * from hosvital.movcont2 where doccod='PCP' AND MVCNRO = 2172  ORDER BY EMPCOD,MVCCSC;


SELECT * FROM HOSVITAL.NIMOVCON2 where doccod='RCM' AND NIMCNRO = 298 ORDER BY EMPCOD,NIMC2CSC;


SELECT  A.MVCCSC AS L1,B.NIMC2CSC ASN1,A.TRCCOD, B.TRCCOD, A.MVCVLRLC AS L2, A.MVCVLR AS L2, B.NIMC2VL AS N2, B.NIMC2VLR AS N3
FROM HOSVITAL.MOVCONT2 A , HOSVITAL.NIMOVCON2 B
WHERE A.DOCCOD='RCM' AND A.DOCCOD = B.DOCCOD AND A.MVCNRO = 298 AND --  A.TRCCOD = B.TRCCOD AND
    A.MVCNRO = B.NIMCNRO   AND A.MVCVLR  <> B.NIMC2VLR AND A.MVCCSC=B.NIMC2CSC;


select * from hosvital.movcont2 where doccod='RCM' AND MVCNRO = 298  AND TRCCOD= '830011670' ORDER BY EMPCOD,MVCCSC;

SELECT * FROM HOSVITAL.NIMOVCON2 where doccod='RCM' AND NIMCNRO = 298   AND TRCCOD= '830011670' ORDER BY EMPCOD,NIMC2CSC;   -- 92

UPDATE HOSVITAL.NIMOVCON2
SET NIMC2VLR=0, NIMC2VL=0
 where doccod='RCM' AND NIMCNRO = 298   AND TRCCOD= '890900943' AND NIMC2VL=3000.00		 AND NIMC2CSC=89;
;




