SELECT YEAR(A.FACFCH), MONTH(A.FACFCH), C.PRCODI, C.PRNOMB, SUM(A.MATOTF)
FROM HOSVITAL.MAEATE A, HOSVITAL.MAEATE2 B, HOSVITAL.MAEPRO C
WHERE A.FACFCH >='2019-01-01' AND  A.MPNFAC = B.MPNFAC AND B.PRCODI = C.PRCODI AND C.PRNOMB LIKE('%HEMODI%')
GROUP BY YEAR(A.FACFCH), MONTH(A.FACFCH),C.PRCODI, C.PRNOMB
ORDER BY  YEAR(A.FACFCH), MONTH(A.FACFCH), C.PRCODI,C.PRNOMB;
             
SELECT * FROM HOSVITAL.MAEPRO WHERE PRNOMB LIKE('%HEMODI%');
         

