SELECT * FROM HOSVITAL.MAEPAB;
SELECT * FROM HOSVITAL.MAEESP  WHERE MENOME LIKE ('%NEUROCIRU%');

-- 514,
SELECT * FROM HOSVITAL.MAEATE LIMIT 10;
-- DEL 2018-0|1-01 / 31_03/2019
--ANULADAS NO




SELECT * FROM HOSVITAL.MAEPRO WHERE PRNOMB LIKE ('%ORTOPEDIA%');

SELECT * FROM HOSVITAL.MAEATE2 LIMIT 100;
SELECT * FROM HOSVITAL.MAEATE LIMIT 100;  --MPMENI

SELECT * FROM HOSVITAL.MAEPRO;
SELECT * FROM HOSVITAL.MAEEMP;


/*
SELECT A.FACFCH, A.MATOTF,B.PRCODI,C.PRNOMB
FROM HOSVITAL.MAEATE A, MAEATE2 B, MAEPRO C
WHERE A.FACFCH>= '2018-01-01' AND A.MPNFAC = B.MPNFAC  and A.MPMENI = B.MENNIT AND 
          AND C.PRCODI IN ('10101')

*/



select * from hosvital.maeprov  WHERE PRCODI LIKE ('12%');  -- ORDER BY PRCODI ; -- WHERE PRCODI='12403';
select * from hosvital.cencost   where  cnccod='M0213'; 

select * from hosvital.cencost  where cncdsc like ('%NEURO%');

/*

10413    	NEUROCIRUGIA                  	
F0408    	NEUROCIRUGIA                  	
        	
M0421    	NEUROCIRUGIA                  	
M0318    	UCIN (UNID. CUID. INT. NEURO) 	

10403    	CIRUGIA DE ORTOPEDIA          	
F0401    	CIRUGIA ORTOPEDIA TRAUMATOLOGI	
F0430    	CIRUGIA ORTOPEDICA 2012       	
      	
M0425    	CIRUGIA  ORTOPEDIA      

10413,F0408,M0421,M0318,10403,F0401,F0430,M0425
*/

select * from hosvital.cencost  where cncdsc like ('%ORTO%');

SELECT * FROM HOSVITAL.MAEATE2;

select * from hosvital.cencost  where   CNCCOD = 'M0502';


select * from hosvital.maeprov  ;  -- WHERE PRCODI='12403';

--FECHA DE LQA FACTURA, 
--FACTURA, VALOR TOTAL, CUPS, NOMBRE DEL PROCEDI, EL CONTRATO, VALOR DEL PROCEMIENTOP,


SELECT  A.FACFCH, A.MPNFAC, M1.MENNIT,M1.MENOMB,A.MATOTF,B.PRCODI,C.PRNOMB,B.MAVATP 
FROM  HOSVITAL.MAEATE A, 
	 HOSVITAL.MAEATE2 B,
	 HOSVITAL.MAEPRO C,
	 HOSVITAL.MAEPROV M,
	 HOSVITAL.CENCOST C1,
	 HOSVITAL.MAEEMP M1
WHERE A.FACFCH>= '2018-01-01' AND A.MPNFAC = B.MPNFAC  AND M1.MENNIT =A.MPMENI  AND
           B.PRCODI = C.PRCODI AND C.PRCODI = M.PRCODI AND  C1.CNCCOD=    M.PRCCCOSV AND
 	C1.CNCCOD IN ('10413','F0408','M0421','M0318','10403','F0401','F0430','M0425')  AND  
	A.MAESTF NOT IN (1,10) AND M.PRCVIG IN (2019) and C1.CNCEST ='S'
GROUP BY A.FACFCH, A.MPNFAC, M1.MENNIT,M1.MENOMB,A.MATOTF,B.PRCODI,C.PRNOMB,B.MAVATP
ORDER BY  A.FACFCH, A.MPNFAC;

--
 SELECT * FROM HOSVITAL.MAEATE2 WHERE MPNFAC = 503624	 AND PRCODI ='871121';
SELECT * FROM HOSVITAL.MAEEMP WHERE MENNIT='NUEVAEPS';
SELECT  * FROM HOSVITAL.MAEPROV WHERE PRCODI='871121' AND PRCVIG=2019 AND PRCCCOSV  IN ('10413','F0408','M0421','M0318','10403','F0401','F0430','M0425') ;


SELECT  A.FACFCH AS FECHA_FACTURA, A.MPNFAC AS FACTURA, M1.MENNIT AS CONTRATO,M1.MENOMB AS NOMBRE_CONTRATO,A.MATOTF AS TOTAL_FACTURA,B.PRCODI AS CUPS,C.PRNOMB AS NOMBRE_PROC,B.MAVATP AS VALOR_PROC
FROM  HOSVITAL.MAEATE A, 
	 HOSVITAL.MAEATE2 B,
	 HOSVITAL.MAEPRO C,
	 HOSVITAL.MAEESP E,
	 HOSVITAL.MAEEMP M1
WHERE A.FACFCH>= '2018-01-01' AND A.MPNFAC = B.MPNFAC  AND M1.MENNIT =A.MPMENI  AND
           B.PRCODI = C.PRCODI  AND E.MECODE = B.MECOMM AND  B.MECOMM IN ( 514, 440)  AND B.FCPTPOTRN = 'F' AND
	A.MAESTF NOT IN (1,10) 
ORDER BY  A.FACFCH, A.MPNFAC;



 SELECT * FROM HOSVITAL.MAEATE2 WHERE MPNFAC = 503666	;

SELECT A.FACFCH AS FECHA_FACTURA,A.MPNFAC AS FACTURA,M1.MENNIT AS CONTRATO,M1.MENOMB AS NOMBRE_CONTRATO,A.MATOTF AS TOTAL_FACTURA,B.PRCODI AS CUPS,C.PRNOMB AS NOMBRE_PROC,B.MAVATP AS VALOR_PROC FROM HOSVITAL.MAEATE A,HOSVITAL.MAEATE2 B,HOSVITAL.MAEPRO C,HOSVITAL.MAEESP E,HOSVITAL.MAEEMP M1 WHERE A.FACFCH>= '2018-01-01' AND A.FACFCH<='2019-03-31' AND A.MPNFAC=B.MPNFAC AND M1.MENNIT=A.MPMENI AND B.PRCODI=C.PRCODI AND E.MECODE = B.MECOMM AND B.MECOMM IN (514,440) AND B.FCPTPOTRN = 'F' AND A.MAESTF NOT IN (1,10) ORDER BY A.FACFCH,A.MPNFAC
	
