SELECT * FROM HOSVITAL.MOVBAN WHERE  doccod= 'RNA'   AND  MVBNROCMP=6636 ;
SELECT * FROM HOSVITAL.MOVBAN1 WHERE   DOCCOD='RNA' AND MVBNROCMP=6636 ;
SELECT * FROM HOSVITAL.MOVBAN2 WHERE   DOCCOD='RNA' AND MVBNROCMP=6636 ;

SELECT * FROM HOSVITAL.MOVBAN WHERE DOCCOD='RNA' AND MVBNROCMP = 5446;
SELECT * FROM HOSVITAL.MOVBAN1 WHERE DOCCOD='RNA' AND MVBNROCMP = 5446;
SELECT * FROM HOSVITAL.MOVBAN2 WHERE DOCCOD='RNA' AND MVBNROCMP = 5446;

-- Este es el ercero de busqueda 800249241  01/01/2017 SIN RE4GISTRAR

UPDATE HOSVITAL.MOVBAN 
SET MVBDET='N', MVBACT='R', MVESTREC='', mvBSEDDET='001',MVINDANUD=' ',CRITIPOP=''
WHERE  doccod= 'RNA'   AND  MVBNROCMP=5010 ;

UPDATE HOSVITAL.MOVBAN 
SET  PRCVIGTRN=2017
WHERE  doccod= 'RNA'   AND  MVBNROCMP=5010 ;

SELECT  * FROM HOSVITAL.MOVCXC WHERE MCCCNC LIKE ('%RNA%5010%');  -- AND MVCXCNRO=5010;
SELECT  * FROM HOSVITAL.MOVCXC WHERE MCCCNC LIKE ('%RNA%'); 

SELECT * FROM  HOSVITAL.MOVCXC WHERE DOCCOD='RNA' AND MVCXCNRO= 5010;

SELECT * FROM HOSVITAL.RCPCAJ;
SELECT * FROM HOSVITAL.MOVBAN WHERE  doccod= 'RNA'   AND  MVBNROCMP IN (4568,4621,5010,6845);
SELECT * FROM HOSVITAL.MOVBAN1 WHERE  doccod= 'RNA'   AND  MVBNROCMP IN (4568,4621,5010,6845,5227, 5925);
SELECT * FROM HOSVITAL.MOVBAN2  WHERE  doccod= 'RNA'   AND  MVBNROCMP IN (6716);
SELECT * FROM HOSVITAL.MOVBAN WHERE  doccod= 'RNA'   AND PRCVIGTRN=2017;

SELECT * FROM HOSVITAL.MOVCONT3 WHERE DOCCOD='RNA' AND MVCNRO=5010;

 INSERT INTO HOSVITAL.MOVBAN1
 (EMPCOD,DOCCOD,MCDPTO,MVBNROCMP,MVBCSC,MVB1ID,MVB1TRC,MVB1OPE,MVB1EST,MVB1VL1,MVB1VL2, MVB1F1,     MVB1CON,MVB1VL3)

select '01',DOCCOD,MCDPTO,MVBNROCMP,MVBCSC,1,TRCCOD,'','S',MVBVLR,MVBVLR,MVBFCH  ,'',0
from hosvital.movban 
where empcod= '01' and   mcdpto='001' and doccod= 'RNA'  AND  mvbnrocmp   = 5925;

UPDATE HOSVITAL.MOVBAN1
SET  MVB1EST='N',MVB1VL2 = 0, MVB1F2='0001-01-01 00:00:00.00000'
where empcod= '01' and   mcdpto='001' and doccod= 'RNA'  AND  mvbnrocmp   = 5925;

-- Proceso 1 Validar que no haya Detale activo del recibo de caj

SELECT  * FROM HOSVITAL.MOVCXC WHERE MCCCNC LIKE ('%RNA%6716');  

select * FROM HOSVITAL.MOVCXC WHERE mccnumobl='571862';
SELECT  * FROM HOSVITAL.MOVCXC WHERE doccod='FAR' and mvcxcnro=571862;


-- Paso 2 Verificar que exista el recibo RNA de caja

SELECT *   FROM HOSVITAL.MOVBAN WHERE  doccod= 'RNA'   AND  MVBNROCMP IN (4568,4621,5010,6845);



-- Paso 3 verificar qel estado del recibo, y coocar Sin Registrar Y No detallado

SELECT empcod,  doccod, mcdpto,mvbnrocmp, mvbfch, prctescod, mvbdet,mvbact  FROM HOSVITAL.MOVBAN WHERE  doccod= 'RNA'   AND  MVBNROCMP IN (4568,4621,5010,6845);

-- paso 3 . Verificar en la movban1 No hayan registros

SELECT *   FROM HOSVITAL.MOVBAN1 WHERE  doccod= 'RNA'   AND  MVBNROCMP  in   ('4193',
'4313',
'4592',
'4865',
'5018',
'5276',
'5310',
'5339',
'6456');

-- Paso 4,. verificar en la movban2 No hayan registros

SELECT *   FROM HOSVITAL.MOVBAN2 WHERE  doccod= 'RNA'   AND  MVBNROCMP  in    ('5931',
'5963',
'6018');

-- Paso 5.  Arastrar de la movban , verificando estados hacia la movban1


SELECT *   FROM HOSVITAL.MOVBAN WHERE  doccod= 'RNA'   AND  MVBNROCMP  in    ('5931',
'5963',
'6018');


 INSERT INTO HOSVITAL.MOVBAN1
 (EMPCOD,DOCCOD,MCDPTO,MVBNROCMP,MVBCSC,MVB1ID,MVB1TRC,MVB1OPE,MVB1EST,MVB1VL1,MVB1VL2, MVB1F1,     MVB1CON,MVB1VL3)
select '01',DOCCOD,MCDPTO,MVBNROCMP,MVBCSC,1,TRCCOD,'','S',MVBVLR,MVBVLR,MVBFCH  ,'',0
from hosvital.movban 
where empcod= '01' and   mcdpto='001' and doccod= 'RNA'  AND  mvbnrocmp  in    ('3875');

UPDATE HOSVITAL.MOVBAN1
SET  MVB1EST='N',MVB1VL2 = 0, MVB1F2='0001-01-01 00:00:00.00000'
where empcod= '01' and   mcdpto='001' and doccod= 'RNA'  AND  mvbnrocmp  in    ('3875');




-- Paso 6. Verificar por el aplicativo cuentas x cobrar procesos detalle de recibo de caja que se pueda distribuir y detallar

-- Paso7 Comparar las Facturas pendientes a detallar

SELECT  * FROM HOSVITAL.MOVCXC where clicod =;  -- WHERE MCCCNC LIKE ('%RNA%5010%');  

UPDATE HOSVITAL.MOVBAN 
SET MVBDET='D', MVBACT='S'
WHERE  doccod= 'RNA'   AND  MVBNROCMP=671 ;

