select * from hosvital.movcont3 where doccod='FV' AND MVCNRO = 71;
select * from hosvital.movcont2 where doccod='FV' AND MVCNRO = 71 AND MVCNAT ='D';

SELECT * FROM HOSVITAL.MOVCXC WHERE DOCCOD='FV' AND MVCXCNRO=71;

SELECT * FROM HOSVITAL.HOJOBL
WHERE HOJNUMOBL = '2582'  AND EMPCOD='02' AND CNTVIG=2019 AND  HOJNUMOBL IN (select MVCDOCRF1  from hosvital.movcont2 where doccod='FV' AND MVCNRO = 71 AND MVCNAT ='D');


SELECT COUNT(*) FROM HOSVITAL.HOJOBL  -- 104
WHERE EMPCOD='02' AND CNTVIG=2019 AND  HOJNUMOBL IN (select MVCDOCRF1  from hosvital.movcont2 where doccod='FV' AND MVCNRO = 71 AND MVCNAT ='D');

select * from hosvital.movcont2 where doccod='FV' AND MVCNRO = 71 AND MVCNAT ='D' AND MVCDOCRF1 = '2582'
 AND CNTCOD='13050501';


UPDATE HOSVITAL.HOJOBL A
SET A.HOJTOTDEB =  ( SELECT M.MVCVLR
                                       FROM HOSVITAL.MOVCONT2 M
                                      WHERE M.EMPCOD= A.EMPCOD AND M.MVCDOCRF1 = A.HOJNUMOBL AND M.DOCCOD='FV' AND M.MVCNRO=71 AND M.MVCNAT='D' AND M.CNTCOD=A.CNTCOD )
WHERE A.EMPCOD='02'  AND A.CNTVIG=2019 AND A.CNTCOD= '13050501' AND  A.HOJNUMOBL IN (select MVCDOCRF1  from hosvital.movcont2 where doccod='FV' AND MVCNRO = 71 AND MVCNAT ='D' AND CNTCOD='13050501');

