-- 
SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='RC' AND MVCNRO= 1491;

SELECT * FROM HOSVITAL.MOVBAN WHERE DOCCOD='RC' AND MVBNROCMP=1491;
SELECT * FROM HOSVITAL.MOVBAN1 WHERE DOCCOD='RC' AND MVBNROCMP=1491;

SELECT * FROM HOSVITAL.NIMOVCON2 WHERE DOCCOD='RC'  AND NIMCNRO= 1491;  -- ESTABA EN 500000

UPDATE  HOSVITAL.MOVBAN 
SET MVBVLR=0
WHERE DOCCOD='RC' AND MVBNROCMP=1491;

select * from hosvital.movcxc where doccod='RC' AND MVCXCNRO= 1491;

UPDATE HOSVITAL.MOVCONT2
SET  MVCVLRLC= 0.0 , MVCVLR=0.0
 WHERE EMPCOD='02' AND DOCCOD='RC' AND  MVCNRO=1491;

SELECT * FROM HOSVITAL.NIMOVCON2 WHERE DOCCOD='RC'  AND NIMCNRO= 1491;

UPDATE  HOSVITAL.NIMOVCON2 
SET  NIMC2VL=0.0,  NIMC2VLR=0
WHERE DOCCOD='RC'  AND NIMCNRO= 1491

 -- SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='DRC' AND 

SELECT * FROM HOSVITAL.MOVCONT3 WHERE DOCCOD='RC' AND MVCNRO=1409;

SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='RC' AND  MVCNRO=1409;

UPDATE HOSVITAL.MOVCONT2
SET  MVCVLRLC= 0.0 , MVCVLR=0.0
 WHERE EMPCOD='02' AND DOCCOD='RC' AND  MVCNRO=1409;


SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='RCF' AND MVCNRO= 145;
select * from hosvital.movcxc where doccod='RCF';


UPDATE HOSVITAL.MOVCONT2
SET  CNTCOD='11100504'
 WHERE DOCCOD='RCF' AND MVCNRO= 145  AND MVCCSC=1 and cntcod='11200503';

SELECT * FROM HOSVITAL.NIMOVCON2 WHERE DOCCOD='RCF'  AND NIMCNRO= 145;



UPDATE  HOSVITAL.NIMOVCON2 
SET  NICNTCOD='11100504'
WHERE DOCCOD='RCF'  AND NIMCNRO= 144 AND NIMC2CSC = 4;

