SELECT * FROM HOSVITAL.RESMCUE  WHERE RSMANO=2020;

SELECT  R.RSMCTNCON,R.TRCCOD,R.RSMSALANT,R.RSMCRE, R.RSMDEB, R.RSMSALACT
FROM HOSVITAL.RESMCUE R  
WHERE RSMANO=2020
ORDER BY  R.RSMCTNCON, R.TRCCOD;


-- SUMATORIA DEBITOS Y CREDITOS POR TERCERO

SELECT R.RSMCTNCON,R.TRCCOD, SUM(IFNULL(R.RSMCRE,0))  CREDITO,  SUM(IFNULL(R.RSMDEB,0)) DEBITO
FROM HOSVITAL.RESMCUE R  
WHERE R.RSMEMPCOD = '01'   AND R.MCDPTO='001' AND R.RSMANO=2020    AND R.RSMMES <> 13 
GROUP BY R.RSMCTNCON,R.TRCCOD
ORDER BY R.RSMCTNCON,R.TRCCOD;


-- CON EL SALDO ANETRRO

SELECT   R.RSMCTNCON,R.TRCCOD,
SUM(( SELECT SUM(IFNULL(R1.RSMSALANT ,0)) FROM  HOSVITAL.RESMCUE R1 WHERE R1.RSMEMPCOD=R.RSMEMPCOD AND R1.RSMCTNCON=R.RSMCTNCON AND R1.MCDPTO=R.MCDPTO AND R1.TRCCOD=R.TRCCOD AND R1.RSMANO=R.RSMANO  AND R1.RSMMES=1) ) SALDO_ANTERIOR,
SUM((SELECT SUM(IFNULL(R2.RSMDEB,0)) FROM  HOSVITAL.RESMCUE R2 WHERE R2.RSMEMPCOD=R.RSMEMPCOD AND R2.RSMCTNCON=R.RSMCTNCON AND R2.MCDPTO=R.MCDPTO AND R2.TRCCOD=R.TRCCOD AND R2.RSMANO=R.RSMANO   AND R.RSMMES <> 13 )) DEBITOS,
SUM((SELECT SUM(IFNULL(R2.RSMCRE,0)) FROM  HOSVITAL.RESMCUE R2 WHERE R2.RSMEMPCOD=R.RSMEMPCOD AND R2.RSMCTNCON=R.RSMCTNCON AND R2.MCDPTO=R.MCDPTO AND R2.TRCCOD=R.TRCCOD AND R2.RSMANO=R.RSMANO  AND R.RSMMES <> 13 )) CREDITOS,
SUM(( SELECT SUM(IFNULL(R1.RSMSALACT ,0)) FROM  HOSVITAL.RESMCUE R1 WHERE R1.RSMEMPCOD=R.RSMEMPCOD AND R1.RSMCTNCON=R.RSMCTNCON AND R1.MCDPTO=R.MCDPTO AND R1.TRCCOD=R.TRCCOD AND R1.RSMANO=R.RSMANO  AND R1.RSMMES=12)) SALDO_ACTUAL
FROM HOSVITAL.RESMCUE R  
WHERE R.RSMEMPCOD = '01'   AND R.MCDPTO='001' AND RSMANO=2020   -- AND TRCCOD='805026666'
GROUP BY R.RSMCTNCON,R.TRCCOD
ORDER BY  R.RSMCTNCON, R.TRCCOD;



SELECT * FROM HOSVITAL.RESMCUE  WHERE RSMANO=2020 AND TRCCOD='805026666' ORDER BY RSMCTNCON,  RSMMES ;

SELECT  DISTINCT R.RSMCTNCON,R.TRCCOD FROM HOSVITAL.RESMCUE R WHERE R.RSMANO=2020  AND R.TRCCOD= '805026666' ORDER BY R.RSMCTNCON;


--

--Query LOCAL BUENO

SELECT    R.RSMCTNCON,  R.TRCCOD,
MAX(( SELECT SUM(IFNULL(R1.RSMSALANT ,0)) SALDO_ANTERIOR FROM  HOSVITAL.RESMCUE R1 WHERE R1.RSMEMPCOD=R.RSMEMPCOD AND R1.RSMCTNCON=R.RSMCTNCON AND R1.MCDPTO=R.MCDPTO AND R1.TRCCOD=R.TRCCOD AND R1.RSMANO=R.RSMANO  AND R1.RSMMES=1)) SALDO_ANTERIOR ,
MAX((SELECT SUM(IFNULL(R2.RSMDEB,0)) FROM  HOSVITAL.RESMCUE R2 WHERE R2.RSMEMPCOD=R.RSMEMPCOD AND R2.RSMCTNCON=R.RSMCTNCON AND R2.MCDPTO=R.MCDPTO AND R2.TRCCOD=R.TRCCOD AND R2.RSMANO=R.RSMANO   AND R2.RSMMES <> 13 ))  DEBITOS,
MAX((SELECT SUM(IFNULL(R2.RSMCRE,0)) FROM  HOSVITAL.RESMCUE R2 WHERE R2.RSMEMPCOD=R.RSMEMPCOD AND R2.RSMCTNCON=R.RSMCTNCON AND R2.MCDPTO=R.MCDPTO AND R2.TRCCOD=R.TRCCOD AND R2.RSMANO=R.RSMANO  AND R2.RSMMES <> 13 )) CREDITOS,
MAX(( SELECT SUM(IFNULL(R1.RSMSALACT ,0	)) SALDO_ANTERIOR FROM  HOSVITAL.RESMCUE R1 WHERE R1.RSMEMPCOD=R.RSMEMPCOD AND R1.RSMCTNCON=R.RSMCTNCON AND R1.MCDPTO=R.MCDPTO AND R1.TRCCOD=R.TRCCOD AND R1.RSMANO=R.RSMANO  AND R1.RSMMES=12))  SALDO_ACTUAL
FROM HOSVITAL.RESMCUE R  
WHERE R.RSMEMPCOD = '01'   AND R.MCDPTO='001' AND R.RSMANO=2020  AND  R.RSMMES<> 13  -- AND TRCCOD='830025149'    AND R.RSMCTNCON = '61257017'
GROUP BY R.RSMCTNCON,R.TRCCOD
ORDER BY  R.RSMCTNCON, R.TRCCOD;


--Query LOCAL BUENO CON TERCEROS Y CUENTAS

SELECT    R.RSMCTNCON, CTAS.CNTDSC CUENTAS , R.TRCCOD,TER.TRCRAZSOC TERCERO,
MAX(( SELECT SUM(IFNULL(R1.RSMSALANT ,0)) SALDO_ANTERIOR FROM  HOSVITAL.RESMCUE R1 WHERE R1.RSMEMPCOD=R.RSMEMPCOD AND R1.RSMCTNCON=R.RSMCTNCON AND R1.MCDPTO=R.MCDPTO AND R1.TRCCOD=R.TRCCOD AND R1.RSMANO=R.RSMANO  AND R1.RSMMES=1)) SALDO_ANTERIOR ,
MAX((SELECT SUM(IFNULL(R2.RSMDEB,0)) FROM  HOSVITAL.RESMCUE R2 WHERE R2.RSMEMPCOD=R.RSMEMPCOD AND R2.RSMCTNCON=R.RSMCTNCON AND R2.MCDPTO=R.MCDPTO AND R2.TRCCOD=R.TRCCOD AND R2.RSMANO=R.RSMANO   AND R2.RSMMES <> 13 ))  DEBITOS,
MAX((SELECT SUM(IFNULL(R2.RSMCRE,0)) FROM  HOSVITAL.RESMCUE R2 WHERE R2.RSMEMPCOD=R.RSMEMPCOD AND R2.RSMCTNCON=R.RSMCTNCON AND R2.MCDPTO=R.MCDPTO AND R2.TRCCOD=R.TRCCOD AND R2.RSMANO=R.RSMANO  AND R2.RSMMES <> 13 )) CREDITOS,
MAX(( SELECT SUM(IFNULL(R1.RSMSALACT ,0	)) SALDO_ANTERIOR FROM  HOSVITAL.RESMCUE R1 WHERE R1.RSMEMPCOD=R.RSMEMPCOD AND R1.RSMCTNCON=R.RSMCTNCON AND R1.MCDPTO=R.MCDPTO AND R1.TRCCOD=R.TRCCOD AND R1.RSMANO=R.RSMANO  AND R1.RSMMES=12))  SALDO_ACTUAL, CTAS.CNTNAT  NATURALEZA
FROM HOSVITAL.RESMCUE R  
INNER JOIN HOSVITAL.TERCEROS TER ON (TER.TRCCOD= R.TRCCOD)
INNER JOIN HOSVITAL.CUENTAS CTAS ON (CTAS.EMPCOD=R.RSMEMPCOD AND CTAS.CNTCOD=R.RSMCTNCON AND CTAS.CNTVIG=2020)
WHERE R.RSMEMPCOD = '01'   AND R.MCDPTO='001' AND R.RSMANO=2020  AND  R.RSMMES<> 13   -- AND R.TRCCOD='830025149'    AND R.RSMCTNCON = '61257017'
GROUP BY R.RSMCTNCON,CTAS.CNTDSC, R.TRCCOD,TER.TRCRAZSOC,CTAS.CNTNAT
ORDER BY  R.RSMCTNCON, R.TRCCOD;

select * from hosvital.resmcue where rsmano=2020 and TRCCOD='830025149'    AND RSMCTNCON = '61257017';
SELECT * FROM HOSVITAL.TERCEROS;

SELECT R.RSMCTNCON,R.TRCCOD, SUM(IFNULL(R.RSMCRE,0))  CREDITO,  SUM(IFNULL(R.RSMDEB,0)) DEBITO
FROM HOSVITAL.RESMCUE R  
WHERE R.RSMEMPCOD = '01'   AND R.MCDPTO='001' AND R.RSMANO=2020    AND R.RSMMES <> 13   AND TRCCOD='830025149'    AND R.RSMCTNCON = '61257017'
GROUP BY R.RSMCTNCON,R.TRCCOD
ORDER BY R.RSMCTNCON,R.TRCCOD;

SELECT SUM(IFNULL(R.RSMSALANT,0))  anteriror , SUM(IFNULL(R.RSMCRE,0))  CREDITO,  SUM(IFNULL(R.RSMDEB,0)) DEBITO,  SUM(IFNULL(R.RSMSALACT,0))  ACTUAL
FROM HOSVITAL.RESMCUE R  
WHERE R.RSMEMPCOD = '01'   AND R.MCDPTO='001' AND R.RSMANO=2020    AND R.RSMMES <> 13   
;

SELECT * FROM HOSVITAL.CUENTAS;


-- QUERY A NIIF

SELECT  *  FROM HOSVITAL.NIRSMGEN;

SELECT    R.NIRCCUE,CTAS.NICNTDSC CUENTAS ,  R.TRCCOD,TER.TRCRAZSOC TERCERO,
MAX(( SELECT SUM(IFNULL(R1.NIRCGANT ,0)) SALDO_ANTERIOR FROM  HOSVITAL.NIRSMGEN R1 WHERE R1.NIRCEMP=R.NIRCEMP AND R1.NIRCCUE=R.NIRCCUE AND R1.MCDPTO=R.MCDPTO AND R1.TRCCOD=R.TRCCOD AND R1.NIRCANIO=R.NIRCANIO  AND R1.NIRCMES=1)) SALDO_ANTERIOR ,
MAX((SELECT SUM(IFNULL(R2.NIRCGDEB,0)) FROM  HOSVITAL.NIRSMGEN R2 WHERE R2.NIRCEMP=R.NIRCEMP AND R2.NIRCCUE=R.NIRCCUE AND R2.MCDPTO=R.MCDPTO AND R2.TRCCOD=R.TRCCOD AND R2.NIRCANIO=R.NIRCANIO   AND R2.NIRCMES <> 13 ))  DEBITOS,
MAX((SELECT SUM(IFNULL(R2.NIRCGCRE,0)) FROM  HOSVITAL.NIRSMGEN R2 WHERE R2.NIRCEMP=R.NIRCEMP AND R2.NIRCCUE=R.NIRCCUE AND R2.MCDPTO=R.MCDPTO AND R2.TRCCOD=R.TRCCOD AND R2.NIRCANIO=R.NIRCANIO  AND R2.NIRCMES <> 13 )) CREDITOS,
MAX(( SELECT SUM(IFNULL(R1.NIRCGACT ,0	)) SALDO_ANTERIOR FROM  HOSVITAL.NIRSMGEN R1 WHERE R1.NIRCEMP=R.NIRCEMP AND R1.NIRCCUE=R.NIRCCUE AND R1.MCDPTO=R.MCDPTO AND R1.TRCCOD=R.TRCCOD AND R1.NIRCANIO=R.NIRCANIO  AND R1.NIRCMES=12))  SALDO_ACTUAL,CTAS.NICNTNAT
FROM HOSVITAL.NIRSMGEN R  
LEFT JOIN HOSVITAL.TERCEROS TER ON (TER.TRCCOD= R.TRCCOD)
INNER JOIN HOSVITAL.NICUENTAS CTAS ON (CTAS.EMPCOD=R.NIRCEMP AND CTAS.NICNTCOD=R.NIRCCUE AND CTAS.NICNTVIG=2017)
WHERE R.NIRCEMP = '01'   AND R.MCDPTO='001' AND R.NIRCANIO=2017  AND  R.NIRCMES<> 13   AND r.TRCCOD='800130907'    AND R.NIRCCUE = '83953005'
GROUP BY R.NIRCCUE,CTAS.NICNTDSC,r.trccod,TER.TRCRAZSOC,CTAS.NICNTNAT
ORDER BY  R.NIRCCUE, R.TRCCOD;

SELECT * FROM  HOSVITAL.NICUENTAS;

SELECT * FROM HOSVITAL.NIRSMGEN WHERE NIRCEMP ='01'  and trccod='800130907' and nirccue='83953005'   and nircanio=2017;

SELECT SUM(IFNULL(R.NIRCGANT,0))  anteriror , SUM(IFNULL(R.NIRCGCRE,0))  CREDITO,  SUM(IFNULL(R.NIRCGDEB,0)) DEBITO,  SUM(IFNULL(R.NIRCGACT,0))  ACTUAL
FROM HOSVITAL.NIRSMGEN R  
WHERE R.NIRCEMP = '01'   AND R.MCDPTO='001' AND R.NIRCANIO=2017    AND R.NIRCMES <> 13    --  AND TRCCOD='830025149'  
;

select * from hosvital.terceros;
select * from hosvital.proveedor1;

select  ter.trccod codigo_proveedor, ter.trcrazsoc  razon_social,ter.trcnit nit
from hosvital.proveedor1 p
inner join hosvital.terceros  ter on (ter.trccod=p.prvcod)
where  p.empcod='01'
order by ter.trccod;

