SELECT  M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH,M2.MVCMES,CAP.MPTDOC, CAP.MPCEDU, CAP.MPNOMC,MAEEMP.MENNIT, MAEEMP.MENOMB,
MAX((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'C'  AND M2.CNTCOD LIKE ('41%') ))  CREDITOS,
MAX((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'D' )) DEBITOS
FROM HOSVITAL.MOVCONT2 M2
INNER JOIN HOSVITAL.MOVCONT3 M3 ON (M3.EMPCOD=M2.EMPCOD AND M3.DOCCOD=M2.DOCCOD  AND M3.MVCNRO= M2.MVCNRO )
INNER JOIN  HOSVITAL.MAEATE  M ON (M.MATIPDOC IN ('2','5') AND M.MPNFAC=M2.MVCNRO)
INNER JOIN HOSVITAL.CAPBAS CAP ON (CAP.MPTDOC=M.MPTDOC AND CAP.MPCEDU=M.MPCEDU)
INNER JOIN  HOSVITAL.MAEEMP MAEEMP ON (MAEEMP.MENNIT=M.MPMENI)
WHERE  M2.EMPCOD='01' AND M2.MVCANIO=2020 AND M2.DOCCOD='FAR'
GROUP BY M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH,M2.MVCMES,CAP.MPTDOC, CAP.MPCEDU, CAP.MPNOMC,MAEEMP.MENNIT, MAEEMP.MENOMB
ORDER BY M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH;


-- 1ER QUERY
----------------------------------
-------------------------------------


SELECT  M2.DOCCOD TIPO_DOC,M2.MVCNRO  DOCUMENTO,M2.MVCCFCH FECHA,M2.MVCMES MES,M2.CNTCOD  CUENTA,EMPRE.EMPDSC,
(SELECT CAP.MPTDOC
FROM HOSVITAL.MAEATE MAE
INNER JOIN HOSVITAL.CAPBAS CAP  ON (CAP.MPTDOC=MAE.MPTDOC AND CAP.MPCEDU=MAE.MPCEDU )
WHERE MAE.MATIPDOC IN ('2','5') AND MAE.MPNFAC = M2.MVCNRO)
 TIPO_DOC,
(SELECT CAP.MPCEDU
FROM HOSVITAL.MAEATE MAE
INNER JOIN HOSVITAL.CAPBAS CAP  ON (CAP.MPTDOC=MAE.MPTDOC AND CAP.MPCEDU=MAE.MPCEDU )
WHERE MAE.MATIPDOC IN ('2','5') AND MAE.MPNFAC = M2.MVCNRO)
 CEDULA,
(SELECT CAP.MPNOMC
FROM HOSVITAL.MAEATE MAE
INNER JOIN HOSVITAL.CAPBAS CAP  ON (CAP.MPTDOC=MAE.MPTDOC AND CAP.MPCEDU=MAE.MPCEDU )
WHERE MAE.MATIPDOC IN ('2','5') AND MAE.MPNFAC = M2.MVCNRO)
 PACIENTE,
(SELECT MAEEMP.MENNIT
FROM HOSVITAL.MAEATE MAE
INNER JOIN HOSVITAL.MAEEMP MAEEMP  ON (MAEEMP.MENNIT=MAE.MPMENI)
WHERE MAE.MATIPDOC IN ('2','5') AND MAE.MPNFAC = M2.MVCNRO)
 COD_EMPRESA,
(SELECT MAEEMP.MENOMB
FROM HOSVITAL.MAEATE MAE
INNER JOIN HOSVITAL.MAEEMP MAEEMP  ON (MAEEMP.MENNIT=MAE.MPMENI)
WHERE MAE.MATIPDOC IN ('2','5') AND MAE.MPNFAC = M2.MVCNRO)
EMPRESA,
MAX((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'C'  AND M22.CNTCOD  =  M2.CNTCOD ))  CREDITOS,
MAX((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'D'  AND M22.CNTCOD  =  M2.CNTCOD ))  DEBITOS
FROM HOSVITAL.MOVCONT2 M2
INNER JOIN HOSVITAL.MOVCONT3 M3 ON (M3.EMPCOD=M2.EMPCOD AND M3.DOCCOD=M2.DOCCOD  AND M3.MVCNRO= M2.MVCNRO )
INNER JOIN HOSVITAL.MAEATE MAE ON (MAE. MPNFAC = M2.MVCNRO)
INNER JOIN HOSVITAL.MAEEMP EMP ON (EMP.MENNIT=MAE.MPMENI)
INNER JOIN HOSVITAL.EMPRESS EMPRE ON (EMPRE.MECNTR= EMP.MECNTR)
WHERE  M2.EMPCOD='01' AND M2.MVCANIO=2020 AND M2.DOCCOD='FAR' AND M2.CNTCOD LIKE ('41%')
GROUP BY M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH,M2.MVCMES, M2.CNTCOD,EMPRE.EMPDSC
ORDER BY M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH, M2.CNTCOD,EMPRE.EMPDSC;

SELECT * FROM HOSVITAL.EMPRESS;
SELECT * FROM HOSVITAL.MAEEMP;
-----------------------
-- 
--------------------------
----------------------------
SELECT * FROM HOSVITAL.MOVCONT2;;


SELECT  M2.DOCCOD TIPO_DOC,M2.MVCNRO  DOCUMENTO,M2.MVCCFCH FECHA,M2.MVCMES MES,M2.CNTCOD  CUENTA,EMPRE.EMPDSC,
MAX((SELECT CAP.MPTDOC
FROM HOSVITAL.MAEATE MAE
INNER JOIN HOSVITAL.CAPBAS CAP  ON (CAP.MPTDOC=MAE.MPTDOC AND CAP.MPCEDU=MAE.MPCEDU )
WHERE MAE.MATIPDOC IN ('2','5') AND MAE.MPNFAC = M2.MVCDOCRF1))
 TIPO_DOC,
MAX((SELECT CAP.MPCEDU
FROM HOSVITAL.MAEATE MAE
INNER JOIN HOSVITAL.CAPBAS CAP  ON (CAP.MPTDOC=MAE.MPTDOC AND CAP.MPCEDU=MAE.MPCEDU )
WHERE MAE.MATIPDOC IN ('2','5') AND MAE.MPNFAC =  M2.MVCDOCRF1))
 CEDULA,
MAX((SELECT CAP.MPNOMC
FROM HOSVITAL.MAEATE MAE
INNER JOIN HOSVITAL.CAPBAS CAP  ON (CAP.MPTDOC=MAE.MPTDOC AND CAP.MPCEDU=MAE.MPCEDU )
WHERE MAE.MATIPDOC IN ('2','5') AND MAE.MPNFAC =  M2.MVCDOCRF1))
 PACIENTE,
MAX((SELECT MAEEMP.MENNIT
FROM HOSVITAL.MAEATE MAE
INNER JOIN HOSVITAL.MAEEMP MAEEMP  ON (MAEEMP.MENNIT=MAE.MPMENI)
WHERE MAE.MATIPDOC IN ('2','5') AND MAE.MPNFAC =  M2.MVCDOCRF1))
 COD_EMPRESA,
MAX((SELECT MAEEMP.MENOMB
FROM HOSVITAL.MAEATE MAE
INNER JOIN HOSVITAL.MAEEMP MAEEMP  ON (MAEEMP.MENNIT=MAE.MPMENI)
WHERE MAE.MATIPDOC IN ('2','5') AND MAE.MPNFAC =  M2.MVCDOCRF1))
EMPRESA,
MAX((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'C'  AND M22.CNTCOD  =  M2.CNTCOD ))  CREDITOS,
MAX((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'D'  AND M22.CNTCOD  =  M2.CNTCOD ))  DEBITOS
FROM HOSVITAL.MOVCONT2 M2
INNER JOIN HOSVITAL.MOVCONT3 M3 ON (M3.EMPCOD=M2.EMPCOD AND M3.DOCCOD=M2.DOCCOD  AND M3.MVCNRO= M2.MVCNRO )
INNER JOIN HOSVITAL.MAEATE MAE ON (MAE. MPNFAC = M2.MVCDOCRF1)
INNER JOIN HOSVITAL.MAEEMP EMP ON (EMP.MENNIT=MAE.MPMENI)
INNER JOIN HOSVITAL.EMPRESS EMPRE ON (EMPRE.MECNTR= EMP.MECNTR)
WHERE  M2.EMPCOD='01' AND M2.MVCANIO=2020 AND M2.DOCCOD IN ('NCR') AND M2.CNTCOD LIKE ('41%') AND  M2.MVCDOCRF1  <> ''
GROUP BY M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH,M2.MVCMES, M2.CNTCOD,EMPRE.EMPDSC
ORDER BY M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH, M2.CNTCOD,EMPRE.EMPDSC;

SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='NCR' AND MVCNRO IN (18755,18756,18757,18758);

SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD IN ('NCF','NGR')  AND MVCANIO=2020 AND MVCDOCRF1 ='';


SELECT * FROM HOSVITAL.MAEATE WHERE MPNFAC IN (630759         	,628612         );
SELECT * FROM HOSVITAL.CAPBAS WHERE MPCEDU IN ( '19411469','5892774') ;

-----------------------
-------- TERCER QUERY
-----------------------------
SELECT  * FROM HOSVITAL.DOCUCON;

SELECT  M2.DOCCOD TIPO_DOC,DOC.DOCDSC,M2.MVCNRO  DOCUMENTO,M2.MVCCFCH FECHA,M2.MVCMES MES,M2.CNTCOD  CUENTA,T.TRCRAZSOC AS TERCERO,
MAX((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'C'  AND M22.CNTCOD  =  M2.CNTCOD AND   M22.TRCCOD= M2.TRCCOD ))  CREDITOS,
MAX((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'D'  AND M22.CNTCOD  =  M2.CNTCOD  AND M22.TRCCOD=M2.TRCCOD ))  DEBITOS
FROM HOSVITAL.MOVCONT2 M2
INNER JOIN HOSVITAL.MOVCONT3 M3 ON (M3.EMPCOD=M2.EMPCOD AND M3.DOCCOD=M2.DOCCOD  AND M3.MVCNRO= M2.MVCNRO )
INNER JOIN HOSVITAL.DOCUCON DOC ON (DOC.DOCCOD=M2.DOCCOD)
INNER JOIN HOSVITAL.TERCEROS T ON (T.TRCCOD=M2.TRCCOD)
WHERE  M2.EMPCOD='01' AND M2.MVCANIO=2020 AND M2.DOCCOD   IN ('ACP','CCA','CIA','ISI','NCR','NGR','RSD') AND M2.CNTCOD LIKE ('41%')
GROUP BY M2.DOCCOD,DOC.DOCDSC,M2.MVCNRO,M2.MVCCFCH,M2.MVCMES, M2.CNTCOD,T.TRCRAZSOC
ORDER BY M2.DOCCOD,DOC.DOCDSC,M2.MVCNRO,M2.MVCCFCH,M2.MVCMES, M2.CNTCOD, T.TRCRAZSOC;
