SELECT  * FROM HOSVITAL.MAEATE
WHERE MAESTF IN ('0','4') AND MPMENI = '290' AND CAST(MPNFAC AS VARCHAR(10)) IN (SELECT H.HOJNUMOBL  FROM HOSVITAL.HOJOBL H WHERE H.HOJTOTDEB = H.HOJTOTCRE);


SELECT  M.MPNFAC, M.FACFCH,M.MAESTF, H1.HOJVLROBL,H1.HOJTOTDEB,H1.HOJTOTCRE ,H1.CNTVIG,H1.CNTCOD,  (H1.HOJTOTDEB - H1.HOJTOTCRE) AS SALDO
 FROM HOSVITAL.MAEATE M
INNER JOIN HOSVITAL.HOJOBL H1 ON  (H1.HOJNUMOBL = CAST(M.MPNFAC AS VARCHAR(10)))
WHERE M.MAESTF IN ('0','4') AND M.MPMENI = 'CS0101' AND CAST(M.MPNFAC AS VARCHAR(10)) IN (SELECT H.HOJNUMOBL  FROM HOSVITAL.HOJOBL H WHERE H.HOJTOTDEB = H.HOJTOTCRE);

SELECT * FROM HOSVITAL.HOJOBL;

SELECT * FROM HOSVITAL.MOVCXC WHERE MCCNUMOBL= '599481';

SELECT HOJNUMOBL, CNTVIG,CNTCOD,HOJFCHOBL,HOJTOTDEB,HOJTOTCRE, (HOJTOTDEB - HOJTOTCRE) SALDO
 FROM HOSVITAL.HOJOBL WHERE HOJNUMOBL = '599481';

SELECT * FROM HOSVITAL.DOCUCON WHERE DOCCOD IN ('FAR','FAD','RSD');


SELECT * FROM HOSVITAL.MOVCXC WHERE MCCNUMOBL= '598125';

SELECT HOJNUMOBL, CNTVIG,CNTCOD,HOJFCHOBL,HOJTOTDEB,HOJTOTCRE, (HOJTOTDEB - HOJTOTCRE) SALDO
 FROM HOSVITAL.HOJOBL WHERE HOJNUMOBL = '598125';

-- Veamos una factura con reclasificacion qu este bien

SELECT * FROM  HOSVITAL.HOJOBL
WHERE CNTVIG =  2019 AND CNTCOD= '13999001' AND  HOJTOTDEB - HOJTOTCRE=0;




SELECT * FROM HOSVITAL.MOVCXC WHERE MCCNUMOBL= '457258';


