select * from hosvital.movcont2 where empcod='02' and cntvig=2021 and mvcdocrf1 ='CSC-4541';  --trccod=51729539       ,,500001.00 ,, 2021-06-08	
	
	


select * from hosvital.hojobl where hojnumobl  in ('CSC-4541','CSC-4540');

insert into hosvital.hojobl (EMPCOD,HOJNUMOBL,CLICOD,CNTVIG,CNTCOD,MCDPTO,DOCCOD,MENNIT,CNUCOD,CNUSUB,HOJFCHOBL,HOJVLRCUO,HOJCUOINI,HOJVLROBL,HOJTOTCRE,HOJTOTDEB,HOJTIPPAG,HOJTPPGDS,HOJNUMCUO,HOJNROREM,HOJFCHREM,HOJNRORAD,
HOJFCHRAD,HOJTIPGLO,HOJSTAGLO,HFCHRECGL,HJFCHRADGL,HJFCANOBL,HOJVLRGLO,HOINDDEV,HONORADG,HOJMATIPD,HOJNROCAS,HOJCARRCH,CONTIP,CONCOD,HOJFCHRCH,HOJUSRRCH,HOJINDFAC,HOJDOCRES,HOJNOMRES,HOJAPERES,HOJCNSING,HOJESTHOM,
HOJINDREC,HOJPRF,HOJFCHRAR,HOJNUMRAR,HOJUSUINF,HOJFCHINF,HOJINDINF,HOJOBLCLU,HOJOBLCLF)
select EMPCOD,'CSC-4541','51729539',CNTVIG,CNTCOD,MCDPTO,DOCCOD,MENNIT,CNUCOD,CNUSUB,HOJFCHOBL,HOJVLRCUO,HOJCUOINI,500001,0,500001,HOJTIPPAG,HOJTPPGDS,HOJNUMCUO,HOJNROREM,HOJFCHREM,HOJNRORAD,
HOJFCHRAD,HOJTIPGLO,HOJSTAGLO,HFCHRECGL,HJFCHRADGL,'0001-01-01',HOJVLRGLO,HOINDDEV,HONORADG,HOJMATIPD,HOJNROCAS,HOJCARRCH,CONTIP,CONCOD,HOJFCHRCH,HOJUSRRCH,HOJINDFAC,HOJDOCRES,HOJNOMRES,HOJAPERES,HOJCNSING,HOJESTHOM,
HOJINDREC,HOJPRF,HOJFCHRAR,HOJNUMRAR,HOJUSUINF,HOJFCHINF,HOJINDINF,HOJOBLCLU,HOJOBLCLF
from hosvital.hojobl
 where hojnumobl = 'CSC-4540';

update hosvital.hojobl
set hojnumobl ='CSC-4541'
where  hojnumobl = 'CSC-4540' and empcod='02' and hojvlrobl=500001;

