/*
2- Informe en excel  de documentos causados del 01/01/2020 al 31/12/2020 en excel  llamados: CA, que contenga la siguiente información así:

VALOR BRUTO- IVA- RETEFUENTE-RETEICA- VALOR PAGADO- CONCEPTO DE COMPRA O SERVICIO
*/

SELECT * FROM HOSVITAL.MOVCONT2 WHERE  CNTVIG=2021 AND DOCCOD='CA';

SELECT  M3.DOCCOD,M3.MVCNRO NUMERO,M3.MVCCPT DETALLE_GLOBAL, M3.MVCFCH FECHA, M2.CNTCOD CUENTA, T.TRCCOD TERCERO, T.TRCRAZSOC TERCERO_NOMBRE,M2.MVCBSE BASE, M2.MVCIMPCOD TIPO_IMPUESTO,M2.MVCVLRLC VALOR, M2.MVCNAT TIPO_MOPIMIENTO ,M2.MVCDET DETALLE
FROM HOSVITAL.MOVCONT3 M3
INNER JOIN HOSVITAL.MOVCONT2 M2  ON (M2.EMPCOD=M3.EMPCOD AND M2.DOCCOD=M3.DOCCOD AND M2.MVCNRO=M3.MVCNRO)
INNER JOIN HOSVITAL.TERCEROS T ON (T.TRCCOD = M2.TRCCOD)
WHERE M3.EMPCOD='01' AND M3.MVCFCH >= '2020-01-01 00:00:00' AND M3.MVCFCH <= '2020-12-31 00:00:00' AND M3.DOCCOD='CA'
ORDER BY M3.MVCFCH;