SELECT  * FROM HOSVITAL.MOVCONT2  WHERE MVCANIO=2020 AND MVCMES=2 AND DOCCOD='HON' AND MVCNRO=17051;
SELECT  * FROM HOSVITAL.NIMOVCON2  WHERE  DOCCOD='HON' AND NIMCNRO=17051;

create table hosvital.nimovcon2_hon17051 as (select * fROM HOSVITAL.NIMOVCON2  WHERE  DOCCOD='HON' AND NIMCNRO=17051) with data;

select * from hosvital.nimovcon2_hon17051;

update HOSVITAL.NIMOVCON2 
set nimc2vl=0, nimc2vlr=0
WHERE  DOCCOD='HON' AND NIMCNRO=17051;

select * from hosvital.nimovcon2_hon17051;

SELECT  * FROM HOSVITAL.MOVCONT2 WHERE MVCANIO=2020 AND MVCMES=12 AND  (DOCCOD,MVCNRO,MVCVLR);

SELECT  * FROM HOSVITAL.MOVCONT2  WHERE MVCANIO=2020 AND MVCMES=2 AND DOCCOD='HON' AND MVCNRO=17051;

SELECT M1.DOCCOD,M1.MVCNRO,M2.DOCCOD,M2.NIMCNRO,M1.MVCVLR, M2.NIMC2VLR
FROM HOSVITAL.MOVCONT2 M1
INNER JOIN HOSVITAL.NIMOVCON2 M2 ON (M2.DOCCOD=M1.DOCCOD AND M2.NIMCNRO = M1.MVCNRO AND M2.NIMC2CSC   =M1.MVCCSC)
WHERE M1.DOCCOD='HON' AND M1.MVCNRO =17051 AND M1.DOCCOD=M2.DOCCOD AND M1.MVCNRO = M2.NIMCNRO;


SELECT M1.DOCCOD,M1.MVCNRO,M2.DOCCOD,M2.NIMCNRO,M1.MVCVLR, M2.NIMC2VLR
FROM HOSVITAL.MOVCONT2 M1
INNER JOIN HOSVITAL.NIMOVCON2 M2 ON (M2.DOCCOD=M1.DOCCOD AND M2.NIMCNRO = M1.MVCNRO AND M2.NIMC2CSC   =M1.MVCCSC)
WHERE M1.MVCANIO=2020 AND  M1.MVCMES = 2 AND M1.MVCANIO=M2.NIMC2ANIO AND M1.MVCMES = M2.NIMC2MES AND
M1.DOCCOD='HON' AND M1.MVCNRO =17121 AND M1.DOCCOD=M2.DOCCOD AND M1.MVCNRO = M2.NIMCNRO;



SELECT M1.DOCCOD,M1.MVCNRO,M2.DOCCOD,M2.NIMCNRO,M1.MVCVLR, M2.NIMC2VLR
FROM HOSVITAL.MOVCONT2 M1
INNER JOIN HOSVITAL.NIMOVCON2 M2 ON (M2.DOCCOD=M1.DOCCOD AND M2.NIMCNRO = M1.MVCNRO AND M2.NIMC2VLR  =M1.MVCVLR)
WHERE M1.MVCANIO=2020 AND  M1.MVCMES = 2 AND M1.MVCANIO=M2.NIMC2ANIO AND M1.MVCMES = M2.NIMC2MES 
  AND M1.DOCCOD=M2.DOCCOD AND M1.MVCNRO = M2.NIMCNRO AND M1.MVCVLR !=  M2.NIMC2VLR;



SELECT *
FROM HOSVITAL.MOVCONT2 M1
WHERE M1.MVCANIO=2020 AND  M1.MVCMES = 2 AND M1.DOCCOD='CE' AND M1.MVCNRO =55 AND (M1.DOCCOD,M1.MVCNRO,M1.MVCVLR) NOT IN (SELECT M2.DOCCOD,M2.NIMCNRO,M2.NIMC2VLR
										FROM HOSVITAL.NIMOVCON2 M2
										WHERE  M2.NIMC2ANIO=2020 AND  M2.NIMC2MES =2);


SELECT * FROM  HOSVITAL.MOVCONT2 WHERE DOCCOD='CE' AND MVCNRO=55;

SELECT M1.DOCCOD,M1.MVCNRO,M1.MVCVLR
FROM HOSVITAL.MOVCONT2 M1
INNER JOIN HOSVITAL.DOCUCON  D ON (D.DOCCOD=M1.DOCCOD AND D.DOCNI='A')
WHERE M1.EMPCOD= '01'  AND M1.DOCCOD != 'DEP'  AND M1.MVCANIO=2020 AND  M1.MVCMES = 2 AND (M1.DOCCOD,M1.MVCNRO,M1.MVCVLR) NOT IN (SELECT M2.DOCCOD,M2.NIMCNRO,M2.NIMC2VLR
										FROM HOSVITAL.NIMOVCON2 M2
										WHERE M2.EMPCOD='01' AND  M2.NIMC2ANIO=2020 AND  M2.NIMC2MES =2);



-- Actualziacion Docuemnto

SELECT  * FROM HOSVITAL.MOVCONT2  WHERE MVCANIO=2020 AND MVCMES=2 AND DOCCOD='HON' AND MVCNRO=17051;
SELECT  * FROM HOSVITAL.NIMOVCON2  WHERE  DOCCOD='HON' AND NIMCNRO=17051;

SELECT * FROM HOSVITAL.RSMAUX WHERE RSMANO=2020 AND RSMMES=2;
SELECT * FROM HOSVITAL.NIRSMAUX; --  WHERE RSMANO=2020 AND RSMMES=2;

SELECT R1.RSMCTNCON,R1.RSAXDEB,R1.RSAXCRE, N1.NIRCCUE,N1.NIRCADEB,N1.NIRCACRE
 FROM HOSVITAL.RSMAUX R1
INNER JOIN HOSVITAL.NIRSMAUX N1 ON (N1.NIRCEMP='01' AND N1.NIRCANIO=R1.RSMANO AND N1.NIRCMES=R1.RSMMES AND N1.NIRCCUE=R1.RSMCTNCON)
WHERE R1.RSMEMPCOD='01' AND R1. RSMANO=2020 AND R1. RSMMES=2
ORDER BY R1.RSMCTNCON ;


--  DIFERENTES

SELECT R1.RSMCTNCON,R1.RSAXDEB,R1.RSAXCRE, N1.NIRCCUE,N1.NIRCADEB,N1.NIRCACRE
 FROM HOSVITAL.RSMAUX R1
INNER JOIN HOSVITAL.NIRSMAUX N1 ON (N1.NIRCEMP='01' AND N1.NIRCANIO=R1.RSMANO AND N1.NIRCMES=R1.RSMMES AND N1.NIRCCUE=R1.RSMCTNCON)
WHERE R1.RSMEMPCOD='01' AND R1. RSMANO=2020 AND R1. RSMMES=2 AND (R1.RSAXDEB<> N1.NIRCADEB OR R1.RSAXCRE<> N1.NIRCACRE)
ORDER BY R1.RSMCTNCON ;


SELECT R1.RSMCTNCON,R1.RSAXDEB,R1.RSAXCRE, N1.NIRCCUE,N1.NIRCADEB,N1.NIRCACRE
 FROM HOSVITAL.RSMAUX R1
INNER JOIN HOSVITAL.NIRSMAUX N1 ON (N1.NIRCEMP='01' AND N1.NIRCANIO=R1.RSMANO AND N1.NIRCMES=R1.RSMMES AND N1.NIRCCUE=R1.RSMCTNCON)
WHERE R1.RSMEMPCOD='01' AND R1. RSMANO=2020 AND R1. RSMMES=1 AND (R1.RSAXDEB<> N1.NIRCADEB OR R1.RSAXCRE<> N1.NIRCACRE)
ORDER BY R1.RSMCTNCON ;


select * from hosvital.nimovcon1;

select nicntcod,
sum(case when nimc2nat='D' then nimc2vlr else 0 end) as Debito, sum(case when nimc2nat='C' then nimc2vlr else 0 end) as Credito,
( sum(case when nimc2nat='D' then nimc2vlr else 0 end)  -  sum(case when nimc2nat='C' then nimc2vlr else 0 end) ) as Dif
from  hosvital.nimovcon2
where  empcod='01' and nimc2anio=2020 and nimc2mes=2
group by  nicntcod
order by  nicntcod;



select sum(case when y.nimc2nat='D' then y.nimc2vlr else 0 end) as Debito, sum(case when y.nimc2nat='C' then y.nimc2vlr else 0 end) as Credito
from  hosvital.nimovcon2 y
where  y.empcod='01' and y.nimc2anio=2020 and y.nimc2mes=2 and (y.empcod, y.doccod,y.nimcnro) not in (select x.empcod,x.doccod,x.nimcnro from  hosvital.nimovcon1 x  where x.empcod =y.empcod and x.doccod = y.doccod and x.nimcnro = y.nimcnro and  x.nimc1est = 'N');

