-- Primera Consulta OK

SELECT NIRCCUE, NIRCANIO,NIRCMES,NIRCGDEB,NIRCGCRE, (NIRCGDEB - NIRCGCRE) SALDO  FROM HOSVITAL.NIRSMGEN WHERE NIRCEMP='01' AND NIRCCUE in  ('53050501','53050501');
SELECT * FROM HOSVITAL.NIRSMAUX   WHERE NIRCEMP='01' AND NIRCANIO=2019 AND NIRCMES=1 AND NIRCCUE LIKE ('4105%') ORDER BY NIRCCUE, NIRCMES;

SELECT *  FROM HOSVITAL.NIRSMGEN WHERE NIRCEMP='01' AND NIRCCUE in  ('53050501', '53050503','53050504','53050505') and trccod  in  ('860034594') and nircanio=2019;

--select n.nicntcod,n.nicntvig
select *
FROM HOSVITAL.NICUENTAS   N, HOSVITAL.NIRSMGEN GEN, HOSVITAL.TERCEROS TER
WHERE N.EMPCOD='01' AND N.NICNTVIG=2019 AND  N.NICNTCOD IN ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')
 AND N.EMPCOD = GEN.NIRCEMP AND  N.NICNTCOD=SUBSTRING( GEN.NIRCCUE ,1,8) AND GEN.NIRCANIO=2019 AND
                GEN.TRCCOD=TER.TRCCOD and ter.trccod= '860034594'
ORDER BY N.NICNTCOD, TER.TRCRAZSOC;




SELECT * FROM HOSVITAL.NICUENTAS;


SELECT N.NICNTCOD,   N.NICNTDSC AS CONCEPTO,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1) as Enero,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 ) as Por_Enero,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=2) as Febrero,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=2) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 ), 0) as Por_Febrero,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=3) as Marzo,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=3) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 ), 0) as Por_Marzo,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=4) as Abril,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=4) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 ), 0) as Por_Abril,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=5) as Mayo,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=5) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5), 0) as Por_Mayo,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=6) as Junio,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=6) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 ), 0) as Por_Junio,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=7) as Julio,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=7) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 ), 0) as Por_Julio,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=8) as Agosto,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=8) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=8), 0) as Por_Agosto,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=9) as Septiembre,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=9) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 ), 9) as Por_Septiembre,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=10) as Octubre,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=10) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 ), 0) as Por_Octubre,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=11) as Noviembre,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=11) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 ), 0) as Por_Noviembre,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=12) as Diciembre ,
ROUND((SELECT SUM(X.NIRCADEB - X.NIRCACRE)
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=12) *100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE x.nircemp =  N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,4)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 ), 0) as Por_Diciembe,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE) 
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4)  = N.NICNTCOD AND X.NIRCANIO = 2019  ) TOTAL,
(SELECT SUM(X.NIRCADEB - X.NIRCACRE) 
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4) = N.NICNTCOD AND X.NIRCANIO = 2019 )*100.00/
(SELECT case when SUM(X.NIRCADEB - X.NIRCACRE)  = 0 then '1' else  SUM(X.NIRCADEB - X.NIRCACRE)  end
 FROM HOSVITAL.NIRSMAUX  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,4)  IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130') AND X.NIRCANIO = 2019 ) TotalPorcentaje

FROM HOSVITAL.NICUENTAS   N
WHERE N.EMPCOD='01' AND N.NICNTVIG=2019 AND  N.NICNTCOD IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130')
ORDER BY N.NICNTCOD;



SELECT * FROM HOSVITAL.NICUENTAS WHERE NICNTVIG = 2019 AND NICNTCOD IN ( '4105','4110','4115','4116','4117','4118','4120','4125','4130') ;

-- Segunda Consulta

SELECT * FROM   HOSVITAL.NIRSMGEN WHERE NIRCANIO=2019 AND NIRCCUE LIKE('510510%') ORDER BY TRCCOD;


SELECT DISTINCT N.NICNTCOD, GEN.TRCCOD,TER.TRCRAZSOC,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD) as Enero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 )  as Por_Enero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD) as Febrero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 )  as Por_febrero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD) as Marzo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 )  as Por_marzo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD) as Abril,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 )  as Por_Abril,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD) as Mayo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 )  as Por_Mayo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD) as Junio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 )  as Por_Junio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD) as Julio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 )  as Por_Julio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD) as Agosto,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 )  as Por_Agosto,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD) as Septiembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 )  as Por_Septiembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD) as Octubre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 )  as Por_Octubre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD) as Noviembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 )  as Por_Noviembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD) as Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 )  as Por_Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD) as Total,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019  ) as TotalPorcentaje
FROM HOSVITAL.NICUENTAS   N, HOSVITAL.NIRSMGEN GEN, HOSVITAL.TERCEROS TER
WHERE N.EMPCOD='01' AND N.NICNTVIG=2019 AND  N.NICNTCOD IN ( '510510') AND N.EMPCOD = GEN.NIRCEMP AND  N.NICNTCOD=SUBSTRING( GEN.NIRCCUE ,1,6) AND GEN.NIRCANIO=2019 AND
                GEN.TRCCOD=TER.TRCCOD
ORDER BY N.NICNTCOD, TER.TRCRAZSOC;

------------------------------
-- Tercer Query
----------------------------------

SELECT NIRCCUE, TRCCOD, NIRCGCRE, NIRCGDEB FROM   HOSVITAL.NIRSMGEN WHERE NIRCANIO=2019 AND SUBSTRING(NIRCCUE,1,6)  = '610510'  AND NIRCMES=1 ORDER BY TRCCOD;

SELECT DISTINCT N.NICNTCOD, GEN.TRCCOD,TER.TRCRAZSOC,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD) as Enero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 )  as Por_Enero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD) as Febrero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010') AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 )  as Por_febrero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD) as Marzo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010') AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 )  as Por_marzo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD) as Abril,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 )  as Por_Abril,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD) as Mayo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010') AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 )  as Por_Mayo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD) as Junio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010') AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 )  as Por_Junio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD) as Julio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010') AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 )  as Por_Julio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD) as Agosto,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010') AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 )  as Por_Agosto,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD) as Septiembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010') AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 )  as Por_Septiembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD) as Octubre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010') AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 )  as Por_Octubre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD) as Noviembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010') AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 )  as Por_Noviembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD) as Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,6)  IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010') AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 )  as Por_Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD) as Total,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,6) = N.NICNTCOD AND X.NIRCANIO = 2019 ) as TotalPorcentaje
FROM HOSVITAL.NICUENTAS   N, HOSVITAL.NIRSMGEN GEN, HOSVITAL.TERCEROS TER
WHERE N.EMPCOD='01' AND N.NICNTVIG=2019 AND  N.NICNTCOD IN ( '610510','611010','611510','611610','611710','611810','612010','612510','613010')
 AND N.EMPCOD = GEN.NIRCEMP AND  N.NICNTCOD=SUBSTRING( GEN.NIRCCUE ,1,6) AND GEN.NIRCANIO=2019 AND
                GEN.TRCCOD=TER.TRCCOD
ORDER BY N.NICNTCOD,TER.TRCRAZSOC;


-- Para el cuarto Query

SELECT * FROM HOSVITAL.NIRSMGEN WHERE  NIRCANIO = 2019 AND NIRCMES = 1 AND  NIRCCUE  IN ('53050501','53050502','53050503','53050504','53050505','53050507','53050508') AND TRCCOD= '860034594';
SELECT * FROM HOSVITAL.NIRSMGEN WHERE  NIRCANIO = 2019 AND NIRCMES = 1 AND  NIRCCUE  IN ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')  ORDER BY NIRCCUE,TRCCOD;




SELECT DISTINCT N.NICNTCOD, GEN.TRCCOD,TER.TRCRAZSOC,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD) as Enero,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 )  as Por_Enero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD) as Febrero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 )  as Por_febrero,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD) as Marzo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 )  as Por_marzo,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD) as Abril,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 )  as Por_Abril,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD) as Mayo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)    in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 )  as Por_Mayo,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD) as Junio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508') AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 )  as Por_Junio,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD) as Julio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508') AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 )  as Por_Julio,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD) as Agosto,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)    in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 )  as Por_Agosto,


(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD) as Septiembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)    in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 )  as Por_Septiembre,


(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD    AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD) as Octubre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD    AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 )  as Por_Octubre,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD) as Noviembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 )  as Por_Noviembre,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD) as Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 )  as Por_Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD) as Total,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD) *100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   in  ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')   AND X.NIRCANIO = 2019  ) as TotalPorcentaje
FROM HOSVITAL.NICUENTAS   N, HOSVITAL.NIRSMGEN GEN, HOSVITAL.TERCEROS TER
WHERE N.EMPCOD='01' AND N.NICNTVIG=2019 AND N.EMPCOD = GEN.NIRCEMP AND  N.NICNTCOD=SUBSTRING( GEN.NIRCCUE ,1,8) AND GEN.NIRCANIO=2019 AND
                GEN.TRCCOD=TER.TRCCOD AND  N.NICNTCOD IN ('53050501','53050502','53050503','53050504','53050505','53050507','53050508')
ORDER BY N.NICNTCOD, TER.TRCRAZSOC;


-- CASO quinto query. Falta  Marzo - Abril, Mayo y Junio NO FUNCIONANA



SELECT DISTINCT N.NICNTCOD, GEN.TRCCOD,TER.TRCRAZSOC,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD) as Enero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN ('53200501') AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 )  as Por_Enero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD) as Febrero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN ('53200501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 )  as Por_febrero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD) as Marzo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8) IN ('53200501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 )  as Por_marzo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD) as Abril,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN ('53200501')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 )  as Por_Abril,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD) as Mayo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN ('53200501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 )  as Por_Mayo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD) as Junio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN ('53200501') AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 )  as Por_Junio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD) as Julio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8) IN ('53200501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 )  as Por_Julio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD) as Agosto,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)    IN ('53200501')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 )  as Por_Agosto,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD) as Septiembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)    IN ('53200501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 )  as Por_Septiembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD    AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD) as Octubre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD    AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN ('53200501')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 )  as Por_Octubre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD) as Noviembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN ('53200501')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 )  as Por_Noviembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD) as Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN ('53200501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 )  as Por_Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD) as Total,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD) *100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  IN ('53200501')   AND X.NIRCANIO = 2019  ) as TotalPorcentaje
FROM HOSVITAL.NICUENTAS   N, HOSVITAL.NIRSMGEN GEN, HOSVITAL.TERCEROS TER
WHERE N.EMPCOD='01' AND N.NICNTVIG=2019 AND N.EMPCOD = GEN.NIRCEMP AND  N.NICNTCOD=SUBSTRING( GEN.NIRCCUE ,1,8) AND GEN.NIRCANIO=2019 AND
                GEN.TRCCOD=TER.TRCCOD AND  N.NICNTCOD IN ('53200501')
ORDER BY N.NICNTCOD, TER.TRCRAZSOC;


-- CASO sexto Solo queda este caso para el REPORT*



SELECT DISTINCT N.NICNTCOD, GEN.TRCCOD,TER.TRCRAZSOC,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD) as Enero,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN  ('53150502','53950501')AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 )  as Por_Enero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD) as Febrero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN  ('53150502','53950501') AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 )  as Por_febrero,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD) as Marzo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8) IN  ('53150502','53950501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 )  as Por_marzo,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD) as Abril,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN  ('53150502','53950501')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 )  as Por_Abril,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD) as Mayo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN  ('53150502','53950501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 )  as Por_Mayo,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD) as Junio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN  ('53150502','53950501') AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 )  as Por_Junio,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD) as Julio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8) IN  ('53150502','53950501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 )  as Por_Julio,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD) as Agosto,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)    IN  ('53150502','53950501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 )  as Por_Agosto,


(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD) as Septiembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)    IN  ('53150502','53950501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 )  as Por_Septiembre,


(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD    AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD) as Octubre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD    AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN  ('53150502','53950501')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 )  as Por_Octubre,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD) as Noviembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN  ('53150502','53950501')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 )  as Por_Noviembre,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD) as Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN  ('53150502','53950501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 )  as Por_Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD) as Total,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD) *100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  IN ('53150502','53950501')   AND X.NIRCANIO = 2019  ) as TotalPorcentaje
FROM HOSVITAL.NICUENTAS   N, HOSVITAL.NIRSMGEN GEN, HOSVITAL.TERCEROS TER
WHERE N.EMPCOD='01' AND N.NICNTVIG=2019 AND N.EMPCOD = GEN.NIRCEMP AND  N.NICNTCOD=SUBSTRING( GEN.NIRCCUE ,1,8) AND GEN.NIRCANIO=2019 AND
                GEN.TRCCOD=TER.TRCCOD AND  N.NICNTCOD IN ('53150502','53950501')
ORDER BY N.NICNTCOD, TER.TRCRAZSOC;



-- Caso septimo


SELECT DISTINCT N.NICNTCOD, GEN.TRCCOD,TER.TRCRAZSOC,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD) as Enero,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8) = N.NICNTCOD AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN  ('23352001','23352501') AND X.NIRCANIO = 2019 AND  X.NIRCMES=1 )  as Por_Enero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD) as Febrero,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=N.EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN ('23352001','23352501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=2 )  as Por_febrero,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD) as Marzo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8) IN ('23352001','23352501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=3 )  as Por_marzo,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD) as Abril,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN  ('23352001','23352501')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=4 )  as Por_Abril,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD) as Mayo,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN  ('23352001','23352501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=5 )  as Por_Mayo,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD) as Junio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN  ('23352001','23352501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=6 )  as Por_Junio,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD) as Julio,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8) IN  ('23352001','23352501') AND X.NIRCANIO = 2019 AND  X.NIRCMES=7 )  as Por_Julio,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD) as Agosto,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)    IN  ('23352001','23352501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=8 )  as Por_Agosto,


(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD) as Septiembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)    IN ('23352001','23352501') AND X.NIRCANIO = 2019 AND  X.NIRCMES=9 )  as Por_Septiembre,


(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD    AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD) as Octubre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD    AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)  IN ('23352001','23352501')   AND X.NIRCANIO = 2019 AND  X.NIRCMES=10 )  as Por_Octubre,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD) as Noviembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN  ('23352001','23352501')  AND X.NIRCANIO = 2019 AND  X.NIRCMES=11 )  as Por_Noviembre,

(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD) as Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD  AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 and x.trccod=GEN.TRCCOD)*100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND  SUBSTRING(X.NIRCCUE,1,8)   IN  ('23352001','23352501') AND X.NIRCANIO = 2019 AND  X.NIRCMES=12 )  as Por_Diciembre,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)   = N.NICNTCOD  AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD) as Total,
(SELECT SUM(X.NIRCGDEB - X.NIRCGCRE)
 FROM HOSVITAL.NIRSMGEN  X
 WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  = N.NICNTCOD   AND X.NIRCANIO = 2019  and x.trccod=GEN.TRCCOD) *100.00/
(SELECT case when SUM(X.NIRCGDEB  - X.NIRCGCRE)  = 0 then '1' else  SUM(X.NIRCGDEB - X.NIRCGCRE)  end
 FROM HOSVITAL.NIRSMGEN  X
WHERE X.NIRCEMP=EMPCOD AND SUBSTRING(X.NIRCCUE,1,8)  IN ('53150502','53950501')   AND X.NIRCANIO = 2019  ) as TotalPorcentaje
FROM HOSVITAL.NICUENTAS   N, HOSVITAL.NIRSMGEN GEN, HOSVITAL.TERCEROS TER
WHERE N.EMPCOD='01' AND N.NICNTVIG=2019 AND N.EMPCOD = GEN.NIRCEMP AND  N.NICNTCOD=SUBSTRING( GEN.NIRCCUE ,1,8) AND GEN.NIRCANIO=2019 AND
                GEN.TRCCOD=TER.TRCCOD AND  N.NICNTCOD IN ('23352001','23352501','23353001','23353002','23354501','23357001','2365','2367','23700501','23701001','23701501','23702001','23702501','23704501','23706001','23809002')
ORDER BY N.NICNTCOD, TER.TRCRAZSOC;
