SELECT COUNT(*) FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='PCP' AND MVCNRO=2333 ; -- 912	

SELECT COUNT(*) FROM HOSVITAL.NIMOVCON2 WHERE DOCCOD='PCP' AND NIMCNRO=2333 ; -- 912

/*

Saludos Cordiales,
*/

SELECT COUNT(*) FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='PCP' AND MVCNRO=2333  AND TRCCOD= '1053339754';
SELECT COUNT(*) FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='PCP' AND MVCNRO=2333  AND TRCCOD= '53161656';

SELECT MVCNAT, SUM(MVCVLR)
FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='PCP' AND MVCNRO=2333
GROUP BY MVCNAT;

SELECT MVCNAT, SUM(MVCVLR)
FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='PCP' AND MVCNRO=2333 AND TRCCOD NOT IN ( '1053339754','53161656')
GROUP BY MVCNAT;

--  por valor $77.256.595.

SELECT nimc2nat, SUM(nimc2vl)
FROM HOSVITAL.nimovcon2 WHERE DOCCOD='PCP' AND nimcnro=2333 AND TRCCOD NOT IN ( '1053339754','53161656')
GROUP BY nimc2nat;



SELECT *
FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='PCP' AND MVCNRO=2333 AND TRCCOD  IN ( '1053339754','53161656');

DELETE FROM  HOSVITAL.MOVCONT2 WHERE empcod='01' and DOCCOD='PCP' AND MVCNRO=2333 AND TRCCOD  IN ( '1053339754','53161656') AND MVCCSC IN (25,359	,481	,815	);


CREATE TABLE hosvital.COP_MOVCONT2_TERC AS (SELECT  * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='PCP' AND MVCNRO=2333 ) with data;
CREATE TABLE hosvital.COP_nimovcon2_TERC AS (SELECT  * FROM HOSVITAL.nimovcon2 WHERE DOCCOD='PCP' AND nimcnro=2333 ) with data;
select * from hosvital.COP_MOVCONT2_TERC;


SELECT *
FROM HOSVITAL.nimovcon2 WHERE DOCCOD='PCP' AND nimcnro=2333 AND TRCCOD  IN ( '1053339754','53161656');


DELETE FROM  HOSVITAL.nimovcon2 WHERE empcod='01' and DOCCOD='PCP' AND nimcnro=2333 AND TRCCOD  IN ( '1053339754','53161656') AND nimc2csc IN (25,359	,481	,815	);


SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='CEG' AND MVCNRO=33842 ; -- 912  ESTABA EN 807756.00

UPDATE  	HOSVITAL.MOVCONT2  SET MVCVLRLC=0,  MVCVLR = 0  WHERE DOCCOD='CEG' AND MVCNRO=33842 AND MVCCSC=1;

SELECT * FROM HOSVITAL.nimovcon2 WHERE DOCCOD='CEG' and nicntvig=2020 ; -- AND nimcnro=33842 ; -- 912	



SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='ACH' AND MVCNRO=1414 ; -- 912  -- ESTABA EN 807756.00	


UPDATE  	HOSVITAL.MOVCONT2  SET MVCVLRLC=0,  MVCVLR = 0  WHERE DOCCOD='ACH' AND MVCNRO=1414 AND MVCCSC=1;


SELECT COUNT(*) FROM HOSVITAL.NIMOVCON2 WHERE DOCCOD='PCP' AND NIMCNRO=2333 ; -- 912

-- Esto suble lo de LOCAL


insert into  HOSVITAL.MOVCONT2 
select EMPCOD,DOCCOD,MVCNRO,MCDPTO,2,CNTVIG,CNTCOD,CNUCOD,CNUSUB,CNCCOD,CNTSUB,TRCCOD,MVCDOCRF1,MVCDOCRF2,MVCDOCRF3,'D',MVCVLRLC,MVCVLREX,MVCDET,MVCBSE,MVCVLR,
MVCIMPCOD,MVCCFCH,MVCSEDORG,MVCMES,MVCANIO,MVCCMPAJ,MVCDOCRF4,MVCDOCRF5,MOVCNTPRF,MVCNROAUD,MVCFCHAUD,MVCIDETRD,MVCGASDED
FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='CEG' AND MVCNRO=33842 and mvccsc=1 ;


insert into  HOSVITAL.MOVCONT2 
select EMPCOD,DOCCOD,MVCNRO,MCDPTO,2,CNTVIG,CNTCOD,CNUCOD,CNUSUB,CNCCOD,CNTSUB,TRCCOD,MVCDOCRF1,MVCDOCRF2,MVCDOCRF3,'D',MVCVLRLC,MVCVLREX,MVCDET,MVCBSE,MVCVLR,
MVCIMPCOD,MVCCFCH,MVCSEDORG,MVCMES,MVCANIO,MVCCMPAJ,MVCDOCRF4,MVCDOCRF5,MOVCNTPRF,MVCNROAUD,MVCFCHAUD,MVCIDETRD,MVCGASDED
FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='ACH' AND MVCNRO=1414  and mvccsc=1 ;




-- Esto sube lo de NIIF
insert into  hosvital.nimovcon2
select EMPCOD,DOCCOD,MVCNRO,MCDPTO,MVCCSC,CNTVIG,CNTCOD,CNUCOD,CNUSUB,CNCCOD,CNTSUB,TRCCOD,MVCDOCRF1,MVCDOCRF2,
MVCDOCRF3,MVCNAT,MVCVLRLC,MVCVLREX,MVCDET,MVCBSE,MVCVLR,MVCIMPCOD,MVCCFCH   ,MVCANIO,        MVCMES,          MVCSEDORG,MVCCMPAJ,
MVCDOCRF4,' ', MOVCNTPRF
from  hosvital.movcont2 
where EMPCOD='01' AND doccod='CEG' and mvcnro in  (33842)        ;  




