SELECT HOSVITAL.HOJOBLPRV.PRVCOD AS ID_PROVEEDOR, HOSVITAL.TERCEROS.TRCRAZSOC AS NOMBRE_PROVEEDOR, HOSVITAL.HOJOBLPRV.HOPNOOBL AS FACTURA, HOSVITAL.HOJOBLPRV.CNTCOD AS CUENTA, HOSVITAL.CUENTAS.CNTDSC AS NOMBRE_CUENTA, HOSVITAL.HOJOBLPRV.HOPFCHOBL AS FECHA_OBL, HOSVITAL.HOJOBLPRV.HOPFCHRAD AS FECHA_RAD, HOSVITAL.HOJOBLPRV.HOPTPPZ AS PLAZO, HOSVITAL.HOJOBLPRV.HOPVLROBL AS VLR_OBL, HOSVITAL.HOJOBLPRV.HOPTOTCRE AS VLR_CREDITOS, HOSVITAL.HOJOBLPRV.HOPTOTDEB AS VLR_DEBITOS, (HOSVITAL.HOJOBLPRV.HOPTOTCRE - HOSVITAL.HOJOBLPRV.HOPTOTDEB) AS SALDO, HOSVITAL.HOJOBLPRV.HOJFCHCAN AS FECHA_CAN, HOSVITAL.HOJOBLPRV.HOJNROOC AS NRO_OC 
FROM (HOSVITAL.HOJOBLPRV 
INNER JOIN HOSVITAL.CUENTAS ON (HOSVITAL.HOJOBLPRV.CNTCOD = HOSVITAL.CUENTAS.CNTCOD) AND (HOSVITAL.HOJOBLPRV.EMPCOD = HOSVITAL.CUENTAS.EMPCOD))
 INNER JOIN HOSVITAL.TERCEROS ON HOSVITAL.HOJOBLPRV.PRVCOD = HOSVITAL.TERCEROS.TRCCOD 
WHERE (HOSVITAL.HOJOBLPRV.CNTVIG=2021 AND ((HOSVITAL.HOJOBLPRV.EMPCOD)='01')) 
GROUP BY HOSVITAL.HOJOBLPRV.PRVCOD, HOSVITAL.TERCEROS.TRCRAZSOC, HOSVITAL.HOJOBLPRV.HOPNOOBL, HOSVITAL.HOJOBLPRV.CNTCOD, HOSVITAL.CUENTAS.CNTDSC, HOSVITAL.HOJOBLPRV.HOPFCHOBL, HOSVITAL.HOJOBLPRV.HOPFCHRAD, HOSVITAL.HOJOBLPRV.HOPTPPZ, HOSVITAL.HOJOBLPRV.HOPVLROBL, HOSVITAL.HOJOBLPRV.HOPTOTCRE, HOSVITAL.HOJOBLPRV.HOPTOTDEB, (HOSVITAL.HOJOBLPRV.HOPTOTCRE - HOSVITAL.HOJOBLPRV.HOPTOTDEB), HOSVITAL.HOJOBLPRV.HOJFCHCAN, HOSVITAL.HOJOBLPRV.HOJNROOC;

/*
Al igual que el informe que se tiene de cuentas por pagar se requiere un informa de cuentas por cobrar con las siguientes especificaciones:
NIT – Nombre Deudor – Fecha de la Obligación – Saldo Final
Para el grupo de cuentas:

 1330, 1355,1370,1380

*/

select * from hosvital.hojobl where hojnumobl='639707';
select * from hosvital.cuentas where substring(cntcod,1,4)  in  ('1330','1355','1370','1380');

select h.clicod codigo, t.trcrazsoc tercero, h.hojnumobl obligacion,h.cntcod cuenta,c.cntdsc nombre, h.hojfchobl fecha_obligacion, h.hojfchrad fecha_radicacion, h.hojvlrobl valor, h.hojtotcre creditos, h.hojtotdeb debitos ,(h.hojtotdeb - h.hojtotcre) saldo, h.hjfcanobl as fecha_cancelacion
from hosvital.hojobl h
inner join hosvital.cuentas c on (c.cntvig=2021 and c.cntcod=h.cntcod)
inner join hosvital.terceros t on (t.trccod= h.clicod)
where h.cntvig=2021 and h.empcod='01' and substring(h.cntcod,1,4)  in  ('1330','1355','1370','1380')
order by h.hojfchobl ,h.hojnumobl ;