SELECT * FROM HOSVITAL.MOVCONT2 WHERE  MVCDOCRF1='620130' AND SUBSTRING(CNTCOD,1,2) = '13';

SELECT MVCNAT, SUM(MVCVLR) 
 FROM HOSVITAL.MOVCONT2 WHERE  MVCDOCRF1='620130' AND SUBSTRING(CNTCOD,1,2) = '13'
GROUP BY MVCNAT;

SELECT * FROM HOSVITAL.HOJOBL WHERE HOJNUMOBL='262109';

SELECT M2.MVCDOCRF1,
CASE WHEN M2.MVCNAT='C' THEN -M2.MVCVLR  WHEN M2.MVCNAT='D' THEN M2.MVCVLR  END MOVIMIENTO,
(
SELECT  (H.HOJTOTDEB - H.HOJTOTCRE)  FROM HOSVITAL.HOJOBL  H
 WHERE CNTVIG=2021 AND H.HOJNUMOBL = CAST(M2.MVCNRO AS VARCHAR(10))) SALDOHOJOBL
FROM HOSVITAL.MOVCONT2 M2
WHERE MVCDOCRF1='262109' AND SUBSTRING(M2.CNTCOD,1,2) = '13'
GROUP BY MVCDOCRF1, MVCVLR;



SELECT M2.MVCDOCRF1,
(SELECT SUM(M3.MVCVLR) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.MVCDOCRF1=M2.MVCDOCRF1 AND M3.MVCNAT='C' AND  SUBSTRING(M3.CNTCOD,1,2) = '13') CREDITOS,
(SELECT SUM(M3.MVCVLR) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.MVCDOCRF1=M2.MVCDOCRF1 AND M3.MVCNAT='C' AND  SUBSTRING(M3.CNTCOD,1,2) = '13') DEBITOS
FROM HOSVITAL.MOVCONT2 M2
WHERE M2.MVCDOCRF1='262109' AND SUBSTRING(M2.CNTCOD,1,2) = '13'
GROUP BY MVCDOCRF1;


SELECT M2.MVCDOCRF1,
(SELECT SUM(M3.MVCVLR) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.CNTVIG <= 2020 AND  M3.MVCDOCRF1=M2.MVCDOCRF1 AND   M3.MVCDOCRF3= 'FAR'  AND M3.MVCNAT='C'  AND SUBSTRING(M3.CNTCOD,1,2) = '13') CREDITOS_M2,
(SELECT SUM(M3.MVCVLR) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.CNTVIG <= 2020 AND   M3.MVCDOCRF1=M2.MVCDOCRF1 AND   M3.MVCDOCRF3= 'FAR'  AND M3.MVCNAT='C'  AND SUBSTRING(M3.CNTCOD,1,2) = '13') DEBITOS_M2,
SUM((SELECT SUM(H.HOJTOTDEB) FROM HOSVITAL.HOJOBL H WHERE H.CNTVIG=2021 AND H.HOJNUMOBL =    CAST(M2.MVCNRO AS VARCHAR(10)))) DEBITOS_HOJOBL,
SUM((SELECT SUM(H.HOJTOTCRE) FROM HOSVITAL.HOJOBL H WHERE H.CNTVIG=2021 AND H.HOJNUMOBL =    CAST(M2.MVCNRO AS VARCHAR(10)))) CREDITOS_HOJOBL
FROM HOSVITAL.MOVCONT2 M2
WHERE  M2.CNTVIG <= 2020 AND  M2.MVCDOCRF1 IN ('262109','563592') AND SUBSTRING(M2.CNTCOD,1,2) = '13' AND M2.MVCDOCRF3='FAR'
GROUP BY MVCDOCRF1;


SELECT * FROM HOSVITAL.HOJOBL WHERE HOJNUMOBL IN ('262109');


SELECT * FROM HOSVITAL.MOVCONT2 WHERE  MVCDOCRF1='620130' AND SUBSTRING(CNTCOD,1,2) = '13';


-- SI HAY DIFERENCIA EN LA MOVCONT2 YL HA  DIDF EN LA HOJOBL TAMBIEN , PERO ESTAS DIFERECIAS SON DIFERENTES DEBE MOSTRAR


--  QUERY GLOBAL


SELECT M2.MVCDOCRF1,
(SELECT SUM(M3.MVCVLR) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.CNTVIG <= 2020 AND  M3.MVCDOCRF1=M2.MVCDOCRF1 AND   M3.MVCDOCRF3= 'FAR'  AND M3.MVCNAT='C'  AND SUBSTRING(M3.CNTCOD,1,2) = '13') CREDITOS_M2,
(SELECT SUM(M3.MVCVLR) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.CNTVIG <= 2020 AND   M3.MVCDOCRF1=M2.MVCDOCRF1 AND   M3.MVCDOCRF3= 'FAR'  AND M3.MVCNAT='D'  AND SUBSTRING(M3.CNTCOD,1,2) = '13') DEBITOS_M2,
SUM((SELECT SUM(H.HOJTOTDEB) FROM HOSVITAL.HOJOBL H WHERE H.CNTVIG=2021 AND H.HOJNUMOBL =    M2.MVCDOCRF1)) DEBITOS_HOJOBL,
SUM((SELECT SUM(H.HOJTOTCRE) FROM HOSVITAL.HOJOBL H WHERE H.CNTVIG=2021 AND H.HOJNUMOBL =    M2.MVCDOCRF1)) CREDITOS_HOJOBL
FROM HOSVITAL.MOVCONT2 M2
WHERE  M2.CNTVIG= 2020 AND  SUBSTRING(M2.CNTCOD,1,2) = '13' AND M2.MVCDOCRF3='FAR' AND M2.MVCDOCRF1='620130'
GROUP BY MVCDOCRF1;


--  QUERY GLOBAL  CON VALIDACION MOV MOVCONT2 WN VIGENCI 2021
SELECT * FROM HOSVITAL.HOJOBL WHERE HOJNUMOBL IN ('620130');

SELECT M2.MVCDOCRF1,
(SELECT SUM(M3.MVCVLR) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.CNTVIG <= 2020 AND  M3.MVCDOCRF1=M2.MVCDOCRF1 AND   M3.MVCDOCRF3= 'FAR'  AND M3.MVCNAT='C'  AND SUBSTRING(M3.CNTCOD,1,2) = '13') CREDITOS_M2,
(SELECT SUM(M3.MVCVLR) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.CNTVIG <= 2020 AND   M3.MVCDOCRF1=M2.MVCDOCRF1 AND   M3.MVCDOCRF3= 'FAR'  AND M3.MVCNAT='D'  AND SUBSTRING(M3.CNTCOD,1,2) = '13') DEBITOS_M2,
SUM((SELECT SUM(H.HOJTOTDEB) FROM HOSVITAL.HOJOBL H WHERE H.CNTVIG =2021 AND H.HOJNUMOBL =    M2.MVCDOCRF1)) DEBITOS_HOJOBL,
SUM((SELECT SUM(H.HOJTOTCRE) FROM HOSVITAL.HOJOBL H WHERE H.CNTVIG =2021 AND H.HOJNUMOBL =    M2.MVCDOCRF1)) CREDITOS_HOJOBL
FROM HOSVITAL.MOVCONT2 M2
WHERE  M2.CNTVIG= 2020 AND  M2.DOCCOD='FAR' AND SUBSTRING(M2.CNTCOD,1,2) = '13' AND M2.MVCDOCRF3='FAR' AND M2.MVCDOCRF1='620130' AND (M2.MVCDOCRF1) NOT IN (SELECT M4.MVCDOCRF1 
									FROM HOSVITAL.MOVCONT2 M4 WHERE M4.CNTVIG=2021 AND M4.MVCDOCRF1=M2.MVCDOCRF1)
GROUP BY MVCDOCRF1;



-- QUERY GLOBAL FILTROS :
-- SI HAY DIFERENCIA EN LA MOVCONT2 YL HA  DIDF EN LA HOJOBL TAMBIEN , PERO ESTAS DIFERECIAS SON DIFERENTES DEBE MOSTRAR




SELECT M2.MVCDOCRF1,
(SELECT SUM(M3.MVCVLR) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.CNTVIG <= 2020 AND  M3.MVCDOCRF1=M2.MVCDOCRF1 AND   M3.MVCDOCRF3= 'FAR'  AND M3.MVCNAT='C'  AND SUBSTRING(M3.CNTCOD,1,2) = '13') CREDITOS_M2,
(SELECT SUM(M3.MVCVLR) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.CNTVIG <= 2020 AND   M3.MVCDOCRF1=M2.MVCDOCRF1 AND   M3.MVCDOCRF3= 'FAR'  AND M3.MVCNAT='D'  AND SUBSTRING(M3.CNTCOD,1,2) = '13') DEBITOS_M2,
SUM((SELECT SUM(H.HOJTOTDEB) FROM HOSVITAL.HOJOBL H WHERE H.CNTVIG=2021 AND H.HOJNUMOBL =    CAST(M2.MVCNRO AS VARCHAR(10)))) DEBITOS_HOJOBL,
SUM((SELECT SUM(H.HOJTOTCRE) FROM HOSVITAL.HOJOBL H WHERE H.CNTVIG=2021 AND H.HOJNUMOBL =    CAST(M2.MVCNRO AS VARCHAR(10)))) CREDITOS_HOJOBL
FROM HOSVITAL.MOVCONT2 M2
WHERE  M2.CNTVIG= 2020 AND  M2.DOCCOD='FAR' AND  SUBSTRING(M2.CNTCOD,1,2) = '13' AND M2.MVCDOCRF3='FAR'  AND (M2.MVCDOCRF1) NOT IN (SELECT M4.MVCDOCRF1 
									FROM HOSVITAL.MOVCONT2 M4 WHERE M4.CNTVIG=2021 AND M4.MVCDOCRF1=M2.MVCDOCRF1)  
GROUP BY MVCDOCRF1
HAVING
			(
			(SELECT IFNULL(SUM(M3.MVCVLR),0) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.CNTVIG <= 2020 AND  M3.MVCDOCRF1=M2.MVCDOCRF1 AND   M3.MVCDOCRF3= 'FAR'  AND M3.MVCNAT='D'  AND SUBSTRING(M3.CNTCOD,1,2) = '13')
                                                                                   - 
			(SELECT IFNULL(SUM(M3.MVCVLR),0) FROM HOSVITAL.MOVCONT2 M3 WHERE M3.CNTVIG <= 2020 AND   M3.MVCDOCRF1=M2.MVCDOCRF1 AND   M3.MVCDOCRF3= 'FAR'  AND M3.MVCNAT='C'  AND SUBSTRING(M3.CNTCOD,1,2) = '13')
			 )
			!=
			(
			(SELECT IFNULL(SUM(H.HOJTOTDEB),0) FROM HOSVITAL.HOJOBL H WHERE H.CNTVIG=2021 AND H.HOJNUMOBL =   M2.MVCDOCRF1 ) 
			)
			-
			(
			(SELECT IFNULL(SUM(H.HOJTOTCRE),0) FROM HOSVITAL.HOJOBL H WHERE H.CNTVIG=2021 AND H.HOJNUMOBL =    M2.MVCDOCRF1)
			);



select * from hosvital.hojobl h	
where h.empcod='01' and h.hojvlrobl = h.hojtotdeb and h.hojtotdeb = h.hojtotcre and h.cntvig=2020 and (h.hojnumobl, h.cntcod)   in (select  h1.hojnumobl, h1.cntcod  from hosvital.hojobl h1 where h1.empcod='01' and h1.cntvig=2021 and h1.hojnumobl=h.hojnumobl and h1.cntcod=h.cntcod and h1.hojtotdeb <> h1.hojtotcre and h1.hojtotdeb <> h1.hojvlrobl);

select *  from hosvital.hojobl where hojnumobl='503896'  ; -- ,'644788';

select * from hosvital.hojobl h	
where h.empcod='01' and h.hojvlrobl = h.hojtotdeb and h.hojtotdeb = h.hojtotcre and h.cntvig=2020 and (h.hojnumobl, h.cntcod)   in (select  h1.hojnumobl, h1.cntcod  from hosvital.hojobl h1 where h1.empcod='01' and h1.cntvig=2021 and h1.hojnumobl=h.hojnumobl and h1.cntcod=h.cntcod and (h1.hojtotdeb <> h1.hojvlrobl or  h1.hojtotcre <> h1.hojvlrobl));

