	

select * from hosvital.movcont2 where empcod='01'and doccod='IEA';

SELECT * FROM HOSVITAL.DOCUCON WHERE DOCCOD='IEA';

SELECT * FROM HOSVITAL.ENTRALM WHERE DOCCOD='IEA';

SELECT * FROM HOSVITAL.ENTRALM1 WHERE DOCCOD='IEA';

SELECT E.DOCCOD,E.ENTANRO DOCUMENTO ,E.ENTAFCH FECHA,  E.PRVCOD,TER.TRCRAZSOC PROVEEDOR ,E1.MSRESO AS COD_MED, M.MSNOMG AS MEDICAMNETO,E1.ENTACNT AS CANTIDAD,
E1.ENTAVLRU AS VALOR_UNITARIO, E1.ENTAVLRI AS IVA, E1.ENTATTAL AS TOTAL, E1.ENTATOTI AS TOTAL_IVA
FROM HOSVITAL.ENTRALM E
INNER JOIN HOSVITAL.ENTRALM1 E1 ON (E1.DOCCOD= E.DOCCOD AND E1.ENTANRO=E.ENTANRO)
INNER JOIN HOSVITAL.TERCEROS TER ON (TER.TRCCOD=E.PRVCOD)
INNER JOIN HOSVITAL.MAESUM1 M ON (M.MSRESO=E1.MSRESO)
WHERE  E.ENTAFCH>= '2019-01-01 00:00:00' AND  E.ENTAFCH<= '2019-12-31 23:59:59' AND E.DOCCOD='IEA'
ORDER BY E.ENTAFCH, E.ENTANRO;

SELECT * FROM HOSVITAL.MOVCONT2 WHERE EMPCOD='01' AND DOCCOD='IEA' AND MVCANIO=2019 ORDER BY MVCCFCH;;
