SELECT * FROM HOSVITAL.MOVCONT2 WHERE  MVCNRO=646905 AND DOCCOD='FAR';
SELECT * FROM HOSVITAL.MOVCONT3;


SELECT  M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH,M2.MVCMES,
SUM((SELECT   SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO  AND M22.MVCNAT = 'D'))
 DEBITOS,
SUM((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'C'))
CREDITOS
FROM HOSVITAL.MOVCONT2 M2
INNER JOIN HOSVITAL.MOVCONT3 M3 ON (M3.EMPCOD=M2.EMPCOD AND M3.DOCCOD=M2.DOCCOD  AND M3.MVCNRO= M2.MVCNRO AND M3.MVCEST <> 'N')
WHERE  M2.EMPCOD='01' AND M2.MVCANIO=2020 AND M2.DOCCOD='FAR' AND M2.CNTCOD LIKE ('41%')
GROUP BY M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH,M2.MVCMES
ORDER BY M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH;

-- FINAL

SELECT * FROM HOSVITAL.MAEEMP;

SELECT * FROM HOSVITAL.MAEATE;
SELECT * FROM HOSVITAL.MOVCONT2 WHERE  MVCNRO=646905 AND DOCCOD='FAR';


SELECT  M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH,M2.MVCMES,CAP.MPTDOC, CAP.MPCEDU, CAP.MPNOMC,MAEEMP.MENNIT, MAEEMP.MENOMB,
MAX((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'C'  AND M2.CNTCOD LIKE ('41%') ))  CREDITOS,
MAX((SELECT  SUM(M22.MVCVLR) END FROM HOSVITAL.MOVCONT2 M22  WHERE M22.EMPCOD=M2.EMPCOD  AND M22.DOCCOD=M2.DOCCOD AND M22.MVCNRO=M2.MVCNRO AND M22.MVCNAT = 'D' )) DEBITOS
FROM HOSVITAL.MOVCONT2 M2
INNER JOIN HOSVITAL.MOVCONT3 M3 ON (M3.EMPCOD=M2.EMPCOD AND M3.DOCCOD=M2.DOCCOD  AND M3.MVCNRO= M2.MVCNRO )
INNER JOIN  HOSVITAL.MAEATE  M ON (M.MATIPDOC IN ('2','5') AND M.MPNFAC=M2.MVCNRO)
INNER JOIN HOSVITAL.CAPBAS CAP ON (CAP.MPTDOC=M.MPTDOC AND CAP.MPCEDU=M.MPCEDU)
INNER JOIN  HOSVITAL.MAEEMP MAEEMP ON (MAEEMP.MENNIT=M.MPMENI)
WHERE  M2.EMPCOD='01' AND M2.MVCANIO=2020 AND M2.DOCCOD='FAR' 
GROUP BY M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH,M2.MVCMES,CAP.MPTDOC, CAP.MPCEDU, CAP.MPNOMC,MAEEMP.MENNIT, MAEEMP.MENOMB
ORDER BY M2.DOCCOD,M2.MVCNRO,M2.MVCCFCH;