select * from hosvital.MOVCONT2;


select * from hosvital.movcont3 
where EMPCOD='02' AND  DOCCOD='CA' AND MVCFCH >= '2020-12-31 00:00:00';
--36100501

select * from hosvital.movcont2
where EMPCOD='02'   and MVCANIO=2020 AND mvcmes>=12 and DOCCOD='CA'   AND MVCNRO >=136 AND CNTCOD='36100501';

SELECT * FROM HOSVITAL.RSMAUX WHERE RSMEMPCOD='02' AND RSMANO=2020 AND RSMMES>=12 AND RSMCTNCON='36100501' ;
-- CN
--TRB
delete     from hosvital.tmprep;

SELECT * FROM HOSVITAL.NIMOVCON1 WHERE EMPCOD='02' AND  DOCCOD='TRB' ; --   AND NIMCNRO >=136  ;
SELECT * FROM HOSVITAL.NIMOVCON1 WHERE EMPCOD='02' AND  DOCCOD='TRB' AND NIMCNRO = 3;
SELECT * FROM HOSVITAL.NIMOVCON2 WHERE EMPCOD='02' AND  DOCCOD='TRB' AND NIMCNRO = 3;

UPDATE  HOSVITAL.NIMOVCON1
SET NIMC1MA='N', NIMC1MG='N'
 WHERE EMPCOD='02' AND  DOCCOD='TRB' AND NIMCNRO = 3;


SELECT * FROM HOSVITAL.NIMOVCON1 WHERE EMPCOD='02' AND  DOCCOD='CN' ; --   AND NIMCNRO >=136  ;
SELECT * FROM HOSVITAL.NIMOVCON1 WHERE EMPCOD='02' AND  DOCCOD='CN' AND NIMCNRO = 38;


SELECT * FROM HOSVITAL.NIMOVCON2 WHERE EMPCOD='02' AND  DOCCOD='CN' AND NIMCNRO = 38 ORDER BY NICNTCOD ;
SELECT * FROM HOSVITAL.NIMOVCON2 WHERE EMPCOD='02' AND  DOCCOD='CN' AND NIMCNRO = 38 AND NICNTCOD='59050501';

SELECT * FROM HOSVITAL.NIRSMAUX WHERE NIRCEMP='02' AND NIRCANIO=2020 AND NIRCCUE='59050501';