SELECT * FROM HOSVITAL.MOVCONT3 WHERE DOCCOD='CEF' AND MVCNRO=86;

UP
SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='CEF' AND MVCNRO=86;  -- ESTABA EN 84900.00	

 SELECT * FROM HOSVITAL.MOVCONT2 WHERE DOCCOD='CEF' AND MVCNRO=86;  
SELECT * FROM HOSVITAL.NIMOVCON2 WHERE DOCCOD='CEF' AND NIMCNRO=86;  


SELECT * FROM HOSVITAL.MOVBAN WHERE DOCCOD='CEF' AND MVBNROCMP = 86;

SELECT * FROM HOSVITAL.MOVCXP WHERE  DOCCOD='CEF' AND  MVCXPNRO=86;

UPDATE  HOSVITAL.MOVCXP
SET MVCXPVAL=0
 WHERE   EMPCOD= '03' AND  DOCCOD='CEF' AND  MVCXPNRO=86 AND MVCXPVAL=84900 ;


SELECT * FROM HOSVITAL.HOJOBLPRV WHERE PRVCOD ='860010451' AND EMPCOD='03';

UPDATE HOSVITAL.MOVCONT2
SET MVCVLRLC=0, MVCVLR=0
 WHERE EMPCOD= '03' AND  DOCCOD='CEF' AND MVCNRO=86; 

UPDATE HOSVITAL.HOJOBLPRV 
SET HOPTOTDEB = 0
WHERE PRVCOD ='860010451' AND EMPCOD='03' AND HOPNOOBL= 'AP- 11720' AND HOPTOTDEB = 84900.00	;
