SELECT HOSVITAL.MAEMED1.MMCEDM AS CEDULA_MED,
HOSVITAL.PROCIR1.PROCIRCOD  AS CODIGO_CIRUGIA, MAX(HOSVITAL.PROCIR.PROFECF)  AS FECHA_CIRUGIA,  CASE MAX(HOSVITAL.PROCIR.PROESTA) WHEN '1' THEN 'RESERVADA' WHEN '2' THEN 'CONFIRMADA' WHEN '3' THEN 'CANCELADA' WHEN '4' THEN 'REALIZADA' WHEN '5' THEN 'FACTURADA' WHEN '6' THEN 'PENDIENTE' WHEN '7' THEN 'CON INSTRUCCIONES' END AS ESTADO,  MAX(HOSVITAL.PROCIR.PROCONS) AS COD_SALA, MAX(HOSVITAL.CONSUL.CONSDET) AS SALA, MAX(HOSVITAL.DESCIRMED.HORINICIR) AS HORA_INICIO , MAX(HOSVITAL.DESCIRMED.HORFINCIR) AS HORA_FINAL, 
CASE MAX(HOSVITAL.INGRESOS.CLAPRO) WHEN '1' THEN 'AMBULATORIO' WHEN '2' THEN 'HOSPITALIZACION' WHEN '3' THEN 'URGENCIAS' WHEN '4' THEN 'TRATAMIENTO ESPECIAL' WHEN '5' THEN 'URGENCIAS' END AS ORIGEN, MAX(HOSVITAL.CAPBAS.MPTDOC)  AS TIPO_DOCUMENTO, HOSVITAL.PROCIR.MPCEDU AS IDENTIFICACION,  MAX(HOSVITAL.CAPBAS.MPNOMC) AS PACIENTE, MAX(HOSVITAL.CAPBAS.MPFCHN) AS FECHA_NACIMIENTO,  MAX(HOSVITAL.CAPBAS.MPSEXO) AS GENERO, 
MAX(HOSVITAL.CAPBAS.MPTELE) AS TELEFONO, MAX(HOSVITAL.PROCIR.PROEPS) AS COD_EPS, MAX(HOSVITAL.MAEEMP.MENOMB) AS EPS, MAX(HOSVITAL.PROCIR2.PERSESP) AS COD_ESPCIALIDAD, MIN(HOSVITAL.MAEESP.MENOME) AS ESPECIALIDAD, HOSVITAL.MAEPRO.PRCODI AS COD_PROCEDIMIENTO , MAX(HOSVITAL.MAEPRO.PRNOMB) AS PROCEDIMIENTO,  
MAX(HOSVITAL.PROCIR1.CRGCNT) AS TOTAL_PROCEDIMIENTOS, HOSVITAL.PROCIR1.MEDCOD AS CODIGO_MEDICO , MAX(HOSVITAL.MAEMED1.MMNOMM) AS CIRUJANO,
  CASE MAX(HOSVITAL.DESCIRMED.TIPANE) WHEN 'G' THEN 'GENERAL' WHEN 'R' THEN 'REGIONAL' WHEN 'L' THEN 'LOCAL' WHEN 'N' THEN 'NO APLICA' END AS TIPO_ANESTESIA,
  MAX(HOSVITAL.PROCIR2.PERSCOD) AS CODIGO_PARTICIPANTE,  MAX(MAEMED1_2.MMNOMM)  AS PARTICIPANTE, MAX(HOSVITAL.PROCIR2.PERSTIP) AS TIPO_PARTICIPANTE, MAX(HOSVITAL.VIAS.VIACOD) AS CODIGO_VIA , MAX(HOSVITAL.VIAS.VIADSC) AS VIA, CASE MAX(HOSVITAL.PROCIR.PROSIT) WHEN '1' THEN 'PROGRAMADA' WHEN '2' THEN 'URGENCIAS' WHEN '3' THEN 'TRAUMA' END AS TIPO_CIRUGIA, MAX(HOSVITAL.DESCIRMED.DESCOM) AS COMPLICACIONES,  CASE MAX(HOSVITAL.DESCIRMED.TIPHER) WHEN '1' THEN 'LIMPIA' WHEN '2' THEN 'LIMPIA CONTAMINADA' WHEN '3' THEN 'CONTAMINADA' WHEN '4' THEN 'SUCIA' END AS TIPO_HERIDA, MAX(HOSVITAL.PROCIR.PROMOTCAN) AS MTVO_CANCELACION, MAX(HOSVITAL.PORTAR1.PTCNTUVR) AS VALOR_UVR, MAX(HOSVITAL.PROCIR1.CRGHNRCI) AS HONORARIOS
 FROM ((((((((((((HOSVITAL.PROCIR1 
 INNER JOIN HOSVITAL.PROCIR ON (HOSVITAL.PROCIR1.PROCIRCOD = HOSVITAL.PROCIR.PROCIRCOD) AND (HOSVITAL.PROCIR1.PROMCDPTO = HOSVITAL.PROCIR.PROMCDPTO) AND (HOSVITAL.PROCIR1.PROEMPCOD = HOSVITAL.PROCIR.PROEMPCOD))  INNER JOIN HOSVITAL.CONSUL ON HOSVITAL.PROCIR.PROCONS = HOSVITAL.CONSUL.CONSCOD) 
INNER JOIN HOSVITAL.DESCIRMED ON HOSVITAL.PROCIR.PROCIRCOD = HOSVITAL.DESCIRMED.CODCIR) 
INNER JOIN HOSVITAL.INGRESOS ON (HOSVITAL.PROCIR.PROCTVIN = HOSVITAL.INGRESOS.INGCSC) AND (HOSVITAL.PROCIR.MPTDOC = HOSVITAL.INGRESOS.MPTDOC) AND (HOSVITAL.PROCIR.MPCEDU = HOSVITAL.INGRESOS.MPCEDU)) 
INNER JOIN HOSVITAL.CAPBAS ON (HOSVITAL.PROCIR.MPTDOC = HOSVITAL.CAPBAS.MPTDOC) AND (HOSVITAL.PROCIR.MPCEDU = HOSVITAL.CAPBAS.MPCEDU)) 
INNER JOIN HOSVITAL.MAEEMP ON HOSVITAL.PROCIR.PROEPS = HOSVITAL.MAEEMP.MENNIT) 
INNER JOIN (HOSVITAL.PROCIR2 
INNER JOIN HOSVITAL.MAEESP ON HOSVITAL.PROCIR2.PERSESP = HOSVITAL.MAEESP.MECODE) ON (HOSVITAL.PROCIR.PROCIRCOD = HOSVITAL.PROCIR2.PROCIRCOD) AND (HOSVITAL.PROCIR.PROMCDPTO = HOSVITAL.PROCIR2.PROMCDPTO) AND (HOSVITAL.PROCIR.PROEMPCOD = HOSVITAL.PROCIR2.PROEMPCOD)) 
INNER JOIN HOSVITAL.MAEPRO ON HOSVITAL.PROCIR1.CRGCOD = HOSVITAL.MAEPRO.PRCODI)  INNER JOIN HOSVITAL.MAEMED1 ON HOSVITAL.PROCIR1.MEDCOD = HOSVITAL.MAEMED1.MMCODM)  
INNER JOIN HOSVITAL.MAEMED1 AS MAEMED1_2 ON HOSVITAL.PROCIR2.PERSCOD = MAEMED1_2.MMCODM) 
 INNER JOIN HOSVITAL.VIAS ON HOSVITAL.PROCIR1.VIACOD = HOSVITAL.VIAS.VIACOD) 
 INNER JOIN HOSVITAL.MAEEMP31 ON HOSVITAL.PROCIR.PROEPS = HOSVITAL.MAEEMP31.MENNIT) 
 INNER JOIN HOSVITAL.PORTAR1 ON (HOSVITAL.PROCIR1.CRGCOD = HOSVITAL.PORTAR1.PRCODI) AND (HOSVITAL.MAEEMP31.PTCODI = HOSVITAL.PORTAR1.PTCODI)
INNER JOIN HOSVITAL.PORTAR ON (HOSVITAL.PORTAR.PTCODI = HOSVITAL.PORTAR1.PTCODI) 
WHERE ( (((HOSVITAL.PROCIR.PROFEC)>= '2019-04-10') AND ((HOSVITAL.PROCIR.PROFEC)<= '2019-04-10'))  and (HOSVITAL.PORTAR.PTEST = 'S') and (hosvital.PROCIR2.PERSESP  NOT IN(136,138))   AND (HOSVITAL.PROCIR2.PERSEST='S' )and ((HOSVITAL.PROCIR2.PERSTIP)='01') and ((HOSVITAL.PROCIR1.CRGHNRCI) ='01'))   --and hosvital.procir.procircod =106335	

GROUP BY HOSVITAL.MAEMED1.MMCEDM, HOSVITAL.PROCIR.MPCEDU,HOSVITAL.PROCIR1.PROCIRCOD, HOSVITAL.MAEPRO.PRCODI, HOSVITAL.PROCIR1.MEDCOD
order by  HOSVITAL.PROCIR1.PROCIRCOD
