--  Generar SQL 
--  Versión:                   	V7R1M0 100423 
--  Generado en:              	12/07/21 09:02:54 
--  Base de datos relacional:       	IASP 
--  Opción de estándares:          	DB2 for i 
CREATE TRIGGER HOSVIPRU.ACTIVACITA 
	AFTER INSERT ON HOSVIPRU.CITMED2 
	REFERENCING OLD AS O 
	NEW AS NUEVA 
	FOR EACH ROW 
	MODE DB2SQL 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	INSERT INTO HOSVIPRU . VISTACEX ( CITA , FECHA , HORA , CONSULTORIO , ESPECIALIDAD , MEDICO , PACIENTE , ESTADO_CITA , PANTALLA , ATENDIDO ) 
	SELECT C . CITNUM AS CITA , C . CITFEC AS FECHA , C . CITHORI AS HORA , CONSUL . CONSCOD AS CONSULTORIO , ESP . MENOME AS ESPECIALIDAD , MAE . MMNOMM AS MEDICO , CAP . MPNOMC AS PACIENTE , 
	CASE WHEN C . CITESTP = 'F' THEN 'Facturada' 
	WHEN C . CITESTP = 'A' THEN 'Atendido' 
	WHEN C . CITESTP = 'N' THEN 'Cancelada' 
	WHEN C . CITESTP = 'R' THEN 'Reservada' 
	WHEN C . CITESTP = 'I' THEN 'Incumplida' 
	WHEN C . CITESTP = 'C' THEN 'Confirmada' END AS ESTADO_CITA , 0 AS LLAMADA , 0 AS ATENDIDO 
	FROM HOSVIPRU . CITMED C 
	INNER JOIN HOSVIPRU . CITMED1 C1 ON ( C1 . CITNUM = C . CITNUM ) 
	INNER JOIN HOSVIPRU . CITMED2 C2 ON ( C2 . CITNUM = C1 . CITNUM ) 
	INNER JOIN HOSVIPRU . CAPBAS CAP ON ( CAP . MPTDOC = C1 . CITTIPDOC AND CAP . MPCEDU = C1 . CITCED ) 
	INNER JOIN HOSVIPRU . CONSUL CONSUL ON ( CONSUL . CONSCOD = C . CITCONS ) 
	INNER JOIN HOSVIPRU . MAEMED1 MAE ON ( MAE . MMCODM = C2 . MMCODM ) 
	INNER JOIN HOSVIPRU . MAEESP ESP ON ( ESP . MECODE = C2 . MECODE ) 
	WHERE C . CITNUM = NUEVA . CITNUM AND C . CITESTP IN ( 'C' , 'R' ) AND  -- c.citnum not in (select x.cita from HOSVIPRU.vistacex x) and 
	( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( CONSUL . CONSCOD , ' ' ) , MAE . MMNOMM ) , ' ' ) , ESP . MENOME ) , ' ' ) , CAST ( C . CITFEC AS		VARCHAR ( 12 ) ) ) , ' ' ) , C . CITHORI ) , ' ' ) , C . CITESTP ) , ' ' ) , CAP . MPNOMC ) ) = ( SELECT QSYS2 . MIN ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( QSYS2 . CONCAT ( CONSULX . CONSCOD , ' ' ) ,	MAEX . MMNOMM ) , ' ' ) , ESPX . MENOME ) , ' ' ) , CAST ( CX . CITFEC AS VARCHAR ( 12 ) ) ) , ' ' ) , CX . CITHORI ) , ' ' ) , CX . CITESTP ) , ' ' ) , CAPX . MPNOMC ) ) 
	FROM HOSVIPRU . CITMED CX 
	INNER JOIN HOSVIPRU . CITMED1 CX1 ON ( CX1 . CITNUM = CX . CITNUM ) 
	INNER JOIN HOSVIPRU . CITMED2 CX2 ON ( CX2 . CITNUM = CX1 . CITNUM ) 
	INNER JOIN HOSVIPRU . CAPBAS CAPX ON ( CAPX . MPTDOC = CX1 . CITTIPDOC AND CAPX . MPCEDU = CX1 . CITCED ) 
	INNER JOIN HOSVIPRU . CONSUL CONSULX ON ( CONSULX . CONSCOD = CX . CITCONS ) 
	INNER JOIN HOSVIPRU . MAEMED1 MAEX ON ( MAEX . MMCODM = CX2 . MMCODM ) 
	INNER JOIN HOSVIPRU . MAEESP ESPX ON ( ESPX . MECODE = CX2 . MECODE ) 
	WHERE CX . CITNUM = NUEVA . CITNUM AND CX . CITESTP IN ( 'C' , 'R' ) AND CAPX . MPTDOC = C1 . CITTIPDOC AND CAPX . MPCEDU = C1 . CITCED )  ;
