SELECT H.HISCKEY AS IDENTIFICACION,H.HISTIPDOC AS TIPO_ID,C.MPNOMC AS PACIENTE,HOSVITAL.TMPFAC.TFCCODCAM AS CAMA, HOSVITAL.MAEPAB.MPNOMP AS PABELLON,H.HISCSEC AS FOLIO,H.HCPRCCOD AS CODIGO_PROC,M.PRNOMB PROCEDIMIENTO,H.HCPRCEST AS ESTADO, H.HCFCHRORD AS FECHA_ORDENADO,HOSVITAL.MAEMED1.MMNOMM AS MEDICO_INTERPRETA,H.HCFCHRAP AS FECHA_APLICADO, H.HCRESULT AS RESULTADO, HCINTRES AS INTERPRETADO, HCFEHINT AS FECHA_INTERPRETADO 
FROM HOSVITAL.HCCOM51  H 
INNER JOIN HOSVITAL.CAPBAS C ON(H.HISCKEY=C.MPCEDU AND H.HISTIPDOC=C.MPTDOC)
 INNER JOIN HOSVITAL.TMPFAC  ON (H.HISCKEY = HOSVITAL.TMPFAC.TFCEDU AND  H.HISTIPDOC=TFTDOC) AND (H.HCTVIN51 = HOSVITAL.TMPFAC.TmCtvIng )
INNER JOIN HOSVITAL.MAEPAB ON  (HOSVITAL.TMPFAC.TFCCODPAB = HOSVITAL.MAEPAB.MPCODP) 
INNER JOIN HOSVITAL.MAEPRO M ON (H.HCPRCCOD = M.PRCODI ) 
LEFT JOIN HOSVITAL.MAEMED1 ON (H.HCMEDINT = HOSVITAL.MAEMED1.MMCODM)
WHERE (((H.HCPRCTPOP)=2) AND  (H.HCPRCEST IN('A','I','O'))   AND (DATE(H.HCFCHRORD)>= ?) AND (DATE(H.HCFCHRORD)<= ?)) AND H.HCPRCCOD NOT IN ('902202', '911004', '911018', '911020', '911021', '911022', '911026','911103', '911104', '911105', '911107', '911108', '911111', '911201', '911302', '912001','912002', '912003', '912005')AND HOSVITAL.MAEPAB.MPCODP NOT IN('8','10');

-- Nuevo reporte

select * from hosvital.maepab  where mpclapro='2';
SELECT * FROM HOSVITAL.TIPPROC;

SELECT H.HISCKEY AS IDENTIFICACION,H.HISTIPDOC AS TIPO_ID,C.MPNOMC AS PACIENTE,T.TFCCODCAM AS CAMA,MAEPAB.MPNOMP AS PABELLON,H.HISCSEC AS FOLIO,H.HCPRCCOD AS CODIGO_PROC,M.PRNOMB PROCEDIMIENTO,H.HCPRCEST AS ESTADO, H.HCFCHRORD AS FECHA_ORDENADO,M1.MMNOMM AS MEDICO_INTERPRETA,H.HCFCHRAP AS FECHA_APLICADO, H.HCRESULT AS RESULTADO, HCINTRES AS INTERPRETADO, HCFEHINT AS FECHA_INTERPRETADO 
FROM HOSVITAL.HCCOM51  H 
INNER JOIN HOSVITAL.CAPBAS C ON(H.HISCKEY=C.MPCEDU AND H.HISTIPDOC=C.MPTDOC)
 INNER JOIN HOSVITAL.TMPFAC T  ON (H.HISCKEY = T.TFCEDU AND  H.HISTIPDOC=T.TFTDOC) AND (H.HCTVIN51 =T.TmCtvIng )
INNER JOIN HOSVITAL.MAEPAB  MAEPAB ON  (T.TFCCODPAB = MAEPAB.MPCODP) 
INNER JOIN HOSVITAL.MAEPRO M ON (H.HCPRCCOD = M.PRCODI ) 
LEFT JOIN HOSVITAL.MAEMED1  M1  ON (H.HCMEDINT = M1.MMCODM)
WHERE H.HCPRCTPOP IN ('1','2') AND  H.HCPRCEST IN('A','I','O')   AND DATE(H.HCFCHRORD)>= '2020-07-01' AND DATE(H.HCFCHRORD)<= '2020-07-31' AND MAEPAB.MPclapro='2'
ORDER BY H.HISCKEY,H.HISCSEC;

--  fACTURADOS 

SELECT * FROM HOSVITAL.MAEATE WHERE MPCEDU= '9065904';

SELECT * FROM HOSVITAL.MAEATE2;
SELECT * FROM HOSVITAL.HCCOM51 WHERE HISCKEY='9065904' ORDER BY HCPRCCOD ;
SELECT * FROM HOSVITAL.HCCOM51 WHERE HISCKEY='9065904'   AND HCPRCCOD= '871121';


SELECT * FROM HOSVITAL.HCCOM5 WHERE HISCKEY='1000134980' AND HCPRCCOD= '881602';
SELECT * FROM HOSVITAL.HCCOM51 WHERE HISCKEY='1000134980'   AND HCPRCCOD= '881602';

SELECT * FROM HOSVITAL.MAEATE2 WHERE MPNFAC IN ('631205','632091',	'632249','632867') AND PRCODI= '871121';	


SELECT MACODPAB,PRCODI FROM HOSVITAL.MAEATE2 WHERE MPNFAC = 633027; --	AND PRCODI= '881602';
SELECT * FROM HOSVITAL.MAEPRO WHERE PRCODI='881602';

SELECT * FROM HOSVITAL.MAEPAB;

SELECT * FROM HOSVITAL.CAPBAS WHERE MPCEDU='1000134980';

SELECT H.HISCKEY AS IDENTIFICACION,H.HISTIPDOC AS TIPO_ID,C.MPNOMC AS PACIENTE,MAE.FACCODCAM AS CAMA,MAEPAB.MPNOMP AS PABELLON,H.HISCSEC AS FOLIO,H.HCPRCCOD AS CODIGO_PROC,M.PRNOMB PROCEDIMIENTO,H.HCPRCEST AS ESTADO, H.HCFCHRORD AS FECHA_ORDENADO,M1.MMNOMM AS MEDICO_INTERPRETA,H.HCFCHRAP AS FECHA_APLICADO, H.HCRESULT AS RESULTADO, HCINTRES AS INTERPRETADO, HCFEHINT AS FECHA_INTERPRETADO 
FROM HOSVITAL.HCCOM51  H 
INNER JOIN HOSVITAL.CAPBAS C ON(H.HISCKEY=C.MPCEDU AND H.HISTIPDOC=C.MPTDOC)
 INNER JOIN HOSVITAL.MAEATE MAE  ON (H.HISCKEY = MAE.MPCEDU AND  H.HISTIPDOC=MAE.MPTDOC AND H.HCTVIN51 =MAE.MACTVING AND MAE.MATIPDOC IN ('2','5') )
INNER JOIN HOSVITAL.MAEATE2 MAE2 ON (MAE2.MPNFAC=MAE.MPNFAC AND MAE2.FCPTPOTRN='F' AND MAE2.MAESANUP<>'S'  AND MAE2.MANUMFOL=H.HISCSEC)
LEFT  JOIN HOSVITAL.MAEPAB  MAEPAB ON  ( MAE2.MACODPAB = MAEPAB.MPCODP) 
INNER JOIN HOSVITAL.MAEPRO M ON (H.HCPRCCOD = M.PRCODI AND H.HCPRCCOD=MAE2.PRCODI ) 
LEFT JOIN HOSVITAL.MAEMED1  M1  ON (H.HCMEDINT = M1.MMCODM)
WHERE   H.HCPRCTPOP IN ('1','2')  AND  H.HCPRCEST IN('A','I','O')   AND DATE(H.HCFCHRORD)>= '2020-07-01' AND DATE(H.HCFCHRORD)<= '2020-07-31' AND MAEPAB.MPclapro='2' 
ORDER BY H.HISCKEY,H.HISCSEC;

-- qUERY TOTAL

SELECT H.HISCKEY AS IDENTIFICACION,H.HISTIPDOC AS TIPO_ID,C.MPNOMC AS PACIENTE,T.TFCCODCAM AS CAMA,MAEPAB.MPNOMP AS PABELLON,H.HISCSEC AS FOLIO,H.HCPRCCOD AS CODIGO_PROC,M.PRNOMB PROCEDIMIENTO,H.HCPRCEST AS ESTADO, H.HCFCHRORD AS FECHA_ORDENADO,M1.MMNOMM AS MEDICO_INTERPRETA,H.HCFCHRAP AS FECHA_APLICADO, H.HCRESULT AS RESULTADO, HCINTRES AS INTERPRETADO, HCFEHINT AS FECHA_INTERPRETADO 
FROM HOSVITAL.HCCOM51  H 
INNER JOIN HOSVITAL.CAPBAS C ON(H.HISCKEY=C.MPCEDU AND H.HISTIPDOC=C.MPTDOC)
 INNER JOIN HOSVITAL.TMPFAC T  ON (H.HISCKEY = T.TFCEDU AND  H.HISTIPDOC=T.TFTDOC) AND (H.HCTVIN51 =T.TmCtvIng )
INNER JOIN HOSVITAL.MAEPAB  MAEPAB ON  (T.TFCCODPAB = MAEPAB.MPCODP) 
INNER JOIN HOSVITAL.MAEPRO M ON (H.HCPRCCOD = M.PRCODI ) 
LEFT JOIN HOSVITAL.MAEMED1  M1  ON (H.HCMEDINT = M1.MMCODM)
WHERE H.HCPRCTPOP IN ('1','2') AND  H.HCPRCEST IN('A','I','O')   AND DATE(H.HCFCHRORD)>= '2020-07-01' AND DATE(H.HCFCHRORD)<= '2020-07-31' AND MAEPAB.MPclapro='2'
UNION
SELECT H.HISCKEY AS IDENTIFICACION,H.HISTIPDOC AS TIPO_ID,C.MPNOMC AS PACIENTE,MAE.FACCODCAM AS CAMA,MAEPAB.MPNOMP AS PABELLON,H.HISCSEC AS FOLIO,H.HCPRCCOD AS CODIGO_PROC,M.PRNOMB PROCEDIMIENTO,H.HCPRCEST AS ESTADO, H.HCFCHRORD AS FECHA_ORDENADO,M1.MMNOMM AS MEDICO_INTERPRETA,H.HCFCHRAP AS FECHA_APLICADO, H.HCRESULT AS RESULTADO, HCINTRES AS INTERPRETADO, HCFEHINT AS FECHA_INTERPRETADO 
FROM HOSVITAL.HCCOM51  H 
INNER JOIN HOSVITAL.CAPBAS C ON(H.HISCKEY=C.MPCEDU AND H.HISTIPDOC=C.MPTDOC)
 INNER JOIN HOSVITAL.MAEATE MAE  ON (H.HISCKEY = MAE.MPCEDU AND  H.HISTIPDOC=MAE.MPTDOC AND H.HCTVIN51 =MAE.MACTVING AND MAE.MATIPDOC IN ('2','5') )
INNER JOIN HOSVITAL.MAEATE2 MAE2 ON (MAE2.MPNFAC=MAE.MPNFAC AND MAE2.FCPTPOTRN='F' AND MAE2.MAESANUP<>'S'  AND MAE2.MANUMFOL=H.HISCSEC)
LEFT  JOIN HOSVITAL.MAEPAB  MAEPAB ON  ( MAE2.MACODPAB = MAEPAB.MPCODP) 
INNER JOIN HOSVITAL.MAEPRO M ON (H.HCPRCCOD = M.PRCODI AND H.HCPRCCOD=MAE2.PRCODI ) 
LEFT JOIN HOSVITAL.MAEMED1  M1  ON (H.HCMEDINT = M1.MMCODM)
WHERE   H.HCPRCTPOP IN ('1','2')  AND  H.HCPRCEST IN('A','I','O')   AND DATE(H.HCFCHRORD)>= '2020-07-01' AND DATE(H.HCFCHRORD)<= '2020-07-31' AND MAEPAB.MPclapro='2' 
ORDER BY 1,2;

-- Query desde el punto de vista clinico para lo facturado

SELECT * FROM HOSVITAL.INGRESOS;

SELECT H.HISCKEY AS IDENTIFICACION,H.HISTIPDOC AS TIPO_ID,C.MPNOMC AS PACIENTE,I.MPNUMC AS CAMA,MAEPAB.MPNOMP AS PABELLON,H.HISCSEC AS FOLIO,H.HCPRCCOD AS CODIGO_PROC,M.PRNOMB PROCEDIMIENTO,H.HCPRCEST AS ESTADO, H.HCFCHRORD AS FECHA_ORDENADO,M1.MMNOMM AS MEDICO_INTERPRETA,H.HCFCHRAP AS FECHA_APLICADO, H.HCRESULT AS RESULTADO, HCINTRES AS INTERPRETADO, HCFEHINT AS FECHA_INTERPRETADO 
FROM HOSVITAL.HCCOM51  H 
INNER JOIN HOSVITAL.CAPBAS C ON(H.HISCKEY=C.MPCEDU AND H.HISTIPDOC=C.MPTDOC)
INNER JOIN HOSVITAL.INGRESOS I ON (I.MPTDOC=H.HISTIPDOC AND I.MPCEDU=H.HISCKEY AND I.INGCSC= H.HCTVIN51)
 --INNER JOIN HOSVITAL.MAEATE MAE  ON (H.HISCKEY = MAE.MPCEDU AND  H.HISTIPDOC=MAE.MPTDOC AND H.HCTVIN51 =MAE.MACTVING AND MAE.MATIPDOC IN ('2','5') )
--INNER JOIN HOSVITAL.MAEATE2 MAE2 ON (MAE2.MPNFAC=MAE.MPNFAC AND MAE2.FCPTPOTRN='F' AND MAE2.MAESANUP<>'S'  AND MAE2.MANUMFOL=H.HISCSEC)
LEFT  JOIN HOSVITAL.MAEPAB  MAEPAB ON  ( MAEPAB.MPCODP = I.MPCODP ) 
INNER JOIN HOSVITAL.MAEPRO M ON (H.HCPRCCOD = M.PRCODI ) 
LEFT JOIN HOSVITAL.MAEMED1  M1  ON (H.HCMEDINT = M1.MMCODM)
WHERE   H.HCPRCTPOP IN ('1','2')  AND  H.HCPRCEST IN('A','I','O')   AND DATE(H.HCFCHRORD)>= '2020-07-01' AND DATE(H.HCFCHRORD)<= '2020-07-31' AND MAEPAB.MPclapro='2' 
ORDER BY H.HISCKEY,H.HISCSEC;