SELECT * FROM  HOSVITAL.PROCIR;

-- Cirugias

SELECT YEAR(PROFEC)  AnO, MONTH(PROFEC) MES, COUNT(*) TOTAL
FROM HOSVITAL.PROCIR
WHERE PROFEC >= '2019-01-01' AND PROESTA IN ('4','5')
GROUP BY YEAR(PROFEC), MONTH(PROFEC)
ORDER BY YEAR(PROFEC), MONTH(PROFEC);

-- Cirugias por año

SELECT YEAR(PROFEC)  AnO, COUNT(*) TOTAL
FROM HOSVITAL.PROCIR
WHERE PROFEC >= '2019-01-01' AND PROESTA IN ('4','5')
GROUP BY YEAR(PROFEC)
ORDER BY YEAR(PROFEC);



SELECT procircod,mpcedu,mptdoc,profec ,proesta FROM HOSVITAL.PROCIR
WHERE PROFEC >= '2019-01-01' AND PROESTA IN ('4','5')
order by profec;


-- Imagenes realizadas

SELECT * FROM HOSVITAL.TIPPROC;
SELECT * FROM HOSVITAL.MAEPRO;

SELECT * FROM HOSVITAL.HCCOM51;

SELECT YEAR(H.HCFCHRAP) ano, MONTH(H.HCFCHRAP) mes ,COUNT(*) total
FROM HOSVITAL.HCCOM51 H
INNER JOIN HOSVITAL.MAEPRO M ON (M.PRCODI=H.HCPRCCOD)
INNER JOIN HOSVITAL.TIPPROC T ON (T.TIPRCOD = M.TPPRCD AND M.TPPRCD=1)
WHERE  H.HCFCHRAP >= '2019-01-01 00:00:00' AND H.HCPRCEST IN ('I','A')
GROUP BY YEAR(H.HCFCHRAP), MONTH(H.HCFCHRAP)
ORDER BY YEAR(H.HCFCHRAP), MONTH(H.HCFCHRAP);

SELECT * FROM HOSVITAL.MAEPAB;
SELECT * FROM HOSVITAL.MAEPAB1 WHERE MPFCHI>= '2021-08-04 00:00:00';

-- PROMEDO DE ESTANCIAS

SELECT * FROM HOSVITAL.INGRESOS WHERE INGFECEGR>= '2021-05-01 00:00:00';
SELECT MPCEDU, MPTDOC, INGFECADM,INGFECEGR, MPCODP,MPNUMC, CLAPRO, (DAYS(INGFECEGR) - DAYS(INGFECADM))  DIAS FROM HOSVITAL.INGRESOS WHERE CLAPRO=2 AND  INGFECEGR>= '2021-05-01 00:00:00';

-- PROMEDIO DE ESTANCIAS

SELECT YEAR(INGFECEGR) ANO, MONTH(INGFECEGR) MES , COUNT(*)TOTAL  ,SUM(DAYS(INGFECEGR) - DAYS(INGFECADM))/COUNT(*) PROMEDIO_DIA
FROM HOSVITAL.INGRESOS
WHERE INGFECEGR>= '2019-01-01 00:00:00' AND CLAPRO= 2      	
GROUP BY YEAR(INGFECEGR), MONTH(INGFECEGR)
ORDER BY YEAR(INGFECEGR), MONTH(INGFECEGR);







