 -- BUENAS TARDE ME PERMITO SOLICITAR LA ESTADISICA DE TRIAGES REALIZADOS
 --Y NUMERO DE ATEnCION DE PACIENTE EN URGENCIAS ,  -- sERIAN PACIEMNTES ATENDIDOS ??
--Y PROMEDIO DE TIEMPOS ENTRE RELAIZACION DE TRAGUE Y CONSULTA POR CADA U A DE LAS CATEGORIAS 
--  DESDE EL MES DE MARZO DEL 2019 HASTA LA FECHA 


-- 20263217       	
-- 41701304       	
-- 19191635       	

select * from hosvital.hctriage; 

select * from hosvital.hccom1 WHERE HISFHORAT >= '2019-10-01 00:00:00';   -- HISCLTR,, FHCINDESP  = GN  / EN


SELECT YEAR( H.HISFHORAT),  MONTH( H.HISFHORAT), DAY( H.HISFHORAT), H.HISCLTR AS TRIAGE, COUNT(*)


FROM HOSVITAL.HCCOM1 H
WHERE H.HISFHORAT>='2019-03-01 00:00:00'
GROUP BY YEAR( H.HISFHORAT),  MONTH( H.HISFHORAT), DAY( H.HISFHORAT), H.HISCLTR
ORDER BY YEAR( H.HISFHORAT),  MONTH( H.HISFHORAT), DAY( H.HISFHORAT), H.HISCLTR;



-- Query 2

SELECT YEAR( H.HISFHORAT),  MONTH( H.HISFHORAT), DAY( H.HISFHORAT), H.HISCLTR AS TRIAGE, COUNT(*),
SUM(
(SELECT  (HH.HISFHORAT - hhh.hisfhorat)
FROM HOSVITAL.HCCOM1 HH, HOSVITAL.HCCOM1 HHH
WHERE YEAR( HH.HISFHORAT) =  YEAR( H.HISFHORAT) AND  MONTH( HH.HISFHORAT) = MONTH( H.HISFHORAT) AND  DAY( HH.HISFHORAT) = DAY( H.HISFHORAT) AND HH.HISCLTR = H.HISCLTR and
             hh.histipdoc =  hhh.histipdoc AND  hh.hisckey = hHh.hisckey AND  hh.hiscsec  = Hhh.hiscsec AND hhh.FHCINDESP='GN' and hhh.hisfhorat = (select min(hhhh.hisfhorat) from hosvital.hccom1 hhhh
									 where hhhh.histipdoc=hhh.histipdoc and hhhh.hisckey=hhh.hisckey and hhhh.hiscsec= 										            hhh.hiscsec and hhhh.FHCINDESP='GN')

)) AS PROMEDIO_DE_TIEMPOS
FROM HOSVITAL.HCCOM1 H
WHERE H.HISFHORAT>='2019-03-01 00:00:00'
GROUP BY YEAR( H.HISFHORAT),  MONTH( H.HISFHORAT), DAY( H.HISFHORAT), H.HISCLTR
ORDER BY YEAR( H.HISFHORAT),  MONTH( H.HISFHORAT), DAY( H.HISFHORAT), H.HISCLTR;
