SELECT * FROM HOSVITAL.AdmWrkSt;
SELECT * FROM HOSVITAL.ADNcAmo;

SELECT * FROM HOSVITAL.RESSEV  WHERE RESFEC >= '2021-03-01 00:00:00';

SELECT HOSVITAL.INTERCN.HISCKEY AS IDENTIFICACION, HOSVITAL.INTERCN.HISTIPDOC AS TIP_IDENT, HOSVITAL.CAPBAS.MPNOMC AS PACIENTE,HOSVITAL.MAEEMP.MENOMB AS EMPRESA,HOSVITAL.MAEPAB.MPNOMP AS PABELLON, HOSVITAL.TMPFAC.TFCCODCAM AS CAMA, HOSVITAL.INTERCN.HISCSEC AS FOLIO, HOSVITAL.MAEESP.MENOME AS ESPECIALIDAD,HOSVITAL.INTERCN.INTEST AS ESTADO,HOSVITAL.MAEMED1.MMNOMM AS MEDICO_SOLICITA, HOSVITAL.HCCOM1.HISCFCON AS FECHA_SOLICITUD, HOSVITAL.INTERCN.INTFCHRSL AS FECHA_RESPUESTA,HOSVITAL.INTERCN.INTOBSORD AS OBSER_SOLICITUD,HOSVITAL.INTERCN.INTDSCRSL AS CONCEPTO_RESPUESTA  
FROM HOSVITAL.INTERCN
 INNER JOIN HOSVITAL.CAPBAS ON((HOSVITAL.INTERCN.HISCKEY = HOSVITAL.CAPBAS.MPCEDU) AND (HOSVITAL.INTERCN.HISTIPDOC = HOSVITAL.CAPBAS.MPTDOC)) 
INNER JOIN HOSVITAL.MAEESP ON (HOSVITAL.INTERCN.MECODE = HOSVITAL.MAEESP.MECODE)
 INNER JOIN HOSVITAL.TMPFAC ON ((HOSVITAL.INTERCN.HISCKEY = HOSVITAL.TMPFAC.TFCEDU) AND (HOSVITAL.INTERCN.HISTIPDOC = HOSVITAL.TMPFAC.TFTDOC))
 INNER JOIN HOSVITAL.MAEEMP ON (HOSVITAL.MAEEMP.MENNIT = HOSVITAL.TMPFAC.TFMENI)  
INNER JOIN HOSVITAL.HCCOM1 ON ((HOSVITAL.INTERCN.HISCSEC = HOSVITAL.HCCOM1.HISCSEC) AND (HOSVITAL.INTERCN.HISTIPDOC = HOSVITAL.HCCOM1.HISTIPDOC) AND (HOSVITAL.INTERCN.HISCKEY = HOSVITAL.HCCOM1.HISCKEY)) INNER JOIN HOSVITAL.MAEMED1 ON (HOSVITAL.HCCOM1.HISCMMED=HOSVITAL.MAEMED1.MMCODM) 
INNER JOIN HOSVITAL.MAEPAB ON (HOSVITAL.TMPFAC.TFCCODPAB = HOSVITAL.MAEPAB.MPCODP) 
WHERE ((HOSVITAL.HCCOM1.HISCFK)>='2021-01-01' AND (HOSVITAL.HCCOM1.HISCFK)<='2021-01-31') 
--ORDER BY HOSVITAL.HCCOM1.HISCFCON DESC
order by HOSVITAL.INTERCN.HISCKEY;

SELECT i.HISCKEY AS IDENTIFICACION, i.HISTIPDOC AS TIP_IDENT, cap.MPNOMC AS PACIENTE,maeemp.MENOMB AS EMPRESA,pab.MPNOMP AS PABELLON, t.TFCCODCAM AS CAMA, i.HISCSEC AS FOLIO, maeesp.MENOME AS ESPECIALIDAD,i.INTEST AS ESTADO,mae.MMNOMM AS MEDICO_SOLICITA, h.HISCFCON AS FECHA_SOLICITUD, i.INTFCHRSL AS FECHA_RESPUESTA,i.INTOBSORD AS OBSER_SOLICITUD,i.INTDSCRSL AS CONCEPTO_RESPUESTA  
FROM HOSVITAL.INTERCN i
 INNER JOIN HOSVITAL.CAPBAS cap ON(i.HISCKEY = cap.MPCEDU AND i.HISTIPDOC = cap.MPTDOC)
INNER JOIN HOSVITAL.MAEESP  maeesp ON (i.MECODE = maeesp.MECODE)
 INNER JOIN HOSVITAL.TMPFAC t ON (i.HISCKEY = t.TFCEDU AND i.HISTIPDOC = t.TFTDOC)
 INNER JOIN HOSVITAL.MAEEMP maeemp ON (maeemp.MENNIT = t.TFMENI)  
INNER JOIN HOSVITAL.HCCOM1 h ON (i.HISCSEC = h.HISCSEC AND i.HISTIPDOC = h.HISTIPDOC AND i.HISCKEY = h.HISCKEY)
 INNER JOIN HOSVITAL.MAEMED1 mae ON (h.HISCMMED=mae.MMCODM) 
INNER JOIN HOSVITAL.MAEPAB pab ON (t.TFCCODPAB = pab.MPCODP) 
WHERE h.HISCFK>='2021-01-01' AND h.HISCFK<='2021-01-31'
ORDER BY h.HISCFCON DESC;


--  atendi x localidad

