SELECT * FROM HOSVITAL.SGNVTLH;

SELECT H.HISFHORAT FECHA,S.HISTIPDOC AS TIPO_DO ,S.HISCKEY AS DOCUMENTO, C.MPNOMC AS PACIENTE, S.HISCSEC AS FOLIO,  S.HISDPES AS PESO, S.HISDTAL AS TALLA,  S.HISPIEL  AS PIEL, M.DMNOMB AS DIAGNOSTICO
FROM HOSVITAL.SGNVTLH S
INNER JOIN HOSVITAL.HCCOM1 H ON (H.HISTIPDOC=S.HISTIPDOC AND H.HISCKEY=S.HISCKEY AND H.HISCSEC=S.HISCSEC)
LEFT JOIN  HOSVITAL.HCDIAGN HC ON   (HC.HISTIPDOC=S.HISTIPDOC AND HC.HISCKEY=S.HISCKEY AND HC.HISCSEC=S.HISCSEC)
INNER JOIN HOSVITAL.MAEDIA M ON (M.DMCODI= HCDXCOD)
INNER JOIN HOSVITAL.CAPBAS C ON (C.MPTDOC= S.HISTIPDOC AND C.MPCEDU=S.HISCKEY)
WHERE H.HISFHORAT >='2020-03-01 00:00:00' AND  H.HISFHORAT <='2020-03-05 00:00:00'
ORDER BY H.HISFHORAT ,S.HISTIPDOC  ,S.HISCKEY, S.HISCSEC;

SELECT * FROM HOSVITAL.HCDIAGN;
SELECT * FROM HOSVITAL.MAEDIA;