-- todo radiologia menos Eco y Menos TomoMenos Reso


select distinct mae.prnomb  -- YEAR(H.HISFHORAT),MONTH(H.HISFHORAT),  'restantes',COUNT(*)
FROM HOSVITAL.HCCOM1 H
INNER JOIN HOSVITAL.HCCOM51 H51 ON (H51.HISTIPDOC=H.HISTIPDOC AND H51.HISCKEY=H.HISCKEY AND H51.HISCSEC=H.HISCSEC )
INNER JOIN HOSVITAL.TIPPROC T ON (T.TIPRCOD = H51.HCPRCTPOP AND T.TIPRCOD  =1 )
INNER JOIN HOSVITAL.MAEPRO MAE ON (MAE.PRCODI=H51.HCPRCCOD AND MAE.PRNOMB NOT LIKE ('%TOMO%') AND MAE.PRNOMB NOT LIKE ('%ECOGRA%') AND MAE.PRNOMB NOT LIKE ('%RESO%'))
WHERE H.HISFHORAT >= '2019-07-01 00:00:00' AND H.HISFHORAT<= '2019-10-31 23:59:59'  AND  H51.HCPRCEST IN ('E','A','I');
-- GROUP BY   YEAR(H.HISFHORAT),MONTH(H.HISFHORAT);



-- Total de procedimientos de radiologia
 
select YEAR(H.HISFHORAT),MONTH(H.HISFHORAT),  T.TIPRDES,COUNT(*)
FROM HOSVITAL.HCCOM1 H
INNER JOIN HOSVITAL.HCCOM51 H51 ON (H51.HISTIPDOC=H.HISTIPDOC AND H51.HISCKEY=H.HISCKEY AND H51.HISCSEC=H.HISCSEC )
INNER JOIN HOSVITAL.TIPPROC T ON (T.TIPRCOD = H51.HCPRCTPOP AND T.TIPRCOD  =1 )
WHERE H.HISFHORAT >= '2019-07-01 00:00:00' AND H.HISFHORAT<= '2019-10-31 23:59:59'  AND  H51.HCPRCEST IN ('E','A','I')
GROUP BY   YEAR(H.HISFHORAT),MONTH(H.HISFHORAT), T.TIPRDES;



-- Total de procedimientos de tomografia

select YEAR(H.HISFHORAT),MONTH(H.HISFHORAT),  'TOMOGRAFIA',COUNT(*)
FROM HOSVITAL.HCCOM1 H
INNER JOIN HOSVITAL.HCCOM51 H51 ON (H51.HISTIPDOC=H.HISTIPDOC AND H51.HISCKEY=H.HISCKEY AND H51.HISCSEC=H.HISCSEC )
INNER JOIN HOSVITAL.TIPPROC T ON (T.TIPRCOD = H51.HCPRCTPOP AND T.TIPRCOD  =1 )
INNER JOIN HOSVITAL.MAEPRO MAE ON (MAE.PRCODI=H51.HCPRCCOD AND MAE.PRNOMB LIKE ('%TOMO%'))
WHERE H.HISFHORAT >= '2019-07-01 00:00:00' AND H.HISFHORAT<= '2019-10-31 23:59:59'  AND  H51.HCPRCEST IN ('E','A','I')
GROUP BY   YEAR(H.HISFHORAT),MONTH(H.HISFHORAT);

-- Total de procedimientos de Resonancias

select YEAR(H.HISFHORAT),MONTH(H.HISFHORAT),  'RESONANCIAS',COUNT(*)
FROM HOSVITAL.HCCOM1 H
INNER JOIN HOSVITAL.HCCOM51 H51 ON (H51.HISTIPDOC=H.HISTIPDOC AND H51.HISCKEY=H.HISCKEY AND H51.HISCSEC=H.HISCSEC )
INNER JOIN HOSVITAL.TIPPROC T ON (T.TIPRCOD = H51.HCPRCTPOP AND T.TIPRCOD  =1 )
INNER JOIN HOSVITAL.MAEPRO MAE ON (MAE.PRCODI=H51.HCPRCCOD AND MAE.PRNOMB LIKE ('%RESON%'))
WHERE H.HISFHORAT >= '2019-07-01 00:00:00' AND H.HISFHORAT<= '2019-10-31 23:59:59'  AND  H51.HCPRCEST IN ('E','A','I')
GROUP BY   YEAR(H.HISFHORAT),MONTH(H.HISFHORAT);



-- Total de procedimientos de eCOCARDIOGRAMAS

select YEAR(H.HISFHORAT),MONTH(H.HISFHORAT),  'ECOCARDIOGRAMA',COUNT(*)
FROM HOSVITAL.HCCOM1 H
INNER JOIN HOSVITAL.HCCOM51 H51 ON (H51.HISTIPDOC=H.HISTIPDOC AND H51.HISCKEY=H.HISCKEY AND H51.HISCSEC=H.HISCSEC )
INNER JOIN HOSVITAL.TIPPROC T ON (T.TIPRCOD = H51.HCPRCTPOP AND T.TIPRCOD  =1 )
INNER JOIN HOSVITAL.MAEPRO MAE ON (MAE.PRCODI=H51.HCPRCCOD AND MAE.PRNOMB LIKE ('%ECOCAR%'))
WHERE H.HISFHORAT >= '2019-07-01 00:00:00' AND H.HISFHORAT<= '2019-10-31 23:59:59'  AND  H51.HCPRCEST IN ('E','A','I')
GROUP BY   YEAR(H.HISFHORAT),MONTH(H.HISFHORAT);


-- Total de procedimientos de Portatiles

select  YEAR(H.HISFHORAT),MONTH(H.HISFHORAT),  'PORTATILES',COUNT(*)
FROM HOSVITAL.HCCOM1 H
INNER JOIN HOSVITAL.HCCOM51 H51 ON (H51.HISTIPDOC=H.HISTIPDOC AND H51.HISCKEY=H.HISCKEY AND H51.HISCSEC=H.HISCSEC )
INNER JOIN HOSVITAL.TIPPROC T ON (T.TIPRCOD = H51.HCPRCTPOP AND T.TIPRCOD  =1 )
INNER JOIN HOSVITAL.MAEPRO MAE ON (MAE.PRCODI=H51.HCPRCCOD AND MAE.PRNOMB LIKE ('%FLUORO%'))
WHERE H.HISFHORAT >= '2019-07-01 00:00:00' AND H.HISFHORAT<= '2019-10-31 23:59:59'  AND  H51.HCPRCEST IN ('E','A','I')
GROUP BY   YEAR(H.HISFHORAT),MONTH(H.HISFHORAT);


-- Total de procedimientos de imagenologia



-- Pacientes atendidos en ecografia


SELECT YEAR(I.INGFECADM),MONTH(I.INGFECADM),COUNT(*)
FROM HOSVITAL.INGRESOS I
WHERE I.INGFECADM >= '2019-07-01 00:00:00' AND I.INGFECADM <= '2019-10-31 23:59:59' AND
   (I.MPTDOC,I.MPCEDU,I.INGCSC) IN (SELECT H51.HISTIPDOC,H51.HISCKEY,H51.HCTVIN51
       FROM HOSVITAL.HCCOM51 H51
       INNER JOIN HOSVITAL.TIPPROC T ON (T.TIPRCOD = H51.HCPRCTPOP AND T.TIPRCOD  =1 )
       INNER JOIN HOSVITAL.MAEPRO MAE ON (MAE.PRCODI=H51.HCPRCCOD AND MAE.PRNOMB LIKE ('%ECOGRA%'))
      WHERE   H51.HCPRCEST IN ('E','A','I'))  
GROUP BY   YEAR(I.INGFECADM),MONTH(I.INGFECADM);


 

--Salas de Cirugia: Cirugias realizadas CRUZ BLANCA

 
select YEAR(P.PROFEC),MONTH(P.PROFEC), COUNT(*)
FROM HOSVITAL.PROCIR P
WHERE P.PROFEC >= '2019-07-01' AND P.PROFEC<= '2019-10-31'  AND P.PROESTA IN (4,5) AND P.PROEPS   IN ('CS0101','SS0101')
GROUP BY   YEAR(P.PROFEC),MONTH(P.PROFEC);


-- Laboratorio Clinico: Examenes realizados CRUZ BLANCA

select YEAR(H.HISFHORAT),MONTH(H.HISFHORAT),  T.TIPRDES,COUNT(*)
FROM HOSVITAL.HCCOM1 H
INNER JOIN HOSVITAL.HCCOM51 H51 ON (H51.HISTIPDOC=H.HISTIPDOC AND H51.HISCKEY=H.HISCKEY AND H51.HISCSEC=H.HISCSEC AND H.FHCCODCTO   IN ('CS0101','SS0101')  )
INNER JOIN HOSVITAL.TIPPROC T ON (T.TIPRCOD = H51.HCPRCTPOP AND T.TIPRCOD  =2)
WHERE H.HISFHORAT >= '2019-07-01 00:00:00' AND H.HISFHORAT<= '2019-10-31 00:00:00'  AND  H51.HCPRCEST IN ('E','A','I')
GROUP BY   YEAR(H.HISFHORAT),MONTH(H.HISFHORAT), T.TIPRDES;


 -- Radiologia: Imágenes realizadas

 -- Urgencias y sistemas: Pacientes atendidos CRUZ BLANCA

-- UCI. Pacientes atendidos CRUZ BLANCA

SELECT * FROM HOSVITAL.INGRESOS;

SELECT YEAR(I.INGFECADM),MONTH(I.INGFECADM),COUNT(*)
FROM HOSVITAL.INGRESOS I
WHERE I.INGFECADM >= '2019-07-01 00:00:00' AND I.INGFECADM <= '2019-10-31 23:59:59' AND I.INGNIT   IN ('CS0101','SS0101') AND
   (I.MPTDOC,I.MPCEDU,I.INGCSC) IN (SELECT M.MPTDOC,M.MPCEDU,M.MACTVING
       FROM HOSVITAL.MAEATE M
        WHERE   M.MPMENI    IN ('CS0101','SS0101')  AND M.MAESTF NOT IN ('1','10') AND M.FACCODPAB IN (3,4,5,44,24,12,43,11) )
GROUP BY   YEAR(I.INGFECADM),MONTH(I.INGFECADM);


-- Hospitalizacion. Pacientes atendidos CRUZ BLANCA

SELECT * FROM HOSVITAL.MAEATE;  -- FACCODPAB
SELECT * FROM HOSVITAL.MAEPAB ; -- WHERE MPNOMP LIKE ('%UC%');;

SELECT YEAR(I.INGFECADM),MONTH(I.INGFECADM),COUNT(*)
FROM HOSVITAL.INGRESOS I
WHERE I.INGFECADM >= '2019-07-01 00:00:00' AND I.INGFECADM <= '2019-10-31 23:59:59' AND I.INGNIT   IN ('CS0101','SS0101') AND -- I.MPCODP  IN (3,4,5,11,12,13,14,15,16,17,22,23,24,25,26,27,28,29,30,34,36,43,44) AND
   (I.MPTDOC,I.MPCEDU,I.INGCSC) IN (SELECT M.MPTDOC,M.MPCEDU,M.MACTVING
       FROM HOSVITAL.MAEATE M
        WHERE   M.MPMENI    IN ('CS0101','SS0101')  AND M.MAESTF NOT IN ('1','10') AND M.FACCODPAB IN (3,4,5,11,12,13,14,15,16,17,22,23,24,25,26,27,28,29,30,34,36,43,44) )
GROUP BY   YEAR(I.INGFECADM),MONTH(I.INGFECADM);


----------------------------------------------------

----------------------------------------------------
----------------------------------------------------

-- PROCEDIMIENTOS DE fISIOTERAPIA

SELECT * FROM HOSVITAL.MAEATE WHERE MPNFAC = 105001		;
SELECT * FROM HOSVITAL.MAEATE2 WHERE MPNFAC = 105001		;


SELECT M.MPNFAC AS FACTURA, M2.PRCODI AS COD_PROD, MAEPRO.PRNOMB AS PROCEDIMIENTO , YEAR(M2.MAFEPR) AS AÑO,MONTH(M2.MAFEPR) AS MES,  MAEPAB.MPNOMP AS PABELLON, CASE WHEN M2.FCPTPOTRN='F' THEN 'Facturado'  WHEN M2.FCPTPOTRN='H' THEN 'Hoja de Gasto' END AS TIPO,
            CASE WHEN M2.MAESANUP ='S' THEN 'Anulado' ELSE 'Facturado' END AS Estado, M2.MACANPR AS CANTIDAD,M2.MPINTE as Vr_Unitario,M2.MAVATP AS VALOR_TOTAL

FROM HOSVITAL.MAEATE M
INNER JOIN HOSVITAL.MAEATE2 M2 ON (M2.MPNFAC = M.MPNFAC)
INNER JOIN HOSVITAL.MAEPAB MAEPAB ON  (MAEPAB.MPCODP=M2.MACODPAB)
INNER JOIN HOSVITAL.MAEPRO MAEPRO ON (MAEPRO.PRCODI=M2.PRCODI)
WHERE M.MATIPDOC='2' AND M.MATIPDOC = M2.MATIPDOC AND  M2.MAFEPR>='2019-01-01 00:00:00'
ORDER BY M.MPNFAC,M2.PRCODI;
