--  1. Se crea la tabla. erdon esta tabla la crea el Front-End Python

create table PRUEBAS.vistacex
as
(
SELECT C.CITNUM AS CITA, C.CITFEC AS FECHA,C.CITHORI AS HORA,CONSUL.CONSCOD AS CONSULTORIO,ESP.MENOME AS ESPECIALIDAD,MAE.MMNOMM AS MEDICO, CAP.MPNOMC AS PACIENTE,
CASE WHEN C.CITESTP='F' THEN 'Facturada' 
WHEN C.CITESTP='A' THEN 'Atendido' 
 WHEN C.CITESTP='N' THEN 'Cancelada' 
 WHEN C.CITESTP='R' THEN 'Reservada' 
 WHEN C.CITESTP='I' THEN 'Incumplida' 
 WHEN C.CITESTP='C' THEN 'Confirmada' END AS ESTADO_CITA,0 AS LLAMADA, 0 AS ATENDIDO
FROM HOSVITAL.CITMED C
INNER JOIN HOSVITAL.CITMED1 C1 ON (C1.CITNUM=C.CITNUM)
INNER JOIN HOSVITAL.CITMED2 C2 ON (C2.CITNUM=C1.CITNUM)
INNER JOIN HOSVITAL.CAPBAS CAP ON (CAP.MPTDOC=C1.CITTIPDOC AND CAP.MPCEDU=C1.CITCED)
INNER JOIN HOSVITAL.CONSUL CONSUL ON (CONSUL.CONSCOD=C.CITCONS)
INNER JOIN HOSVITAL.MAEMED1 MAE ON (MAE.MMCODM=C2.MMCODM)
INNER JOIN HOSVITAL.MAEESP ESP ON (ESP.MECODE=C2.MECODE)
WHERE C.CItnum=0  AND C.CITESTP IN ('C','R') AND c.citnum not in (select x.cita from hosvital.vistacex x) and
 (CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONSUL.CONSCOD,' '), MAE.MMNOMM) ,' ') ,ESP.MENOME), ' ') , CAST( C.CITFEC AS VARCHAR(12))),' ') ,C.CITHORI),' '),C.CITESTP),' '),CAP.MPNOMC) ) = (SELECT MIN( CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONSULX.CONSCOD,' '), MAEX.MMNOMM) ,' ') ,ESPX.MENOME), ' ') , CAST(CX.CITFEC AS VARCHAR(12))),' ') ,CX.CITHORI),' '),CX.CITESTP),' ') ,CAPX.MPNOMC) )
FROM HOSVITAL.CITMED CX
INNER JOIN HOSVITAL.CITMED1 CX1 ON (CX1.CITNUM=CX.CITNUM)
INNER JOIN HOSVITAL.CITMED2 CX2 ON (CX2.CITNUM=CX1.CITNUM)
INNER JOIN HOSVITAL.CAPBAS CAPX ON (CAPX.MPTDOC=CX1.CITTIPDOC AND CAPX.MPCEDU=CX1.CITCED)
INNER JOIN HOSVITAL.CONSUL CONSULX ON (CONSULX.CONSCOD=CX.CITCONS)
INNER JOIN HOSVITAL.MAEMED1 MAEX ON (MAEX.MMCODM=CX2.MMCODM)
INNER JOIN HOSVITAL.MAEESP ESPX ON (ESPX.MECODE=CX2.MECODE)
WHERE CX.Citnum=0  AND CX.CITESTP IN ('C','R') AND CAPX.MPTDOC=C1.CITTIPDOC AND CAPX.MPCEDU=C1.CITCED )) with data;

select * from HOSVITAL.vistacex;

-- 2. Se insertan en la tabla vistacex desde el dia de hoy o ayer como lo indiquen.

--  delete from hosvital.vistacex;

SELECT * from hosvital.citmed2;

SELECT count(*) from hosvital.citmed2;

insert into hosvital.vistacex
SELECT C.CITNUM AS CITA, C.CITFEC AS FECHA,C.CITHORI AS HORA,CONSUL.CONSCOD AS CONSULTORIO,ESP.MENOME AS ESPECIALIDAD,MAE.MMNOMM AS MEDICO, CAP.MPNOMC AS PACIENTE,
CASE WHEN C.CITESTP='F' THEN 'Facturada' 
WHEN C.CITESTP='A' THEN 'Atendido' 
 WHEN C.CITESTP='N' THEN 'Cancelada' 
 WHEN C.CITESTP='R' THEN 'Reservada' 
 WHEN C.CITESTP='I' THEN 'Incumplida' 
 WHEN C.CITESTP='C' THEN 'Confirmada' END AS ESTADO_CITA,0 AS LLAMADA, 0 AS ATENDIDO
FROM HOSVITAL.CITMED C
INNER JOIN HOSVITAL.CITMED1 C1 ON (C1.CITNUM=C.CITNUM)
INNER JOIN HOSVITAL.CITMED2 C2 ON (C2.CITNUM=C1.CITNUM)
INNER JOIN HOSVITAL.CAPBAS CAP ON (CAP.MPTDOC=C1.CITTIPDOC AND CAP.MPCEDU=C1.CITCED)
INNER JOIN HOSVITAL.CONSUL CONSUL ON (CONSUL.CONSCOD=C.CITCONS)
INNER JOIN HOSVITAL.MAEMED1 MAE ON (MAE.MMCODM=C2.MMCODM)
INNER JOIN HOSVITAL.MAEESP ESP ON (ESP.MECODE=C2.MECODE)
WHERE C.CITFEC>='2021-07-30' AND C.CITESTP IN ('C','R') AND c.citnum not in (select x.cita from hosvital.vistacex x) and
 (CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONSUL.CONSCOD,' '), MAE.MMNOMM) ,' ') ,ESP.MENOME), ' ') , CAST( C.CITFEC AS VARCHAR(12))),' ') ,C.CITHORI),' '),C.CITESTP),' '),CAP.MPNOMC) ) = (SELECT MIN( CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONSULX.CONSCOD,' '), MAEX.MMNOMM) ,' ') ,ESPX.MENOME), ' ') , CAST(CX.CITFEC AS VARCHAR(12))),' ') ,CX.CITHORI),' '),CX.CITESTP),' ') ,CAPX.MPNOMC) )
FROM HOSVITAL.CITMED CX
INNER JOIN HOSVITAL.CITMED1 CX1 ON (CX1.CITNUM=CX.CITNUM)
INNER JOIN HOSVITAL.CITMED2 CX2 ON (CX2.CITNUM=CX1.CITNUM)
INNER JOIN HOSVITAL.CAPBAS CAPX ON (CAPX.MPTDOC=CX1.CITTIPDOC AND CAPX.MPCEDU=CX1.CITCED)
INNER JOIN HOSVITAL.CONSUL CONSULX ON (CONSULX.CONSCOD=CX.CITCONS)
INNER JOIN HOSVITAL.MAEMED1 MAEX ON (MAEX.MMCODM=CX2.MMCODM)
INNER JOIN HOSVITAL.MAEESP ESPX ON (ESPX.MECODE=CX2.MECODE)
WHERE CX.CITFEC>='2021-07-30' AND CX.CITESTP IN ('C','R') AND CAPX.MPTDOC=C1.CITTIPDOC AND CAPX.MPCEDU=C1.CITCED );




select * from hosvital.citmed where citfec >= '2021-07-30' order by citnum;

select COUNT(*) from hosvital.citmed where citfec >= '2021-07-30';  -- hay 6 de diferencia
select COUNT(*) from hosvital.citmed2 where citfecme >= '2021-07-30';  -- 138
select count(*) from hosvital.vistacex; -- 132/140/145/146/155/166
select * from hosvital.vistacex order by cita;
select * from hosvital.vistacex where fecha='2021-07-30'; --;and consultorio=140;

select * from hosvital.consul where conscod=50;

select * from hosvital.consul where conscod in (select consultorio from hosvital.vistacex  where atendido=0);

select count(*) from hosvital.vistacex  where fecha='2021-07-30';
select * from hosvital.citmed  where citfec='2021-07-30' and citestP in ('C','R'); --2





--3. Se crean y activan el triggers y el triger Actualizar con cada Confirmacion de Citas medicas en hosvital

CREATE OR REPLACE TRIGGER HOSVITAL.ACTIVACITA
   AFTER INSERT   ON HOSVITAL.CITMED2
   REFERENCING NEW AS NUEVA OLD AS O FOR EACH ROW
	Insert into HOSVITAL.vistacex
	SELECT C.CITNUM AS CITA, C.CITFEC AS FECHA,C.CITHORI AS HORA,CONSUL.CONSCOD AS CONSULTORIO,ESP.MENOME AS ESPECIALIDAD,MAE.MMNOMM AS MEDICO, CAP.MPNOMC AS PACIENTE,
	CASE WHEN C.CITESTP='F' THEN 'Facturada' 
	WHEN C.CITESTP='A' THEN 'Atendido' 
	 WHEN C.CITESTP='N' THEN 'Cancelada' 
	 WHEN C.CITESTP='R' THEN 'Reservada' 
	 WHEN C.CITESTP='I' THEN 'Incumplida' 
	 WHEN C.CITESTP='C' THEN 'Confirmada' END AS ESTADO_CITA,0 AS LLAMADA, 0 AS ATENDIDO
	FROM HOSVITAL.CITMED C
	INNER JOIN HOSVITAL.CITMED1 C1 ON (C1.CITNUM=C.CITNUM)
	INNER JOIN HOSVITAL.CITMED2 C2 ON (C2.CITNUM=C1.CITNUM)
	INNER JOIN HOSVITAL.CAPBAS CAP ON (CAP.MPTDOC=C1.CITTIPDOC AND CAP.MPCEDU=C1.CITCED)
	INNER JOIN HOSVITAL.CONSUL CONSUL ON (CONSUL.CONSCOD=C.CITCONS)
	INNER JOIN HOSVITAL.MAEMED1 MAE ON (MAE.MMCODM=C2.MMCODM)
	INNER JOIN HOSVITAL.MAEESP ESP ON (ESP.MECODE = C2.MECODE)
	WHERE C.CITNUM = NUEVA.CITNUM  AND C.CITESTP IN ('C','R') AND -- c.citnum not in (select x.cita from HOSVITAL.vistacex x) and
	 (CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONSUL.CONSCOD,' '), MAE.MMNOMM) ,' ') ,ESP.MENOME), ' ') , CAST( C.CITFEC AS 		VARCHAR(12))),' ') ,C.CITHORI),' '),C.CITESTP),' '),CAP.MPNOMC) ) = (SELECT MIN( CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONSULX.CONSCOD,' '), 	MAEX.MMNOMM) ,' ') ,ESPX.MENOME), ' ') , CAST(CX.CITFEC AS VARCHAR(12))),' ') ,CX.CITHORI),' '),CX.CITESTP),' ') ,CAPX.MPNOMC) )
	FROM HOSVITAL.CITMED CX
	INNER JOIN HOSVITAL.CITMED1 CX1 ON (CX1.CITNUM=CX.CITNUM)
	INNER JOIN HOSVITAL.CITMED2 CX2 ON (CX2.CITNUM=CX1.CITNUM)
	INNER JOIN HOSVITAL.CAPBAS CAPX ON (CAPX.MPTDOC=CX1.CITTIPDOC AND CAPX.MPCEDU=CX1.CITCED)
	INNER JOIN HOSVITAL.CONSUL CONSULX ON (CONSULX.CONSCOD=CX.CITCONS)
	INNER JOIN HOSVITAL.MAEMED1 MAEX ON (MAEX.MMCODM=CX2.MMCODM)
	INNER JOIN HOSVITAL.MAEESP ESPX ON (ESPX.MECODE=CX2.MECODE)
	WHERE CX.CITNUM = NUEVA.CITNUM AND CX.CITESTP IN ('C','R') AND CAPX.MPTDOC=C1.CITTIPDOC AND CAPX.MPCEDU=C1.CITCED );



-- Trigger del UPDATE cuando confirmen la cita medica


CREATE OR REPLACE TRIGGER HOSVITAL.ACTUALIZACITA
   AFTER UPDATE   ON HOSVITAL.CITMED
   REFERENCING NEW AS NUEVA OLD AS O FOR EACH ROW
	UPDATE HOSVITAL.vistacex
	SET ESTADO_CITA='Confirmada'
	WHERE CITA = NUEVA.CITNUM ;



select count(*) from hosvital.vistacex;
