select * from hosvital.movcont3 where doccod='PCP' AND MVCNRO = 2303;
select * from hosvital.movcont2 where doccod='PCP' AND MVCNRO = 2303;

UPDATE  hosvital.movcont2 
SET EMPCOD='01'
where doccod='PCP' AND MVCNRO = 2303 AND  EMPCOD ='';

DELETE FROM HOSVITAL.MOVCONT3 WHERE doccod='PCP' AND MVCNRO = 2303 AND EMPCOD='';

UPDATE    hosvital.movcont3 SET  MVCEST='N' where doccod='PCP' AND MVCNRO = 2303;

UPDATE    hosvital.movcont2 SET  MVCVLRLC =0, MVCVLR=0
 where doccod='PCP' AND MVCNRO = 2303;

SELECT * FROM HOSVITAL.NIMOVCON1 WHERE DOCCOD = 'PCP' AND NIMCNRO=2303;

 	
select * from hosvital.movcont3 where doccod='PCP' AND MVCNRO = 2306;
select * from hosvital.movcont2 where doccod='PCP' AND MVCNRO = 2306;

UPDATE  hosvital.movcont2 
SET EMPCOD='01'
where doccod='PCP' AND MVCNRO = 2306 AND  EMPCOD ='';

DELETE FROM HOSVITAL.MOVCONT3 WHERE doccod='PCP' AND MVCNRO = 2306 AND EMPCOD='';



SELECT * FROM HOSVITAL.NIMOVCON1 WHERE DOCCOD = 'PCP' AND NIMCNRO=2303;

UPDATE  HOSVITAL.NIMOVCON1 
SET NIMC1EST='N'
WHERE DOCCOD = 'PCP' AND NIMCNRO=2303;

DELETE FROM HOSVITAL.NIMOVCON1  WHERE doccod='PCP' AND NIMCNRO  = 2303 AND EMPCOD='';

SELECT *  FROM HOSVITAL.NIMOVCON2 WHERE doccod='PCP' AND NIMCNRO  = 2303 ;


UPDATE    hosvital.NIMOVCON2
 SET  NIMC2VL =0, NIMC2VLR=0
 where doccod='PCP' AND NIMCNRO = 2303;

SELECT * FROM HOSVITAL.NIMOVCON1 WHERE DOCCOD = 'PCP' AND NIMCNRO=2306;
SELECT *  FROM HOSVITAL.NIMOVCON2 WHERE doccod='PCP' AND NIMCNRO  = 2306;

DELETE FROM HOSVITAL.NIMOVCON1  WHERE doccod='PCP' AND NIMCNRO  = 2306 AND EMPCOD='';

