SELECT MPNFAC,FACFCH,MACTVING  FROM HOSVITAL.MAEATE WHERE MPCEDU ='1000118344';


SELECT M.MPCEDU AS PACIENTE, M3.MSRESO AS COD_INSUMO, MAE1.MSNOMG AS INSUMO , YEAR(M3.MAFCSU) AS AÑO,MONTH(M3.MAFCSU) AS MES,  MAEPAB.MPNOMP AS PABELLON,
CASE WHEN M3.FCSTPOTRN='F' THEN 'Facturado'  WHEN M3.FCSTPOTRN='H' THEN 'Hoja de Gasto' END AS TIPO,
M3.MACANS AS CANTIDAD,M3.MAVALU as Vr_Unitario,M3.MAVATS AS VALOR_TOTAL
FROM HOSVITAL.MAEATE M
INNER JOIN HOSVITAL.MAEATE3 M3 ON (M3.MPNFAC = M.MPNFAC)
INNER JOIN HOSVITAL.MAESUM1 MAE1 ON (MAE1.MSRESO = M3.MSRESO)
INNER JOIN HOSVITAL.MAEPAB MAEPAB ON  (MAEPAB.MPCODP=M.FACCODPAB)
WHERE M.MATIPDOC='2' AND M.MATIPDOC = M3.MATIPDOC AND M3.MAESANUS<> 'S' AND  M3.MAFCSU>='2019-01-01 00:00:00' AND M3.MSRESO IN
('S55201','S55206','S55208')
ORDER BY M.MPNFAC,M3.MSRESO, M3.MAFCSU;



SELECT M.MPCEDU AS PACIENTE, M3.MSRESO AS COD_INSUMO, MAE1.MSNOMG AS INSUMO , M3.MAFCSU,  YEAR(M3.MAFCSU) AS AÑO,MONTH(M3.MAFCSU) AS MES,  MAEPAB.MPNOMP AS PABELLON,
CASE WHEN M3.FCSTPOTRN='F' THEN 'Facturado'  WHEN M3.FCSTPOTRN='H' THEN 'Hoja de Gasto' END AS TIPO,
M3.MACANS AS CANTIDAD,M3.MAVALU as Vr_Unitario,M3.MAVATS AS VALOR_TOTAL,MAEPAB11.MPNUMC, CAST(MAEPAB11.HISCAMFEC AS VARCHAR(10))||' '||MAEPAB11.HISCAMHOR OCUPA,
(SELECT CAST(O1.HISCAMFEC AS VARCHAR(10))||' '||O1.HISCAMHOR
FROM HOSVITAL.MAEPAB11 O1
WHERE O1.MPTDOC=M.MPTDOC AND O1.MPCEDU = M.MPCEDU AND O1.hiscnsing=M.MACTVING AND O1.MPCODP = MAEPAB11.MPCODP AND O1.MPNUMC= MAEPAB11.MPNUMC AND
    O1.HISCAMEDO='L'  AND O1.HISCAMCTV = (SELECT MIN (O2.HISCAMCTV)
			FROM HOSVITAL.MAEPAB11 O2
			WHERE O2.MPTDOC=O1.MPTDOC AND O2.MPCEDU = O1.MPCEDU AND O2.hiscnsing=O1.HISCNSING AND O2.MPCODP = O1.MPCODP AND O2.MPNUMC= O1.MPNUMC AND
			 O2.HISCAMEDO='L' 
		            )                                   

) LIBERA
FROM HOSVITAL.MAEATE M
INNER JOIN HOSVITAL.MAEATE3 M3 ON (M3.MPNFAC = M.MPNFAC)
INNER JOIN HOSVITAL.MAESUM1 MAE1 ON (MAE1.MSRESO = M3.MSRESO)
INNER JOIN HOSVITAL.MAEPAB MAEPAB ON  (MAEPAB.MPCODP=M.FACCODPAB)
INNER JOIN HOSVITAL.MAEPAB11 MAEPAB11 ON  (maepab11.mptdoc = m.mptdoc and maepab11.mpcedu = m.mpcedu and maepab11.hiscnsing = m.mactving  )
WHERE M.MATIPDOC='2' AND M.MATIPDOC = M3.MATIPDOC AND M3.MAESANUS<> 'S' AND  M3.MAFCSU>='2019-01-01 00:00:00' AND M3.MSRESO IN
('S55201','S55206','S55208')  -- and m.mpcedu = '3068772' 
and maepab11.hiscamedo='O'
ORDER BY M.MPNFAC,M3.MSRESO, M3.MAFCSU;

select * from hosvital.maepab11 WHERE MPCEDU= '1000118344';




SELECT M.MPCEDU AS PACIENTE, M3.MSRESO AS COD_INSUMO, MAE1.MSNOMG AS INSUMO , M3.MAFCSU,  YEAR(M3.MAFCSU) AS AÑO,MONTH(M3.MAFCSU) AS MES,  MAEPAB.MPNOMP AS PABELLON,
CASE WHEN M3.FCSTPOTRN='F' THEN 'Facturado'  WHEN M3.FCSTPOTRN='H' THEN 'Hoja de Gasto' END AS TIPO,
M3.MACANS AS CANTIDAD,M3.MAVALU as Vr_Unitario,M3.MAVATS AS VALOR_TOTAL,MAEPAB11.MPNUMC, CAST(MAEPAB11.HISCAMFEC AS VARCHAR(10))||' '||MAEPAB11.HISCAMHOR OCUPA,
(SELECT CAST(O1.HISCAMFEC AS VARCHAR(10))||' '||O1.HISCAMHOR
FROM HOSVITAL.MAEPAB11 O1
WHERE O1.MPTDOC=M.MPTDOC AND O1.MPCEDU = M.MPCEDU AND O1.hiscnsing=M.MACTVING AND O1.MPCODP = MAEPAB11.MPCODP AND O1.MPNUMC= MAEPAB11.MPNUMC AND
    O1.HISCAMEDO='L'  AND O1.HISCAMCTV = (SELECT MIN (O2.HISCAMCTV)
			FROM HOSVITAL.MAEPAB11 O2
			WHERE O2.MPTDOC=O1.MPTDOC AND O2.MPCEDU = O1.MPCEDU AND O2.hiscnsing=O1.HISCNSING AND O2.MPCODP = O1.MPCODP AND O2.MPNUMC= O1.MPNUMC AND
			 O2.HISCAMEDO='L'  )                                   

) LIBERA
FROM HOSVITAL.MAEATE M
INNER JOIN HOSVITAL.MAEATE3 M3 ON (M3.MPNFAC = M.MPNFAC)
INNER JOIN HOSVITAL.MAESUM1 MAE1 ON (MAE1.MSRESO = M3.MSRESO)
INNER JOIN HOSVITAL.MAEPAB MAEPAB ON  (MAEPAB.MPCODP=M.FACCODPAB)
INNER JOIN HOSVITAL.MAEPAB11 MAEPAB11 ON  (maepab11.mptdoc = m.mptdoc and maepab11.mpcedu = m.mpcedu and maepab11.hiscnsing = m.mactving  )
WHERE M.MATIPDOC='2' AND M.MATIPDOC = M3.MATIPDOC AND M3.MAESANUS<> 'S' AND  M3.MAFCSU>='2019-01-01 00:00:00' AND M3.MSRESO IN
('S55201','S55206','S55208')  and maepab11.hiscamedo='O'
ORDER BY M.MPCEDU, M3.MAFCSU,M3.MSRESO;



-- Veamos aver que pasa el DEFINITIVO



SELECT M.MPCEDU AS PACIENTE, M3.MSRESO AS COD_INSUMO, M3.MACSCS, MAE1.MSNOMG AS INSUMO , M3.MAFCSU,  YEAR(M3.MAFCSU) AS AÑO,MONTH(M3.MAFCSU) AS MES,  MAEPAB.MPNOMP AS PABELLON,
CASE WHEN M3.FCSTPOTRN='F' THEN 'Facturado'  WHEN M3.FCSTPOTRN='H' THEN 'Hoja de Gasto' END AS TIPO,
M3.MACANS AS CANTIDAD,M3.MAVALU as Vr_Unitario,M3.MAVATS AS VALOR_TOTAL,MAEPAB11.MPNUMC, CAST(MAEPAB11.HISCAMFEC AS VARCHAR(10))||' '||MAEPAB11.HISCAMHOR OCUPA,
(SELECT CAST(O1.HISCAMFEC AS VARCHAR(10))||' '||O1.HISCAMHOR
FROM HOSVITAL.MAEPAB11 O1
WHERE O1.MPTDOC=M.MPTDOC AND O1.MPCEDU = M.MPCEDU AND O1.hiscnsing=M.MACTVING AND O1.MPCODP = MAEPAB11.MPCODP AND O1.MPNUMC= MAEPAB11.MPNUMC AND
    O1.HISCAMEDO='L'  AND                 O1.HISCAMCTV = (SELECT MIN (O2.HISCAMCTV)
			FROM HOSVITAL.MAEPAB11 O2
			WHERE O2.MPTDOC=O1.MPTDOC AND O2.MPCEDU = O1.MPCEDU AND O2.hiscnsing=O1.HISCNSING AND O2.MPCODP = O1.MPCODP AND O2.MPNUMC= O1.MPNUMC AND
			 O2.HISCAMEDO='L'  AND    
                                                                                                    M3.MAFCSU         BETWEEN          (CAST(MAEPAB11.HISCAMFEC AS VARCHAR(10))||' '||MAEPAB11.HISCAMHOR)           AND   	 (CAST(O1.HISCAMFEC AS VARCHAR(10))||' '||O1.HISCAMHOR)

  )   	                       				

) LIBERA
FROM HOSVITAL.MAEATE M
INNER JOIN HOSVITAL.MAEATE3 M3 ON (M3.MPNFAC = M.MPNFAC)
INNER JOIN HOSVITAL.MAESUM1 MAE1 ON (MAE1.MSRESO = M3.MSRESO)
INNER JOIN HOSVITAL.MAEPAB MAEPAB ON  (MAEPAB.MPCODP=M.FACCODPAB)
INNER JOIN HOSVITAL.MAEPAB11 MAEPAB11 ON  (maepab11.mptdoc = m.mptdoc and maepab11.mpcedu = m.mpcedu and maepab11.hiscnsing = m.mactving  )
WHERE M.MATIPDOC='2' AND M.MATIPDOC = M3.MATIPDOC AND M3.MAESANUS<> 'S' AND  M3.MAFCSU>='2019-01-01 00:00:00' AND M3.MSRESO IN
('S55201','S55206','S55208')  and maepab11.hiscamedo='O'   AND M.MAESTF NOT IN ('1','10')
ORDER BY M.MPCEDU, M3.MAFCSU,M3.MSRESO;

SELECT * FROM  HOSVITAL.MAEATE3;

