SELECT HOSVITAL.TMPFAC.TFCEDU AS CEDULA_PAC, HOSVITAL.CAPBAS.MPNOMC AS NOMBRE_PAC, HOSVITAL.TMPFAC.TMCTVING AS CVO_ING, HOSVITAL.TMPFAC.TFCCODPAB AS COD_PABELLON, HOSVITAL.MAEPAB.MPNOMP AS PABELLON, HOSVITAL.TMPFAC.TFCCODCAM AS CAMA, HOSVITAL.MAEEMP.MENOMB AS CONTRATO, HOSVITAL.TMPFAC.TFFCHI AS FECHA_INGRESO, HOSVITAL.TMPFAC.MPFESH AS FECHA_EGRESO, SUM(HOSVITAL.TMPFAC1.TFVATP) AS VL_TOTAL, CASE HOSVITAL.TMPFAC.CLAPRO WHEN '1' THEN 'FACTURACION' WHEN '2' THEN 'FACTURACION' WHEN '3' THEN 'FACTURACION' WHEN '4' THEN 'FACTURACION' WHEN '5' THEN 'FACTURACION' WHEN '6' THEN 'REFACTURACION' WHEN '7' THEN 'REFACTURACION' WHEN '8' THEN 'REFACTURACION' WHEN '9' THEN 'REFACTURACION' WHEN '10' THEN 'REFACTURACION' END AS ESTADO_ING,  CASE HOSVITAL.TMPFAC.CLAPRO WHEN '1' THEN 'AMBULATORIO' WHEN '2' THEN 'HOSPITALIZACION' WHEN '3' THEN 'URGENCIAS' WHEN '4' THEN 'TRIAGE' WHEN '5' THEN 'TRAT. ESPECIAL' WHEN '6' THEN 'AMBULATORIO' WHEN '7' THEN 'HOSPITALIZACION' WHEN '8' THEN 'URGENCIAS' WHEN '9' THEN 'TRIAGE' WHEN '10' THEN 'TRAT. ESPECIAL' END AS TIPO_ESTADO
FROM (HOSVITAL.CAPBAS INNER JOIN (HOSVITAL.TMPFAC1
 INNER JOIN (HOSVITAL.TMPFAC INNER JOIN HOSVITAL.MAEEMP ON HOSVITAL.TMPFAC.TFMENI = HOSVITAL.MAEEMP.MENNIT) ON (HOSVITAL.TMPFAC1.TMCTVING = HOSVITAL.TMPFAC.TMCTVING) AND (HOSVITAL.TMPFAC1.TFTDOC = HOSVITAL.TMPFAC.TFTDOC) AND (HOSVITAL.TMPFAC1.TFCEDU = HOSVITAL.TMPFAC.TFCEDU)) ON (HOSVITAL.CAPBAS.MPTDOC = HOSVITAL.TMPFAC.TFTDOC) AND (HOSVITAL.CAPBAS.MPCEDU = HOSVITAL.TMPFAC.TFCEDU)) INNER JOIN HOSVITAL.MAEPAB ON HOSVITAL.TMPFAC.TFCCODPAB = HOSVITAL.MAEPAB.MPCODP
WHERE HOSVITAL.TMPFAC1.TFESTAANU1<>'S' AND HOSVITAL.TMPFAC1.TFPTPOTRN<>'H'
GROUP BY HOSVITAL.TMPFAC.TFCEDU, HOSVITAL.CAPBAS.MPNOMC, HOSVITAL.TMPFAC.TMCTVING, HOSVITAL.TMPFAC.TFCCODPAB, HOSVITAL.MAEPAB.MPNOMP, HOSVITAL.TMPFAC.TFCCODCAM, HOSVITAL.MAEEMP.MENOMB, HOSVITAL.TMPFAC.TFFCHI, HOSVITAL.TMPFAC.MPFESH, HOSVITAL.TMPFAC.CLAPRO

UNION

SELECT HOSVITAL.TMPFAC.TFCEDU, HOSVITAL.CAPBAS.MPNOMC, HOSVITAL.TMPFAC.TMCTVING, HOSVITAL.TMPFAC.TFCCODPAB, HOSVITAL.MAEPAB.MPNOMP, HOSVITAL.TMPFAC.TFCCODCAM, HOSVITAL.MAEEMP.MENOMB, HOSVITAL.TMPFAC.TFFCHI, HOSVITAL.TMPFAC.MPFESH, SUM (HOSVITAL.TMPFAC2.TFVATS), CASE HOSVITAL.TMPFAC.CLAPRO WHEN '1' THEN 'FACTURACION' WHEN '2' THEN 'FACTURACION' WHEN '3' THEN 'FACTURACION' WHEN '4' THEN 'FACTURACION' WHEN '5' THEN 'FACTURACION' WHEN '6' THEN 'REFACTURACION' WHEN '7' THEN 'REFACTURACION' WHEN '8' THEN 'REFACTURACION' WHEN '9' THEN 'REFACTURACION' WHEN '10' THEN 'REFACTURACION' END,  CASE HOSVITAL.TMPFAC.CLAPRO WHEN '1' THEN 'AMBULATORIO' WHEN '2' THEN 'HOSPITALIZACION' WHEN '3' THEN 'URGENCIAS' WHEN '4' THEN 'TRIAGE' WHEN '5' THEN 'TRAT. ESPECIAL' WHEN '6' THEN 'AMBULATORIO' WHEN '7' THEN 'HOSPITALIZACION' WHEN '8' THEN 'URGENCIAS' WHEN '9' THEN 'TRIAGE' WHEN '10' THEN 'TRAT. ESPECIAL' END
FROM HOSVITAL.TMPFAC2
 INNER JOIN ((HOSVITAL.CAPBAS 
INNER JOIN (HOSVITAL.TMPFAC INNER JOIN HOSVITAL.MAEEMP ON HOSVITAL.TMPFAC.TFMENI = HOSVITAL.MAEEMP.MENNIT) ON (HOSVITAL.CAPBAS.MPCEDU = HOSVITAL.TMPFAC.TFCEDU) AND (HOSVITAL.CAPBAS.MPTDOC = HOSVITAL.TMPFAC.TFTDOC))
 INNER JOIN HOSVITAL.MAEPAB ON HOSVITAL.TMPFAC.TFCCODPAB = HOSVITAL.MAEPAB.MPCODP) ON (HOSVITAL.TMPFAC2.TMCTVING = HOSVITAL.TMPFAC.TMCTVING) AND (HOSVITAL.TMPFAC2.TFTDOC = HOSVITAL.TMPFAC.TFTDOC) AND (HOSVITAL.TMPFAC2.TFCEDU = HOSVITAL.TMPFAC.TFCEDU)
WHERE HOSVITAL.TMPFAC2.TFESTAANU2<>'S' AND HOSVITAL.TMPFAC2.TFSTPOTRN<>'H' 
GROUP BY HOSVITAL.TMPFAC.TFCEDU, HOSVITAL.CAPBAS.MPNOMC, HOSVITAL.TMPFAC.TMCTVING, HOSVITAL.TMPFAC.TFCCODPAB, HOSVITAL.MAEPAB.MPNOMP, HOSVITAL.TMPFAC.TFCCODCAM, HOSVITAL.MAEEMP.MENOMB, HOSVITAL.TMPFAC.TFFCHI, HOSVITAL.TMPFAC.MPFESH, HOSVITAL.TMPFAC.CLAPRO;

-- Query No 1
select c.mptdoc as tipo_doc, c.mpcedu as documento,c.mpnomc as nombre_paciente,i.ingcsc as ingreso,t.tfccodpab as pabellon,m.mpnomp as nombre_pabellon, t.tfccodcam as cama_fac,
m1.menomb as contrato,i.ingfecadm as ingreso, i.ingfecegr as egreso,
(select m11.mpnumc
 from hosvital.maepab11 m11
 where  m11.mptdoc = t.tftdoc and m11.mpcedu = t.tfcedu and m11.hiscnsing = t.tmctving and m11.hiscamedo='O' and m11.hiscamctv =
		(select max(m111.hiscamctv)
		from hosvital.maepab11 m111
		 where  m111.mptdoc = m11.mptdoc and m111.mpcedu = m11.mpcedu and m111.hiscnsing = m11.hiscnsing and m111.hiscamedo=m11.hiscamedo)
) as camaCenso,
(select sum(tfvatp)
from hosvital.tmpfac1 t2
where t.tftdoc = t.tftdoc and t2.tfcedu=t.tfcedu and t2.tmctving = t.tmctving and t2.tfptpotrn='F' and t2.tfestaanu1 <>'S'
) as procedimientos,
(select sum(tfvats)
from hosvital.tmpfac2 t2
where t.tftdoc = t.tftdoc and t2.tfcedu=t.tfcedu and t2.tmctving = t.tmctving and t2.tfstpotrn='F' and t2.tfestaanu2 <> 'S'
) as suministros,
CASE t.CLAPRO WHEN '1' THEN 'FACTURACION' WHEN '2' THEN 'FACTURACION' WHEN '3' THEN 'FACTURACION' WHEN '4' THEN 'FACTURACION' WHEN '5' THEN 'FACTURACION' WHEN '6' THEN 'REFACTURACION' WHEN '7' THEN 'REFACTURACION' WHEN '8' THEN 'REFACTURACION' WHEN '9' THEN 'REFACTURACION' WHEN '10' THEN 'REFACTURACION' END AS ESTADO_ING,  CASE t.CLAPRO WHEN '1' THEN 'AMBULATORIO' WHEN '2' THEN 'HOSPITALIZACION' WHEN '3' THEN 'URGENCIAS' WHEN '4' THEN 'TRIAGE' WHEN '5' THEN 'TRAT. ESPECIAL' WHEN '6' THEN 'AMBULATORIO' WHEN '7' THEN 'HOSPITALIZACION' WHEN '8' THEN 'URGENCIAS' WHEN '9' THEN 'TRIAGE' WHEN '10' THEN 'TRAT. ESPECIAL' END AS TIPO_ESTADO
from hosvital.ingresos i
inner join hosvital.tmpfac t on (t.tfcedu = i.mpcedu and t.tftdoc=i.mptdoc and t.tmctving= i.ingcsc)
inner join hosvital.capbas c on (c.mpcedu = t.tfcedu and c.mptdoc = t.tftdoc)
inner join hosvital.maepab m on (m.mpcodp = t.tfccodpab)
inner join hosvital.maeemp m1 on (m1.mennit = t.tfmeni);


