SELECT HOSVITAL.MAEPRO.PRCODI AS CODIGO, HOSVITAL.PORTAR1.PTCODI, HOSVITAL.PORTAR.PTDESC AS PORTAFOLIO, HOSVITAL.HOMPROC.TRFCOD AS TARIFA, HOSVITAL.HOMPROC.HOMPRODSC AS DESCRIPCION,
 HOSVITAL.HOMPROC.HOMPROVLR  AS VALOR, HOSVITAL.PORTAR1.PTPORC AS PORCENTAGE, ((HOSVITAL.HOMPROC.HOMPROVLR*HOSVITAL.PORTAR1.PTPORC)/100) AS VALOR
FROM HOSVITAL.MAEPRO 
INNER JOIN HOSVITAL.PORTAR1 ON (HOSVITAL.MAEPRO.PRCODI = HOSVITAL.PORTAR1.PRCODI) 
INNER JOIN HOSVITAL.HOMPROC ON (HOSVITAL.PORTAR1.PRCODI = HOSVITAL.HOMPROC.PRCODI) 
INNER JOIN HOSVITAL.PORTAR ON (HOSVITAL.PORTAR1.PTCODI = HOSVITAL.PORTAR.PTCODI) 
WHERE HOSVITAL.HOMPROC.TRFCOD='9' AND HOSVITAL.PORTAR1.PTCODI= '31';

SELECT * FROM HOSVITAL.PORTAR1 WHERE PTCODI='31' AND PRCODI='A32402';
SELECT * FROM HOSVITAL.HOMPROC WHERE PRCODI='A32402';  -- 15625.00	

SELECT HOSVITAL.MAEPRO.PRCODI AS CODIGO, HOSVITAL.PORTAR1.PTCODI, HOSVITAL.PORTAR.PTDESC AS PORTAFOLIO, HOSVITAL.HOMPROC.TRFCOD AS TARIFA, HOSVITAL.HOMPROC.HOMPRODSC AS DESCRIPCION,
 HOSVITAL.HOMPROC.HOMPROVLR  AS VALOR, HOSVITAL.PORTAR1.PTPORC AS PORCENTAGE, (HOSVITAL.HOMPROC.HOMPROVLR*HOSVITAL.PORTAR1.PTPORC)/100.00 AS VALOR
FROM HOSVITAL.MAEPRO 
INNER JOIN HOSVITAL.PORTAR1 ON (HOSVITAL.MAEPRO.PRCODI = HOSVITAL.PORTAR1.PRCODI) 
LEFT  JOIN HOSVITAL.HOMPROC ON (HOSVITAL.PORTAR1.PRCODI = HOSVITAL.HOMPROC.PRCODI AND HOSVITAL.HOMPROC.TRFCOD=HOSVITAL.PORTAR1.TRFCOD) 
INNER JOIN HOSVITAL.PORTAR ON (HOSVITAL.PORTAR1.PTCODI = HOSVITAL.PORTAR.PTCODI) 
WHERE  HOSVITAL.PORTAR1.PTCODI= '31' ; -- AND HOSVITAL.MAEPRO.PRCODI= 'A32402';

