-- Desde Julio del añopasado
-- Salud Total
-- Por centro decosto
-- Mediacmentos e Insumos
-- Es mes a Mes
-- Discriminarlos con esos items
-- 

SELECT * FROM HOSVITAL.MAEEMP;
SELECT * FROM HOSVITAL.MAEATE;
SELECT * FROM HOSVITAL.MAEATE2;
SELECT * FROM HOSVITAL.MAEATE3;
SELECT * FROM HOSVITAL.TIPPROC;
SELECT * FROM HOSVITAL.MAEPRO;
SELECT * FROM HOSVITAL.CENCOST;

SELECT * FROM HOSVITAL.MAEEMP WHERE MENOMB LIKE ('%SALUD%TOTA%');  -- 290 , 161 

-- Este es el query de SALUD TOTAL


SELECT  I.MPTDOC TIPO_DOC ,I.MPCEDU DOCUMENTO, I.INGCSC AS INGRESO,M.MPNFAC FACTURA, M.FACFCH FECHA_FACTURA, M2.MACSCP, M2.PRCODI,MAEPRO.PRNOMB, M2.MACANPR,M2.MAVATP, TIP.TIPRDES AS AGRUPADOR,CEN.CNCDSC
FROM  HOSVITAL.MAEATE M
LEFT JOIN HOSVITAL.MAEATE2 M2  ON (M2.MPNFAC = M.MPNFAC)
INNER JOIN HOSVITAL.INGRESOS I ON ( I.MPTDOC=M.MPTDOC AND I.MPCEDU=M.MPCEDU AND I.INGCSC = M.MACTVING)
INNER JOIN HOSVITAL.MAEEMP MAE ON (MAE.MENNIT = M.MPMENI)
INNER JOIN HOSVITAL.MAEPRO MAEPRO ON (MAEPRO.PRCODI = M2.PRCODI)
INNER JOIN HOSVITAL.TIPPROC TIP ON (TIP.TIPRCOD = MAEPRO.TPPRCD)
INNER JOIN HOSVITAL.CENCOST CEN ON (CEN.CNCCOD = M2.FCPCODSCC)
WHERE M.MATIPDOC='2' AND M.FACFCH >= '2019-01-01' AND M.FACFCH <= '2019-01-31' AND M.MPMENI IN ('290','161') AND M2.FCPTPOTRN='F' AND M2.MAESANUP <> 'S '
UNION
SELECT  I.MPTDOC TIPO_DOC ,I.MPCEDU DOCUMENTO, I.INGCSC AS INGRESO,M.MPNFAC FACTURA, M.FACFCH FECHA_FACTURA, M3.MACSCS,  M3.MSRESO,MAESUM1.MSNOMG, M3.MACANS,M3.MAVATS, 'INSUMOS' AS AGRUPADOR,CEN.CNCDSC
FROM  HOSVITAL.MAEATE M
LEFT JOIN HOSVITAL.MAEATE3 M3  ON (M3.MPNFAC = M.MPNFAC)
INNER JOIN HOSVITAL.INGRESOS I ON ( I.MPTDOC=M.MPTDOC AND I.MPCEDU=M.MPCEDU AND I.INGCSC = M.MACTVING)
INNER JOIN HOSVITAL.MAEEMP MAE ON (MAE.MENNIT = M.MPMENI)
INNER JOIN HOSVITAL.MAESUM1 MAESUM1 ON (MAESUM1.MSRESO= M3.MSRESO)
INNER JOIN HOSVITAL.CENCOST CEN ON (CEN.CNCCOD = M3.MACENCOS)
WHERE M.MATIPDOC='2' AND M.FACFCH >= '2019-01-01' AND M.FACFCH <= '2019-01-31' AND M.MPMENI IN ('290','161')  AND M3.FCSTPOTRN='F' AND M3.MAESANUS <> 'S ';


SELECT * FROM HOSVITAL.MAEATE3;

SELECT  I.MPTDOC TIPO_DOC ,I.MPCEDU DOCUMENTO, I.INGCSC AS INGRESO,M.MPNFAC FACTURA, M.FACFCH FECHA_FACTURA, M2.PRCODI,MAEPRO.PRNOMB, M2.MACANPR,M2.MAVATP, TIP.TIPRDES AS AGRUPADOR,CEN.CNCDSC
FROM  HOSVITAL.MAEATE M
LEFT JOIN HOSVITAL.MAEATE2 M2  ON (M2.MPNFAC = M.MPNFAC)
INNER JOIN HOSVITAL.INGRESOS I ON ( I.MPTDOC=M.MPTDOC AND I.MPCEDU=M.MPCEDU AND I.INGCSC = M.MACTVING)
INNER JOIN HOSVITAL.MAEEMP MAE ON (MAE.MENNIT = M.MPMENI)
INNER JOIN HOSVITAL.MAEPRO MAEPRO ON (MAEPRO.PRCODI = M2.PRCODI)
INNER JOIN HOSVITAL.TIPPROC TIP ON (TIP.TIPRCOD = MAEPRO.TPPRCD)
INNER JOIN HOSVITAL.CENCOST CEN ON (CEN.CNCCOD = M2.FCPCODSCC)
WHERE M.MATIPDOC='2' AND M.FACFCH >= '2018-07-01' AND M.MPMENI IN ('290','161') AND M.MPNFAC = 540492 AND M2.FCPTPOTRN='F' AND M2.MAESANUP <> 'S ';


SELECT  I.MPTDOC TIPO_DOC ,I.MPCEDU DOCUMENTO, I.INGCSC AS INGRESO,M.MPNFAC FACTURA, M.FACFCH FECHA_FACTURA, M3.MSRESO,MAESUM1.MSNOMG, M3.MACANS,M3.MAVATS, 'INSUMOS' AS AGRUPADOR,CEN.CNCDSC
FROM  HOSVITAL.MAEATE M
LEFT JOIN HOSVITAL.MAEATE3 M3  ON (M3.MPNFAC = M.MPNFAC)
INNER JOIN HOSVITAL.INGRESOS I ON ( I.MPTDOC=M.MPTDOC AND I.MPCEDU=M.MPCEDU AND I.INGCSC = M.MACTVING)
INNER JOIN HOSVITAL.MAEEMP MAE ON (MAE.MENNIT = M.MPMENI)
INNER JOIN HOSVITAL.MAESUM1 MAESUM1 ON (MAESUM1.MSRESO= M3.MSRESO)
INNER JOIN HOSVITAL.CENCOST CEN ON (CEN.CNCCOD = M3.MACENCOS)
WHERE M.MATIPDOC='2' AND M.FACFCH >= '2018-07-01' AND M.MPMENI IN ('290','161') AND M.MPNFAC = 540492 AND M3.FCSTPOTRN='F' AND M3.MAESANUS <> 'S ';


