SELECT DISTINCT HOSVITAL.MAEATE.MPNFAC AS FACTURA, '110010413101' AS COD_PRESTADOR,  HOSVITAL.MAEATE.MPTDOC AS TIPO_DOC, HOSVITAL.MAEATE.MPCEDU AS CEDULA, DATE(HOSVITAL.INGRESOS.INGFECADM) AS FECHA_INGRESO, TIME(HOSVITAL.INGRESOS.INGFECADM) AS HORA_ING, HOSVITAL.MAEATE.MPNUMA AS NUM_AUT, HOSVITAL.MAEATE.MACAUE AS CAUSA_EXTERNA, HOSVITAL.INGRESOS.INGSALDX AS DX_SAL, HOSVITAL.MAEATE.MADI1I AS DX_REL_1, HOSVITAL.MAEATE.MADI2I AS DX_REL_2, HOSVITAL.MAEATE.MADI3I AS DX_REL_3, CASE HOSVITAL.MAEATE.MPCLPR WHEN '2' THEN '3' WHEN '3' THEN '1' END AS DESTINO, CASE HOSVITAL.INGRESOS.INGESTSLD WHEN '1' THEN '1' WHEN '0' THEN '2' END AS EST_SALIDA, HOSVITAL.MAEPAB11.HISCAMFEC AS FECHA_CAMB_SERV, HOSVITAL.MAEPAB11.HISCAMHOR AS HORA_CAMB_SERV, DATE(HOSVITAL.INGRESOS.INGFECEGR) AS FECHA_EGRE_URG, TIME(HOSVITAL.INGRESOS.INGFECEGR) AS HORA_EGRE_URG, HOSVITAL.MAEPAB11.MPNUMC AS CAMA
FROM HOSVITAL.ADMGLO11 
INNER JOIN (HOSVITAL.MAEPAB11 
RIGHT JOIN (HOSVITAL.MAEATE 
INNER JOIN HOSVITAL.INGRESOS ON (HOSVITAL.MAEATE.MACTVING = HOSVITAL.INGRESOS.INGCSC) AND (HOSVITAL.MAEATE.MPTDOC = HOSVITAL.INGRESOS.MPTDOC) AND (HOSVITAL.MAEATE.MPCEDU = HOSVITAL.INGRESOS.MPCEDU)) ON (HOSVITAL.MAEPAB11.HISCNSING = HOSVITAL.INGRESOS.INGCSC) AND (HOSVITAL.MAEPAB11.MPTDOC = HOSVITAL.INGRESOS.MPTDOC) AND (HOSVITAL.MAEPAB11.MPCEDU = HOSVITAL.INGRESOS.MPCEDU)) ON (HOSVITAL.ADMGLO11.MATIPDOC = HOSVITAL.MAEATE.MATIPDOC) AND (HOSVITAL.ADMGLO11.MPNFAC = HOSVITAL.MAEATE.MPNFAC) 
WHERE HOSVITAL.ADMGLO11.AGLREMNR=22838 ORDER BY   HOSVITAL.MAEATE.MPNFAC
;

select * from hosvital.admglo11 where mpnfac =572765;
select * from hosvital.admglo11 where AGLREMNR =22838;

select * from hosvital.maepab11 where mpcedu = '5711809';
select * from hosvital.ingresos where mpcedu = '5711809';  -- 2019-04-14 04:35:30.000000	

select * from hosvital.hccom1 where hisckey= '5711809'  and hctvin1= 9 order by hiscsec;
select * from hosvital.maeate2 where mpnfac =576480;



SELECT DISTINCT MAEATE.MPNFAC AS FACTURA, '110010413101' AS COD_PRESTADOR, MAEATE.MPTDOC AS TIPO_DOC, MAEATE.MPCEDU AS CEDULA, DATE(INGRESOS.INGFECADM) AS FECHA_INGRESO, TIME(INGRESOS.INGFECADM) AS HORA_ING, MAEATE.MPNUMA AS NUM_AUT, MAEATE.MACAUE AS CAUSA_EXTERNA, INGRESOS.INGSALDX AS DX_SAL, MAEATE.MADI1I AS DX_REL_1,MAEATE.MADI2I AS DX_REL_2, ' ' AS DX_REL_3, CASE MAEATE.MPCLPR WHEN '2' THEN '3' WHEN '3' THEN '1' END AS DESTINO, CASE INGRESOS.INGESTSLD WHEN '1' THEN '1' WHEN '0' THEN '2' END AS EST_SALIDA,      ingresos.ingcaum as Col,
(select case when max(x.hiscamfec) is NULL then date(ingresos.ingfecegr) else max(x.hiscamfec) end
FROM HOSVITAL.MAEPAB11 X
WHERE X.MPTDOC=INGRESOS.MPTDOC AND X.MPCEDU=INGRESOS.MPCEDU AND X.HISCNSING=INGRESOS.INGCSC 

) AS FECHA_EGRESO_CAMA,
(SELECT case when  max(x.hiscamhor) is NULL then time(ingresos.ingfecegr) else max(x.hiscamhor) end
FROM HOSVITAL.MAEPAB11 X
WHERE X.MPTDOC=INGRESOS.MPTDOC AND X.MPCEDU=INGRESOS.MPCEDU AND X.HISCNSING=INGRESOS.INGCSC AND
  concat(concat(varchar_format(cast(X.HISCAMFEC as timestamp) , 'YYYY-MM-DD'),' ')  , X.HISCAMHOR)  = (SELECT  MAX(concat(concat(varchar_format(cast(Y.HISCAMFEC as timestamp) , 'YYYY-MM-DD'),' ')  , Y.HISCAMHOR)) FROM HOSVITAL.MAEPAB11 Y WHERE Y.MPTDOC=X.MPTDOC AND Y.MPCEDU=X.MPCEDU AND Y.HISCNSING=X.HISCNSING)

) AS HORA_EGRESO_CAMA,
maepab11.mpnumc as cama,
ingresos.ingfecegr
FROM HOSVITAL.ADMGLO11 ADMGLO11
INNER  JOIN HOSVITAL.MAEATE  MAEATE ON (MAEATE.MATIPDOC=ADMGLO11.MATIPDOC AND MAEATE.MPNFAC = ADMGLO11.MPNFAC)
INNER JOIN HOSVITAL.INGRESOS  INGRESOS ON (INGRESOS.INGCSC=MAEATE.MACTVING AND INGRESOS.MPTDOC=MAEATE.MPTDOC  AND INGRESOS.MPCEDU=MAEATE.MPCEDU)
LEFT JOIN HOSVITAL.MAEPAB11  MAEPAB11 ON  (MAEPAB11.MPTDOC=INGRESOS.MPTDOC AND MAEPAB11.MPCEDU=INGRESOS.MPCEDU AND MAEPAB11.HISCNSING=INGRESOS.INGCSC)
WHERE ADMGLO11.AGLREMNR=22838    -- AND ADMGLO11.MPNFAC = 574116
ORDER BY MAEATE.MPNFAC;





SELECT DISTINCT MAEATE.MPNFAC AS FACTURA, '110010413101' AS COD_PRESTADOR, MAEATE.MPTDOC AS TIPO_DOC, MAEATE.MPCEDU AS CEDULA, DATE(INGRESOS.INGFECADM) AS FECHA_INGRESO, TIME(INGRESOS.INGFECADM) AS HORA_ING, MAEATE.MPNUMA AS NUM_AUT, MAEATE.MACAUE AS CAUSA_EXTERNA, INGRESOS.INGSALDX AS DX_SAL, MAEATE.MADI1I AS DX_REL_1,MAEATE.MADI2I AS DX_REL_2, MAEATE.MADI3I AS DX_REL_3, CASE MAEATE.MPCLPR WHEN '2' THEN '3' WHEN '3' THEN '1' END AS DESTINO, CASE INGRESOS.INGESTSLD WHEN '1' THEN '1' WHEN '0' THEN '2' END AS EST_SALIDA,
(SELECT CASE WHEN X.HISCAMFEC <> '' THEN MAX(X.HISCAMFEC) ELSE DATE(INGRESOS.INGFECEGR) END
FROM HOSVITAL.MAEPAB11 X
WHERE X.MPTDOC=INGRESOS.MPTDOC AND X.MPCEDU=INGRESOS.MPCEDU AND X.HISCNSING=INGRESOS.INGCSC  AND X.MPCODP IN ( 7,35,23,21,20,18)

) AS FECHA_EGRESO_CAMA,
(SELECT X.HISCAMHOR
FROM HOSVITAL.MAEPAB11 X
WHERE X.MPTDOC=INGRESOS.MPTDOC AND X.MPCEDU=INGRESOS.MPCEDU AND X.HISCNSING=INGRESOS.INGCSC AND  X.MPCODP IN ( 7,35,23,21,20,18) AND
  concat(concat(varchar_format(cast(X.HISCAMFEC as timestamp) , 'YYYY-MM-DD'),' ')  , X.HISCAMHOR)  = (SELECT  MAX(concat(concat(varchar_format(cast(Y.HISCAMFEC as timestamp) , 'YYYY-MM-DD'),' ')  , Y.HISCAMHOR)) FROM HOSVITAL.MAEPAB11 Y WHERE Y.MPTDOC=X.MPTDOC AND Y.MPCEDU=X.MPCEDU AND Y.HISCNSING=X.HISCNSING AND X.MPCODP=Y.MPCODP)

) AS HORA_EGRESO_CAMA

FROM HOSVITAL.ADMGLO11 ADMGLO11
INNER  JOIN HOSVITAL.MAEATE  MAEATE ON (MAEATE.MATIPDOC=ADMGLO11.MATIPDOC AND MAEATE.MPNFAC = ADMGLO11.MPNFAC)
INNER JOIN HOSVITAL.INGRESOS  INGRESOS ON (INGRESOS.INGCSC=MAEATE.MACTVING AND INGRESOS.MPTDOC=MAEATE.MPTDOC  AND INGRESOS.MPCEDU=MAEATE.MPCEDU)
LEFT JOIN HOSVITAL.MAEPAB11  MAEPAB11 ON  (MAEPAB11.MPTDOC=INGRESOS.MPTDOC AND MAEPAB11.MPCEDU=INGRESOS.MPCEDU AND MAEPAB11.HISCNSING=INGRESOS.INGCSC)
WHERE ADMGLO11.AGLREMNR=?	

ORDER BY MAEATE.MPNFAC;

SELECT M2.MPCODP, MPNOMP, MPNUMC
 FROM HOSVITAL.MAEPAB1 M1, HOSVITAL.MAEPAB M2
WHERE M2.MPCODP = M1.MPCODP
 ORDER BY M2.MPCODP ,M1.MPNUMC;

--CODIGOS   7,35,23,21,20,18


SELECT * FROM HOSVITAL.INGRESOS ; --  WHERE ingfchm>= '2019-01-01 00:00:00'	;


SELECT * FROM HOSVITAL.MAEPAB11 WHERE MPCEDU='3214606' AND HISCNSING=47;


/* aparte
(select max(case when x.hiscamfec = '0001-01-01'  then date(i2.ingfecegr) else x.hiscamfec end)
FROM hosvital.ingresos i2
left join HOSVITAL.MAEPAB11 X on ( x.mptdoc=i2.mptdoc and x.mpcedu=i2.mpcedu and x.HISCNSING=i2.ingcsc  )
WHERE X.MPTDOC=INGRESOS.MPTDOC AND X.MPCEDU=INGRESOS.MPCEDU AND X.HISCNSING=INGRESOS.INGCSC and i2.mptdoc=INGRESOS.MPTDOC  and i2.mpcedu=ingresos.mpcedu and i2.ingcsc=ingresos.ingcsc 

) AS FECHA_EGRESO_CAMA,


*/